Delivered-To: cecycorrea@gmail.com
Received: by 10.159.54.171 with SMTP id p40csp274048uap;
Mon, 23 May 2016 11:56:30 -0700 (PDT)
X-Received: by 10.55.21.16 with SMTP id f16mr441547qkh.38.1464029790841;
Mon, 23 May 2016 11:56:30 -0700 (PDT)
Return-Path: <Travis_Swicegood@condenast.com>
Received: from na01-bl2-obe.outbound.protection.outlook.com (mail-bl2on0097.outbound.protection.outlook.com. [65.55.169.97])
by mx.google.com with ESMTPS id a139si31064465qkc.140.2016.05.23.11.56.30
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-SHA bits=128/128);
Mon, 23 May 2016 11:56:30 -0700 (PDT)
Received-SPF: pass (google.com: domain of Travis_Swicegood@condenast.com designates 65.55.169.97 as permitted sender) client-ip=65.55.169.97;
Authentication-Results: mx.google.com;
dkim=pass header.i=@advancepublications.onmicrosoft.com;
spf=pass (google.com: domain of Travis_Swicegood@condenast.com designates 65.55.169.97 as permitted sender) smtp.mailfrom=Travis_Swicegood@condenast.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=advancepublications.onmicrosoft.com; s=selector1-condenast-com;
h=From:To:Date:Subject:Message-ID:Content-Type:MIME-Version;
bh=7gQGtzad/QjUpzHJPoqB60qIA9/7XzmGpOs2hZWl4As=;
b=TvRUhLDdNr1T2jbNugFULlByZQZWVL1DO0/1ma0jqeVq4akyIn/DsEly8YOxZ4OpC+olJdu5MJKI+PIpc4X9cSrTILcdcQhKEX3DHV9SImuEZTtyMh1RhcSDKrIOYZUOrI5mDuwq5S7K9RcqS11GTQicfdMcg3DmRMPUXq2qvD4=
Received: from BY1PR02MB1243.namprd02.prod.outlook.com (10.162.108.29) by
BY1PR02MB1241.namprd02.prod.outlook.com (10.162.108.27) with Microsoft SMTP
Server (TLS) id 15.1.497.12; Mon, 23 May 2016 18:56:29 +0000
Received: from BY1PR02MB1243.namprd02.prod.outlook.com ([10.162.108.29]) by
BY1PR02MB1243.namprd02.prod.outlook.com ([10.162.108.29]) with mapi id
15.01.0497.019; Mon, 23 May 2016 18:56:29 +0000
From: "Swicegood, Travis" <Travis_Swicegood@condenast.com>
To: Cecy Correa <cecycorrea@gmail.com>
Subject: Re: Austin on Rails tomorrow
Thread-Topic: Austin on Rails tomorrow
Thread-Index: AQHRtR5+14Zc7OSbzkybwuRNE9Ncnp/G32IA
Date: Mon, 23 May 2016 18:56:29 +0000
Message-ID: <etPan.5743525c.15e58cf1.172e5@X00041816140408>
References: <CAL4Zj++_bF+Jv-VH+k9X3T1RyA2iM0=gL4w_O6K8GEWdzCN9JA@mail.gmail.com>
In-Reply-To: <CAL4Zj++_bF+Jv-VH+k9X3T1RyA2iM0=gL4w_O6K8GEWdzCN9JA@mail.gmail.com>
Accept-Language: en-US
Content-Language: en-US
X-MS-Has-Attach:
X-MS-TNEF-Correlator:
authentication-results: gmail.com; dkim=none (message not signed)
header.d=none;gmail.com; dmarc=none action=none header.from=condenast.com;
x-originating-ip: [67.79.8.126]
x-ms-office365-filtering-correlation-id: 91d7d21d-6ee0-48f9-224a-08d3833bf351
x-microsoft-exchange-diagnostics: 1;BY1PR02MB1241;5:rRnjnkKExHrkRUY7vWyDsoJEAKorQHN9EV2c51979IVlAY9fzbomWkf0BrYTpOpHRzfAIgVYc9lr1V4ggs7JfqpRsYaAGHhXBtTVQnYVVBTs3OjdytNuG447dq4Yn4/RLVNZ0/gsLfESLjilAi46Dg==;24:3BEeT/LZXN0u0QFg3/uOWFD01BRMQ1aMojPeBNGWJT7g59IFp65A+iGRD+584R0PJ8Rf3n4eriiRPQMLy/PH1FedAt1UZHSGomjwweVrvnQ=;7:L6Myh6SnJxE0Kch8UdxfYQb3UBX8DDv1gb0SqG6Gu6N8rqiKtjTXo40A9+fSDmVkYRfpCZLQSGPLhhNUDkRD5BLMqyHiDYtCzNNmjLUcLu4xfsGKk298OAYQz7CTLxyRZ3KV5H3huvPGeodUF3KVzDEPnJ/gyuJKC2lMWALDd6BVj7q+r1eSK19qwgNzf1gA
x-microsoft-antispam: UriScan:;BCL:0;PCL:0;RULEID:;SRVR:BY1PR02MB1241;
x-microsoft-antispam-prvs: <BY1PR02MB12415BA4475E08068C0784D2E24E0@BY1PR02MB1241.namprd02.prod.outlook.com>
x-exchange-antispam-report-test: UriScan:;
x-exchange-antispam-report-cfa-test: BCL:0;PCL:0;RULEID:(601004)(2401047)(5005006)(8121501046)(10201501046)(3002001)(6055026);SRVR:BY1PR02MB1241;BCL:0;PCL:0;RULEID:;SRVR:BY1PR02MB1241;
x-forefront-prvs: 0951AB0A30
x-forefront-antispam-report: SFV:NSPM;SFS:(10009020)(24454002)(377454003)(1411001)(2860100001)(3280700002)(2950100001)(2900100001)(10400500002)(77096005)(189998001)(80792005)(33716001)(3480700004)(3660700001)(1220700001)(6116002)(66066001)(586003)(5002640100001)(102836003)(5008740100001)(8936002)(8676002)(50986999)(99286002)(106116001)(76176999)(122556002)(450100001)(107886002)(54356999)(110136002)(5004730100002)(11100500001)(92566002)(87936001)(19580395003)(2906002)(19580405001)(9686002)(16236675004)(81166006)(3846002)(86362001);DIR:OUT;SFP:1101;SCL:1;SRVR:BY1PR02MB1241;H:BY1PR02MB1243.namprd02.prod.outlook.com;FPR:;SPF:None;MLV:sfv;LANG:en;
spamdiagnosticoutput: 1:23
spamdiagnosticmetadata: NSPM
Content-Type: multipart/alternative;
boundary="_000_etPan5743525c15e58cf1172e5X00041816140408_"
MIME-Version: 1.0
X-OriginatorOrg: condenast.com
X-MS-Exchange-CrossTenant-originalarrivaltime: 23 May 2016 18:56:29.7391
(UTC)
X-MS-Exchange-CrossTenant-fromentityheader: Hosted
X-MS-Exchange-CrossTenant-id: 14a59442-0cf9-46f0-9f4d-662504c4084f
X-MS-Exchange-Transport-CrossTenantHeadersStamped: BY1PR02MB1241

--_000_etPan5743525c15e58cf1172e5X00041816140408_
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64

Q2xvc2luZyB0aGUgbG9vcCDigJQgdGhlc2UgYXJlIG9yZGVyZWQgYW5kIHNldCBmb3IgZGVsaXZl
cnkgYXQgNjozMC4gSeKAmWxsIGJlIHRoZXJlIHRvbyA6LSkNCg0KLS0NClRyYXZpcyBTd2ljZWdv
b2QNCkRpcmVjdG9yIG9mIEVuZ2luZWVyaW5nLCBDb25kw6kgTmFzdCBBVFgNCjUxMi42OTMuNzA1
MTx0ZWw6NTEyLjY5My43MDUxPiB8IEB0c3dpY2Vnb29kIChtb3N0IGV2ZXJ5d2hlcmUpDQoNCg0K
T24gTWF5IDIzLCAyMDE2IGF0IDE6MTE6MTUgUE0sIENlY3kgQ29ycmVhIChjZWN5Y29ycmVhQGdt
YWlsLmNvbTxtYWlsdG86Y2VjeWNvcnJlYUBnbWFpbC5jb20+KSB3cm90ZToNCg0KU29ycnkgYWJv
dXQgdGhlIGRlbGF5IGluIGdldHRpbmcgdGhpcyB0byB5b3UgdmlhIGVtYWlsISBGb3IgQXVzdGlu
IG9uIFJhaWxzIHRvbW9ycm93LCB0aGlzIGlzIHRoZSB0eXBpY2FsIG9yZGVyIHdlIGdldCBhdCBI
b2Jva2VuICg1MTItNDc3LTQyNTY8dGVsOjUxMi00NzctNDI1Nj4pDQoNCg0KMyBwZXBwZXJvbmkN
Cg0KMiBjaGVlc2UNCg0KMSB2ZXJhIGNydXoNCg0KMSBidXRjaGVyDQoNCjEgdG9ycmVzDQoNCjEg
bWVkaXRlcnJhbmVhbg0KDQoxIHBvcnRhYmVsbG8NCg0KNSB0d28gbGl0ZXIgYm90dGxlcyBvZiBz
b2RhDQoNCllvdSBjYW4gdXNlIGFueSBvdGhlciBwcm92aWRlciB5b3UgbWlnaHQgbGlrZSB0aG91
Z2ggOikNCg0KQXJlIHlvdSBjb21pbmcgdG9tb3Jyb3c/DQoNCkBjZWN5Y29ycmVhDQo=

--_000_etPan5743525c15e58cf1172e5X00041816140408_
Content-Type: text/html; charset="utf-8"
Content-ID: <D49C7A96C28F444B8121AA1FBD8363B3@namprd02.prod.outlook.com>
Content-Transfer-Encoding: base64

PGh0bWw+DQo8aGVhZD4NCjxtZXRhIGh0dHAtZXF1aXY9IkNvbnRlbnQtVHlwZSIgY29udGVudD0i
dGV4dC9odG1sOyBjaGFyc2V0PXV0Zi04Ij4NCjxzdHlsZT5ib2R5e2ZvbnQtZmFtaWx5OkhlbHZl
dGljYSxBcmlhbDtmb250LXNpemU6MTNweH08L3N0eWxlPg0KPC9oZWFkPg0KPGJvZHkgc3R5bGU9
IndvcmQtd3JhcDogYnJlYWstd29yZDsgLXdlYmtpdC1uYnNwLW1vZGU6IHNwYWNlOyAtd2Via2l0
LWxpbmUtYnJlYWs6IGFmdGVyLXdoaXRlLXNwYWNlOyI+DQo8ZGl2IGlkPSJibG9vcF9jdXN0b21m
b250IiBzdHlsZT0iZm9udC1mYW1pbHk6SGVsdmV0aWNhLEFyaWFsO2ZvbnQtc2l6ZToxM3B4OyBj
b2xvcjogcmdiYSgwLDAsMCwxLjApOyBtYXJnaW46IDBweDsgbGluZS1oZWlnaHQ6IGF1dG87Ij4N
CkNsb3NpbmcgdGhlIGxvb3Ag4oCUIHRoZXNlIGFyZSBvcmRlcmVkIGFuZCBzZXQgZm9yIGRlbGl2
ZXJ5IGF0IDY6MzAuIEnigJlsbCBiZSB0aGVyZSB0b28gOi0pPC9kaXY+DQo8YnI+DQo8ZGl2IGlk
PSJibG9vcF9zaWduXzE0NjQwMjk3NzQ3ODEyMTgwNDgiIGNsYXNzPSJibG9vcF9zaWduIj4NCjxk
aXYgc3R5bGU9InRleHQtYWxpZ246IGxlZnQ7Ij4tLTwvZGl2Pg0KPGRpdiBzdHlsZT0idGV4dC1h
bGlnbjogbGVmdDsiPlRyYXZpcyBTd2ljZWdvb2Q8L2Rpdj4NCjxkaXYgc3R5bGU9InRleHQtYWxp
Z246IGxlZnQ7Ij5EaXJlY3RvciBvZiBFbmdpbmVlcmluZywgQ29uZMOpIE5hc3QgQVRYPC9kaXY+
DQo8ZGl2IHN0eWxlPSJ0ZXh0LWFsaWduOiBsZWZ0OyI+PGEgZGlyPSJsdHIiIGhyZWY9InRlbDo1
MTIuNjkzLjcwNTEiIHgtYXBwbGUtZGF0YS1kZXRlY3RvcnM9InRydWUiIHgtYXBwbGUtZGF0YS1k
ZXRlY3RvcnMtdHlwZT0idGVsZXBob25lIiB4LWFwcGxlLWRhdGEtZGV0ZWN0b3JzLXJlc3VsdD0i
MCI+NTEyLjY5My43MDUxPC9hPiZuYnNwO3wgQHRzd2ljZWdvb2QgKG1vc3QgZXZlcnl3aGVyZSk8
L2Rpdj4NCjwvZGl2Pg0KPGJyPg0KPHAgY2xhc3M9ImFpcm1haWxfb24iPk9uIE1heSAyMywgMjAx
NiBhdCAxOjExOjE1IFBNLCBDZWN5IENvcnJlYSAoPGEgaHJlZj0ibWFpbHRvOmNlY3ljb3JyZWFA
Z21haWwuY29tIj5jZWN5Y29ycmVhQGdtYWlsLmNvbTwvYT4pIHdyb3RlOjwvcD4NCjxibG9ja3F1
b3RlIHR5cGU9ImNpdGUiIGNsYXNzPSJjbGVhbl9icSI+PHNwYW4+DQo8ZGl2Pg0KPGRpdj48L2Rp
dj4NCjxkaXY+DQo8dGl0bGU+PC90aXRsZT4NCjxkaXYgZGlyPSJsdHIiPg0KPGRpdj5Tb3JyeSBh
Ym91dCB0aGUgZGVsYXkgaW4gZ2V0dGluZyB0aGlzIHRvIHlvdSB2aWEgZW1haWwhIEZvciBBdXN0
aW4gb24gUmFpbHMgdG9tb3Jyb3csIHRoaXMgaXMgdGhlIHR5cGljYWwgb3JkZXIgd2UgZ2V0IGF0
IEhvYm9rZW4gKDxzcGFuIGNsYXNzPSIiPjxhIGhyZWY9InRlbDo1MTItNDc3LTQyNTYiPjUxMi00
NzctNDI1NjwvYT4pPC9zcGFuPjwvZGl2Pg0KPGRpdj48YnI+DQo8L2Rpdj4NCjxkaXY+DQo8cCBj
bGFzcz0iIj48c3BhbiBjbGFzcz0iIj4zIHBlcHBlcm9uaTwvc3Bhbj48L3A+DQo8cCBjbGFzcz0i
Ij48c3BhbiBjbGFzcz0iIj4yIGNoZWVzZTwvc3Bhbj48L3A+DQo8cCBjbGFzcz0iIj48c3BhbiBj
bGFzcz0iIj4xIHZlcmEgY3J1ejwvc3Bhbj48L3A+DQo8cCBjbGFzcz0iIj48c3BhbiBjbGFzcz0i
Ij4xIGJ1dGNoZXI8L3NwYW4+PC9wPg0KPHAgY2xhc3M9IiI+PHNwYW4gY2xhc3M9IiI+MSB0b3Jy
ZXM8L3NwYW4+PC9wPg0KPHAgY2xhc3M9IiI+PHNwYW4gY2xhc3M9IiI+MSBtZWRpdGVycmFuZWFu
PC9zcGFuPjwvcD4NCjxwIGNsYXNzPSIiPjxzcGFuIGNsYXNzPSIiPjEgcG9ydGFiZWxsbzwvc3Bh
bj48L3A+DQo8cCBjbGFzcz0iIj41IHR3byBsaXRlciBib3R0bGVzIG9mIHNvZGE8L3A+DQo8L2Rp
dj4NCjxkaXY+PGJyPg0KPC9kaXY+DQo8ZGl2PllvdSBjYW4gdXNlIGFueSBvdGhlciBwcm92aWRl
ciB5b3UgbWlnaHQgbGlrZSB0aG91Z2ggOik8L2Rpdj4NCjxkaXY+PGJyPg0KQXJlIHlvdSBjb21p
bmcgdG9tb3Jyb3c/PC9kaXY+DQo8YnIgY2xlYXI9ImFsbCI+DQo8ZGl2Pg0KPGRpdiBjbGFzcz0i
Z21haWxfc2lnbmF0dXJlIj4NCjxkaXYgZGlyPSJsdHIiPjxiPkBjZWN5Y29ycmVhPC9iPjwvZGl2
Pg0KPC9kaXY+DQo8L2Rpdj4NCjwvZGl2Pg0KPC9kaXY+DQo8L2Rpdj4NCjwvc3Bhbj48L2Jsb2Nr
cXVvdGU+DQo8L2JvZHk+DQo8L2h0bWw+DQo=

--_000_etPan5743525c15e58cf1172e5X00041816140408_--
