Delivered-To: cecycorrea@gmail.com
Received: by 10.176.5.194 with SMTP id e60csp43877uae;
Fri, 20 May 2016 15:01:44 -0700 (PDT)
X-Received: by 10.129.46.149 with SMTP id u143mr3307536ywu.170.1463781704606;
Fri, 20 May 2016 15:01:44 -0700 (PDT)
Return-Path: <allison@onemorecloud.com>
Received: from mail-yw0-x231.google.com (mail-yw0-x231.google.com. [2607:f8b0:4002:c05::231])
by mx.google.com with ESMTPS id l134si9894672ybl.281.2016.05.20.15.01.44
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Fri, 20 May 2016 15:01:44 -0700 (PDT)
Received-SPF: neutral (google.com: 2607:f8b0:4002:c05::231 is neither permitted nor denied by best guess record for domain of allison@onemorecloud.com) client-ip=2607:f8b0:4002:c05::231;
Authentication-Results: mx.google.com;
dkim=pass header.i=@onemorecloud-com.20150623.gappssmtp.com;
spf=neutral (google.com: 2607:f8b0:4002:c05::231 is neither permitted nor denied by best guess record for domain of allison@onemorecloud.com) smtp.mailfrom=allison@onemorecloud.com
Received: by mail-yw0-x231.google.com with SMTP id x189so121620309ywe.3
for <cecycorrea@gmail.com>; Fri, 20 May 2016 15:01:44 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=onemorecloud-com.20150623.gappssmtp.com; s=20150623;
h=mime-version:date:message-id:subject:from:to;
bh=qc7YnKzDAuq+X3hmstWMIPWLPQwqGp4Dfo3Sn1QsSoA=;
b=FoqRSQTCsvP/tJQ6GNmqHfqgCOpVU8ySCEn/S6wPHizqHksJULHj7mmIU2j6RX6p3m
YiGor6E5Rp9dzX0K/X0omcvyWwqggeAMWByYkIek58ot2GPD0GoY0GSylWM7WeXW8L3Q
7KcqypyRUtgCZDvgsFAB+t4jbQ6eqEgiWnmBK17xWDvXM4JCa4vXgPoe2/7xumdKAcBh
dTpv94lNQgLrk8p/XyfTQQLDiHf8OLApTBOxPEPCiwtfRbk9Hr5tuJc+fxI86rAfAk3b
gWAGY1Gnd7Osfo3O6AKnRdTpneAgYNDhTBWmoqcZqxT/3MhP/sRf5e02MhXrKHhcAajX
RK0A==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:date:message-id:subject:from:to;
bh=qc7YnKzDAuq+X3hmstWMIPWLPQwqGp4Dfo3Sn1QsSoA=;
b=ZIvVjETd1CYD6ZiIOOqlb7uEWy/fuNAfKgljeFQzYzaEJXpJCZFxLTbAsIj6tTENc5
sCKPTKp1owcewmaaWZ5YVWagPsH6w2aGpzlSfSq8ne9y/p4smGo0uXdASgSDitUTXy/y
Dk9uZ84sGukX6oGdcJ30N03+yZg8+vfK/zD39EueBrN5dWsJHAOPpwqTMM5j1R5+5GG/
MhLzdih0/Pse6HZvK6K7MIfo/rfP7ISmpMm14j4c5YC86A2OBNr1DA3vmwh0nXh35Mi6
E3ZoxaQkBs8/4cPs/ruXLuUN8oY5HEijLva4jCR+VBNQMu61B7eegA51RR/G2pCVE9yI
F2yA==
X-Gm-Message-State: AOPr4FX+6XBNbid/qANFV4B5jCLX487XxZ9KKwBJ3GuJdS1jnSNLT0ZwpgRA78TvuPeyFAy6lFsElzqUZl4hWQ==
MIME-Version: 1.0
X-Received: by 10.13.214.199 with SMTP id y190mr3227437ywd.241.1463781704315;
Fri, 20 May 2016 15:01:44 -0700 (PDT)
Received: by 10.129.9.214 with HTTP; Fri, 20 May 2016 15:01:44 -0700 (PDT)
X-Originating-IP: [2605:a601:1130:d100:ddea:1263:3646:86af]
Date: Fri, 20 May 2016 17:01:44 -0500
Message-ID: <CAHWHXu=qKsoYg70Z673Ck8UvfxEyZrQM4+E4o-_z_fLhBNCHpQ@mail.gmail.com>
Subject: AOR Sponsorship
From: Allison Zadrozny <allison@onemorecloud.com>
To: cecycorrea@gmail.com
Content-Type: multipart/alternative; boundary=94eb2c0766c683e45f05334d3c94

--94eb2c0766c683e45f05334d3c94
Content-Type: text/plain; charset=UTF-8

Hello Cecy,

One More Cloud would like to sponsor AOR. We've never done it before so can
you give me some context in terms of how much we should expect to sponsor,
and how I should coordinate for payment?

Thank you! Looking forward to the talks this Tuesday.

Best,
Allison

--94eb2c0766c683e45f05334d3c94
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hello Cecy,<div><br></div><div>One More Cloud would like t=
o sponsor AOR. We&#39;ve never done it before so can you give me some conte=
xt in terms of how much we should expect to sponsor, and how I should coord=
inate for payment?</div><div><br></div><div>Thank you! Looking forward to t=
he talks this Tuesday.</div><div><br></div><div>Best,</div><div>Allison</di=
v></div>

--94eb2c0766c683e45f05334d3c94--
