Delivered-To: cecycorrea@gmail.com
Received: by 10.176.5.194 with SMTP id e60csp311098uae;
Fri, 13 May 2016 08:59:26 -0700 (PDT)
X-Received: by 10.140.92.65 with SMTP id a59mr15604760qge.93.1463155166764;
Fri, 13 May 2016 08:59:26 -0700 (PDT)
Return-Path: <shassett@oreilly.com>
Received: from mail-qg0-x236.google.com (mail-qg0-x236.google.com. [2607:f8b0:400d:c04::236])
by mx.google.com with ESMTPS id 36si12384483qgj.99.2016.05.13.08.59.26
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Fri, 13 May 2016 08:59:26 -0700 (PDT)
Received-SPF: pass (google.com: domain of shassett@oreilly.com designates 2607:f8b0:400d:c04::236 as permitted sender) client-ip=2607:f8b0:400d:c04::236;
Authentication-Results: mx.google.com;
dkim=pass header.i=@oreilly-com.20150623.gappssmtp.com;
spf=pass (google.com: domain of shassett@oreilly.com designates 2607:f8b0:400d:c04::236 as permitted sender) smtp.mailfrom=shassett@oreilly.com
Received: by mail-qg0-x236.google.com with SMTP id w36so59436574qge.3
for <cecycorrea@gmail.com>; Fri, 13 May 2016 08:59:26 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=oreilly-com.20150623.gappssmtp.com; s=20150623;
h=mime-version:from:date:message-id:subject:to;
bh=//QM64w88DOGCBGurOp00MmFwFZPFuQu9QnS1scrTew=;
b=PQykKGj/0Q3twfpUZNc9ivSuXH6uazDXggGHsTWJbMTh1F4UGYzagSpG5399kDYXL9
BGXia6cHgLCJ4WlnlghvVElL1LilgXfeo9Gkl7JX1hLXSdmc94XSKfua9/75vpqU4BVU
3lVCNj8dwi4kTwMLz5jM6SKZbmyil8PblNOmY4hGaTWSmxeeEPH29hzq6RPWPoTDjGg7
muWTaJQeOaqRJ6rZG7w2RxR+4IY1wjQwXZLruWpAmeMHmaBrURhB9kTnmq++kAXVKA9O
9dxeWk6GL0wy+zH2EIU50q81IU/g0b4KR6Op7+ZwbIP5RAKPBZWc1KyDc0ZFVDgcqinF
DaBg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
bh=//QM64w88DOGCBGurOp00MmFwFZPFuQu9QnS1scrTew=;
b=a13ZB4NsU6rBkKFpcKZ6DntWot6uYiymeYssICZBP7KCaoEhPcUchBBwTU8AipFmfN
7qfOpjSMB1ulKSOlEmqdGSjgXPZDOC3Lk9xqDV8kv1tUoJRbIfiYmtqES/SgqaMVB2Rt
TebtcGeN4bbhdrhjOjUZIMBlHrDd3WytbKDDQklWROQWZrU+5mxJqbEf94yseiEc15PC
xj0DRtO/TkXnRbZ5Samf4CEaWw2+imXtFu2b/qOQK3oPMCOWDE2HugSR5u7nCYFaSQGt
v8mtPr8P2wMgaMo+9dIyKJ0p8E0DK0W8hg0Rs2z06QH3HFIPyreElg8P285rsNyNczwE
KaPA==
X-Gm-Message-State: AOPr4FV/Q5LMOQFL7hT4L7jwnLm9UhkthKBpGODj5pr5pNw8lNNi2hRWcpv72k6I+dkCQoyCZQSA0Cnw+PBoC4Vn
X-Received: by 10.140.20.43 with SMTP id 40mr16015900qgi.15.1463155166535;
Fri, 13 May 2016 08:59:26 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.55.192.68 with HTTP; Fri, 13 May 2016 08:58:47 -0700 (PDT)
From: Sherry Hassett <shassett@oreilly.com>
Date: Fri, 13 May 2016 08:58:47 -0700
Message-ID: <CALWyCvre3-4nVp6fnOPubOdZK=ne024X1W5O3Os6SoiwtGCBdg@mail.gmail.com>
Subject: Books for GDI, Austin on Rails
To: Cecy Correa <cecycorrea@gmail.com>
Content-Type: multipart/alternative; boundary=001a11c128baf422eb0532bb5b55

--001a11c128baf422eb0532bb5b55
Content-Type: text/plain; charset=UTF-8

Hi Cecy -

We will have display books after OSCON is over that we would like to donate
to local meetup groups. I have about 4 or so that I am extending this offer
to and of course, you are one of them.

If you would like to come by the O'Reilly booth about 4:30pm on Thursday -
you can take 20-25 books to use for your community any way you like.

Please let me know if you are interested, since if not, I'll offer this to
other groups in the local area.

-Sherry

--001a11c128baf422eb0532bb5b55
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hi Cecy -<div><br></div><div>We will have display books af=
ter OSCON is over that we would like to donate to local meetup groups. I ha=
ve about 4 or so that I am extending this offer to and of course, you are o=
ne of them.</div><div><br></div><div>If you would like to come by the O&#39=
;Reilly booth about 4:30pm on Thursday - you can take 20-25 books to use fo=
r your community any way you like.</div><div><br></div><div>Please let me k=
now if you are interested, since if not, I&#39;ll offer this to other group=
s in the local area.</div><div><br></div><div>-Sherry<br clear=3D"all"><div=
><br></div><div class=3D"gmail_signature"><div dir=3D"ltr"><div><br></div><=
/div></div>
</div></div>

--001a11c128baf422eb0532bb5b55--
