Delivered-To: cecy.correa@returnpath.com
Received: by 10.112.141.5 with SMTP id rk5csp315115lbb;
Fri, 25 Mar 2016 08:57:07 -0700 (PDT)
X-Received: by 10.182.50.136 with SMTP id c8mr7550742obo.66.1458921427564;
Fri, 25 Mar 2016 08:57:07 -0700 (PDT)
Return-Path: <atom@twilio.com>
Received: from mail-ig0-x22e.google.com (mail-ig0-x22e.google.com. [2607:f8b0:4001:c05::22e])
by mx.google.com with ESMTPS id wk1si468230obc.82.2016.03.25.08.57.07
for <cecy.correa@returnpath.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Fri, 25 Mar 2016 08:57:07 -0700 (PDT)
Received-SPF: pass (google.com: domain of atom@twilio.com designates 2607:f8b0:4001:c05::22e as permitted sender) client-ip=2607:f8b0:4001:c05::22e;
Authentication-Results: mx.google.com;
dkim=pass header.i=@twilio-com.20150623.gappssmtp.com;
spf=pass (google.com: domain of atom@twilio.com designates 2607:f8b0:4001:c05::22e as permitted sender) smtp.mailfrom=atom@twilio.com
Received: by mail-ig0-x22e.google.com with SMTP id cl4so14768126igb.0
for <cecy.correa@returnpath.com>; Fri, 25 Mar 2016 08:57:07 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=twilio-com.20150623.gappssmtp.com; s=20150623;
h=mime-version:date:message-id:subject:from:to;
bh=vHLcXMDPHWDMpSRz75ujOV/g7YDl/R7muIueTCizb68=;
b=wpCFlQmvkTWxPYJpbQuQa1PcTJHxQo4Qen8HiS4VGc8jOH3+i7ViUP2Yeu0sAjJ7lp
rkrP1zFTrYsOS02mk7UjnFNXgyNNFvBjukb494iVl0bSkfD0KjjSG+dDqduFg2ycQsrK
y1wW4bXPC7IHoPFMaI7g/RQSeJqMvSVTGzZ+87OdXc0xnwZOl1pHIvgGjDntra3gwalo
3zprXEGY9UhupE9AWSXuKmh8usL01Q13vHOZ2+ELUpT9v35srlgX5kUzAfcs3+yY+ZmD
64MU2MWbfBFZzKf0l5Neax4GkclpfGxdxJ6nAhxD9Qhi6nodISm47C2y2YNah+5hObQB
0/Aw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:date:message-id:subject:from:to;
bh=vHLcXMDPHWDMpSRz75ujOV/g7YDl/R7muIueTCizb68=;
b=HC+9c1Zt5b6cFEjfavpKSwz/lCdgfkmQkhG219jzVG5XGSgx9poBQRwL480pCkuyF9
/O9lH12j/g/Pk2aXKM292LgRgSky5ROoZVD+vxUah1YlmSJUPBIXVQG1Njd507VBC2G5
Unp5DEfdjhW6XlRIlsesbUzoGBqjcnZyDQOvXOQ9L6KFOr/rCVE05xExaTlfM045lW98
qgDf7SD/6BehO/Nvh3Fo0UOSx79BhOE4Tvs6ocfuoX+/9LOkx1DYVd9i1IfBIfee2NDu
6zOIK+h1cTo8A3kvi/4w+cBSjOV2aYcLjTVw440K2j2zCiNvPazCfxIAp7YdFWZ3CDRl
IvOg==
X-Gm-Message-State: AD7BkJILMbixcd2lkF+c4AmtAtTTyDunbZvFnHnpfagf1boOjwdFS1i1Q9mV1m951tFvjbs1Hi43D1VtWLy/IvBH
MIME-Version: 1.0
X-Received: by 10.50.150.72 with SMTP id ug8mr19088548igb.52.1458921427013;
Fri, 25 Mar 2016 08:57:07 -0700 (PDT)
Received: by 10.107.4.70 with HTTP; Fri, 25 Mar 2016 08:57:06 -0700 (PDT)
Date: Fri, 25 Mar 2016 08:57:06 -0700
Message-ID: <CACwXJiWCfB4MjvCtxH1vEoXfz64fvjtpyPS5TFZegeh302ibBA@mail.gmail.com>
Subject: Follow-up from Authy
From: Andrew Tom <atom@twilio.com>
To: cecy.correa@returnpath.com
Content-Type: multipart/alternative; boundary=001a11360bf869b0ce052ee19ddb

--001a11360bf869b0ce052ee19ddb
Content-Type: text/plain; charset=UTF-8

Hi Cecy,

Just reaching out as you start to investigate our API.  How I can be of
assistance e.g. documentation, source examples, tutorials, etc.?

Thanks,
Andrew

--
Andrew Tom
Authentication Sales



Mobile: +1-415-969-2049

--001a11360bf869b0ce052ee19ddb
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr"><div class=3D"gmail_quote"><div dir=3D"ltr">Hi Cecy,<br><d=
iv><br></div><div>Just reaching out as you start to investigate our API.=C2=
=A0 How I can be of assistance e.g. documentation, source examples, tutoria=
ls, etc.?</div><div><br></div><div>Thanks,</div><div>Andrew<span class=3D"H=
OEnZb"><font color=3D"#888888"><br clear=3D"all"><div><br></div>-- <br><div=
><div dir=3D"ltr"><div><div dir=3D"ltr">Andrew Tom<div>Authentication Sales=
</div><div><br></div><div><img src=3D"https://lh5.googleusercontent.com/25l=
ZrOwk2LmchWmMOW2dml7rrGNkY-VcYYR9W0ANEBJv8SkF1139BvSXnz09Z1HnST4OQkCAwVA66i=
5VGpdh_PUy2JZpFD6faBX3Nk4jitQaJxw8a1Fd-tfxmr0MMchIXmcTz5o" width=3D"142px;"=
height=3D"35px;" style=3D"color:rgb(0,0,0);font-family:Arial;font-size:15p=
x;white-space:pre-wrap;border:none"><br></div><div><br></div><div>Mobile: <=
a href=3D"tel:%2B1-415-969-2049" value=3D"+14159692049" target=3D"_blank">+=
1-415-969-2049</a></div><div><br></div></div></div></div></div>
</font></span></div></div>
</div><br><div><br></div><div class=3D"gmail_signature"><div dir=3D"ltr"><d=
iv><div dir=3D"ltr"><div><br></div></div></div></div></div>
<font face=3D"yw-f06a75c5925c7b0ea47b71238c1ca99ba09e76e0-b3375cef7a4f18b6a=
53ad4b926aa180e--olfcu-eyJXaG9JZCI6IjAwUTQwMDAwMDFCUExveUVBSCJ9" style=3D"d=
isplay: none;"></font></div>

--001a11360bf869b0ce052ee19ddb--
