Delivered-To: cecy@refreshaustin.org
Received: by 10.27.54.136 with SMTP id d130csp2449984wla;
Tue, 4 Aug 2015 12:53:24 -0700 (PDT)
X-Received: by 10.107.34.147 with SMTP id i141mr5608683ioi.59.1438718003900;
Tue, 04 Aug 2015 12:53:23 -0700 (PDT)
Return-Path: <hey@michaelneal.me>
Received: from mail-io0-f180.google.com (mail-io0-f180.google.com. [209.85.223.180])
by mx.google.com with ESMTPS id m21si433131ioi.11.2015.08.04.12.53.22
for <cecy@refreshaustin.org>
(version=TLSv1.2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Tue, 04 Aug 2015 12:53:23 -0700 (PDT)
Received-SPF: pass (google.com: domain of hey@michaelneal.me designates 209.85.223.180 as permitted sender) client-ip=209.85.223.180;
Authentication-Results: mx.google.com;
spf=pass (google.com: domain of hey@michaelneal.me designates 209.85.223.180 as permitted sender) smtp.mail=hey@michaelneal.me
Received: by ioeg141 with SMTP id g141so28154861ioe.3
for <cecy@refreshaustin.org>; Tue, 04 Aug 2015 12:53:22 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:date:message-id:subject:from:to
:content-type;
bh=1Dchf5op2KBGM1MQJOv3MR4dcGH3PAGOwvvCqw0bTrM=;
b=m3Yt2SvdDjBB++PltptxUmG9p3lM7lEsoQeNE7RfI3aP2Cm5sN4WiGrwo9hyJvx4HG
NAaE+Ycda/1sURMZfz9EwTiY8jBy+6/DdVYrMKuay0GKbkJHksXrK7N9ExgCrIA1eMJq
R0CVbWEYAcoMtQ0YRfyzw4ZTD4XHej7oCNvirIrnfi0bKHBVTG6Vrx/lZNht/on5tqcC
9T8GmBqw9uHbx1gf+ySmEZWrB+SIV5DGrTAuD5JrJlN0Ydds4xJgnrOcYUGzMCd/MI/1
ZbnhSN2AYZu6rur5enJ1oFgxku5qzOOsMMokkoe+SIoEJ9FMXfaAjjmPABk47dD0yuHB
VAlQ==
X-Gm-Message-State: ALoCoQkVfPYNS6rR27aDdvcD/mfhlCVuzvZ2f9I03ugL6WgHQYmwANL4n3ZFIzjMxfgJ59e3JWZD
MIME-Version: 1.0
X-Received: by 10.107.14.10 with SMTP id 10mr5577337ioo.45.1438718002749; Tue,
04 Aug 2015 12:53:22 -0700 (PDT)
Received: by 10.64.148.229 with HTTP; Tue, 4 Aug 2015 12:53:22 -0700 (PDT)
X-Originating-IP: [70.114.200.116]
Date: Tue, 4 Aug 2015 14:53:22 -0500
Message-ID: <CAAqtsd1HJK_xWQf4LbNUORyk8PSyR4b+i5-dUtqJLet_evQgFg@mail.gmail.com>
Subject: Re: Lightning Talk for Next Refresh
From: Michael Neal <hey@michaelneal.me>
To: cecy@refreshaustin.org
Content-Type: multipart/alternative; boundary=001a113ff0ae7c9e8b051c81a387

--001a113ff0ae7c9e8b051c81a387
Content-Type: text/plain; charset=UTF-8

Hey Cecy,

My name is Michael and I am a developer in Austin. I would like to give a
lightning talk that I have an idea for. The talk would be Copyrighting with
Git. In the talk I would show some live Git examples and working with
branch magic to show how Git can help with writing effective copy. I could
keep the talk 10-15 minutes or maybe 20 if needed. That's it for now.
Please let me know what you think!

-Michael

--




//\\//\\  //\\//\\  //\\//\\  //\\//\\
Michael Neal
michaelneal.me
hey@michaelneal.me
512-993-0327

twitter.com/michaelnhacker
linkedin.com/in/michaelnhacker
github.com/michaelnhacker

--001a113ff0ae7c9e8b051c81a387
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr"><div>Hey Cecy,<br><br>My name is Michael and I am a develo=
per in Austin. I would like to give a lightning talk that I have an idea fo=
r. The talk would be Copyrighting with Git. In the talk I would show some l=
ive Git examples and working with branch magic to show how Git can help wit=
h writing effective copy. I could keep the talk 10-15 minutes or maybe 20 i=
f needed. That&#39;s it for now. Please let me know what you think!<br><br>=
</div>-Michael<br clear=3D"all"><div><br>-- <br><div class=3D"gmail_signatu=
re"><div dir=3D"ltr"><div class=3D"gmail_signature"><div dir=3D"ltr"><font =
face=3D"arial, helvetica, sans-serif"><br></font><div><font face=3D"arial, =
helvetica, sans-serif"><br></font></div><div><font face=3D"arial, helvetica=
, sans-serif"><br></font></div><div><font face=3D"arial, helvetica, sans-se=
rif"><br></font></div><div><font face=3D"arial, helvetica, sans-serif">//\\=
//\\ =C2=A0//\\//\\ =C2=A0//\\//\\ =C2=A0//\\//\\</font></div><div><font fa=
ce=3D"arial, helvetica, sans-serif">Michael Neal</font></div><div><font fac=
e=3D"arial, helvetica, sans-serif"><a href=3D"http://michaelneal.me" target=
=3D"_blank">michaelneal.me</a></font></div><div><font face=3D"arial, helvet=
ica, sans-serif"><a href=3D"mailto:hey@michaelneal.me" target=3D"_blank">he=
y@michaelneal.me</a></font></div><div><font face=3D"arial, helvetica, sans-=
serif">512-993-0327</font></div><div><font face=3D"arial, helvetica, sans-s=
erif"><br></font></div><div><font face=3D"arial, helvetica, sans-serif"><a =
href=3D"http://twitter.com/michaelnhacker" target=3D"_blank">twitter.com/mi=
chaelnhacker</a></font></div><div><font face=3D"arial, helvetica, sans-seri=
f"><a href=3D"http://linkedin.com/in/michaelnhacker" target=3D"_blank">link=
edin.com/in/michaelnhacker</a></font></div><div><font face=3D"arial, helvet=
ica, sans-serif"><a href=3D"http://github.com/michaelnhacker" target=3D"_bl=
ank">github.com/michaelnhacker</a></font></div></div></div></div></div>
</div></div>

--001a113ff0ae7c9e8b051c81a387--
