Delivered-To: cecycorrea@gmail.com
Received: by 10.103.130.70 with SMTP id e67csp1963258vsd;
Tue, 21 Jun 2016 17:34:42 -0700 (PDT)
X-Received: by 10.129.44.193 with SMTP id s184mr15357510yws.183.1466555682600;
Tue, 21 Jun 2016 17:34:42 -0700 (PDT)
Return-Path: <kelly.erickson@devbootcamp.com>
Received: from mail-yw0-x22b.google.com (mail-yw0-x22b.google.com. [2607:f8b0:4002:c05::22b])
by mx.google.com with ESMTPS id l185si22495823ybb.141.2016.06.21.17.34.42
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Tue, 21 Jun 2016 17:34:42 -0700 (PDT)
Received-SPF: pass (google.com: domain of kelly.erickson@devbootcamp.com designates 2607:f8b0:4002:c05::22b as permitted sender) client-ip=2607:f8b0:4002:c05::22b;
Authentication-Results: mx.google.com;
dkim=pass header.i=@devbootcamp-com.20150623.gappssmtp.com;
spf=pass (google.com: domain of kelly.erickson@devbootcamp.com designates 2607:f8b0:4002:c05::22b as permitted sender) smtp.mailfrom=kelly.erickson@devbootcamp.com
Received: by mail-yw0-x22b.google.com with SMTP id b72so28044538ywa.3
for <cecycorrea@gmail.com>; Tue, 21 Jun 2016 17:34:42 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=devbootcamp-com.20150623.gappssmtp.com; s=20150623;
h=mime-version:in-reply-to:references:date:message-id:subject:from:to
:cc;
bh=8UMxj51XhJnV/y3EWitjKcoBUdCKKOz9lSl6AHfN9/8=;
b=YRIxwrbdw337c3unQMl9XNhGRuhhuUGu2Wgf7k21PT9JeY3wH8SvNEeUQrXmaLu5Tl
Xu41AEOxFE1Guv9uhaMVjHWNYuV1DlZzDglT2JdKu03l0wj7NYSOXn0roxmRtV+WvuL2
95Yc0hi4Vs7ycYKesnZ2ydO/fQvTKcs00wrWNECNvcA1qZOXRttiuIEnrF+d2EXDwUcg
X7czds0eDvIzSJoRFZ1uRPeF2xQaChTpgkuEVvAdEin9wWjkz8tmOlvprSJrf7rxIRHS
wWzDXU/QEhUnOOCDsHBuXjtirdh+JxB5I7cDq6BHOovnQuziCmpgOnxyb7/jhXDvA7f/
jg/w==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:in-reply-to:references:date
:message-id:subject:from:to:cc;
bh=8UMxj51XhJnV/y3EWitjKcoBUdCKKOz9lSl6AHfN9/8=;
b=hVaI1GGjNHCkQ2hFeXXeUH//IPqO3w6zBi+WCprgSZlBXmaRhADhcNX0JvVxz2toTL
Fq5QYQR1I4dczd/hdxpy7iWg0/UhA+vftN2fu2p8ppKoOwri75mg4OY0FsbqbstmSfCj
HQqEubyKrZOI3AVLM0uQcHtgAtQEyHjKG7HzgT+fD0D1v+yemdY/Y0efg/s5B4qaEjB0
PR3aBYltaF+pnp8FTDBNke+t4XEIXc/SSU3bDtjojeFIOdGZ9It0OHi4ZkNPEjt5xdzU
iPfSEFcRqsnKvdYfI1a/m49cWB+WEeIa+cdHcN2j7eS7NmltDYN2xRZ7RVJ34T42Muml
r4wA==
X-Gm-Message-State: ALyK8tJf04XUDQtLVipniBbVyZRu1wMid8g1lhR9U4aDLJHGUvnm7f2CF9vpm3XlMGwb4l5mSGR97FEZbhmzocpP
MIME-Version: 1.0
X-Received: by 10.129.160.80 with SMTP id x77mr9662526ywg.180.1466555682120;
Tue, 21 Jun 2016 17:34:42 -0700 (PDT)
Received: by 10.37.108.84 with HTTP; Tue, 21 Jun 2016 17:34:42 -0700 (PDT)
In-Reply-To: <CAK0rhsRM3X_t-0S+JQQt7xQYHuE3CZWdUGssFGjE3Wmn5Qy2-w@mail.gmail.com>
References: <A6DD04BA-DEEB-456F-9DD1-4C11F5E40A5A@devbootcamp.com>
<CAL4Zj+KCa6a7xb8MnUP94A8O_zCcyY-u+w6_mFj2Z3Eu5ECzAw@mail.gmail.com>
<CAL4Zj++WtM0KRHVPQJhipyLJg4yacqRuzv3Gdp-qao-0P0V2bA@mail.gmail.com>
<CAK0rhsRM3X_t-0S+JQQt7xQYHuE3CZWdUGssFGjE3Wmn5Qy2-w@mail.gmail.com>
Date: Tue, 21 Jun 2016 19:34:42 -0500
Message-ID: <CACZRmv_U=tcU6EqSAPms7Z5nsfjsi5MZuFrurAtbtDJ-fGN85g@mail.gmail.com>
Subject: Re: Sponsorship for July
From: Kelly Erickson <kelly.erickson@devbootcamp.com>
To: Britt Ballard <britt@thoughtbot.com>
Cc: Cecy Correa <cecycorrea@gmail.com>
Content-Type: multipart/alternative; boundary=94eb2c07d5ac7a13230535d31ac5

--94eb2c07d5ac7a13230535d31ac5
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hi Ladies,

We can still host, July 28th 6:30-9PM.
I am however, already out of budget for food! Do you think you could bring
in a food sponsor?  Sorry about that.

Thanks,
Kelly


On Tue, Jun 21, 2016 at 2:18 PM, Britt Ballard <britt@thoughtbot.com> wrote=
:

> That you Cecy!
>
> Hey Kelly,
>
> I apologize, I dropped the ball on this. Let me know if you need any
> additional information from us and I'll take care of it.
>
> Thank you for your interest in helping us out!
>
> Cheers,
> Britt
>
> On Tue, Jun 21, 2016 at 2:17 PM, Cecy Correa <cecycorrea@gmail.com> wrote=
:
>
>> Kelly,
>>
>> Very sorry for the delay in this.
>>
>> If Dev Bootcamp is still interested in helping out with Austin on Rails,
>> we're looking for a space to host our July meeting, as Capital Factory i=
s
>> unavailable that day.
>>
>> The day would be July 26, and the time is 6:30pm - 9:00pm.
>>
>> Turnout is typically ~50 people. All we need is wifi and a projector /
>> screen where to hook up presenter laptops.
>>
>> Let me know if you think Dev Bootcamp could host us. :)
>>
>> Best,
>>
>> *@cecycorrea*
>>
>> On Wed, May 25, 2016 at 4:44 PM, Cecy Correa <cecycorrea@gmail.com>
>> wrote:
>>
>>> Hi Kelly!
>>>
>>> That is amazing! We are actually looking for a space for July!
>>>
>>> I am cc'ing Britt here who is organizing the July meetup for Austin on
>>> Rails.
>>>
>>> Britt =E2=80=94 Kelly works at Dev Bootcamp, and they are interested in
>>> sponsoring July and providing space.
>>>
>>> Best,
>>>
>>> *@cecycorrea*
>>>
>>> On Wed, May 25, 2016 at 2:28 PM, Kelly Erickson <
>>> kelly.erickson@devbootcamp.com> wrote:
>>>
>>>> Hi Cecy,
>>>>
>>>> Hope your week is going well! What's the need for July? Also, we're
>>>> open to hosting Austin on Rails in our space.
>>>>
>>>> Let's put something on the calendar!!!
>>>>
>>>> Thanks,
>>>>
>>>> Kelly
>>>>
>>>> Kelly Erickson
>>>> C. (401) 369-0887
>>>> Sent from my iPhone
>>>>
>>>>
>>>
>>
>
>
> --
> Britt Ballard / thoughtbot Austin
> 979.575.5007
>



--=20
Kelly Erickson
*Community Marketing Manager | Austin*

@devbootcamp
devbootcamp.com
Sign up for our newsletter <http://eepurl.com/AgphT>

--94eb2c07d5ac7a13230535d31ac5
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hi Ladies,<div><br></div><div>We can still host, July 28th=
6:30-9PM.=C2=A0</div><div>I am however, already out of budget for food! Do=
you think you could bring in a food sponsor?=C2=A0 Sorry about that. =C2=
=A0</div><div><br></div><div>Thanks,</div><div>Kelly</div><div><br></div></=
div><div class=3D"gmail_extra"><br><div class=3D"gmail_quote">On Tue, Jun 2=
1, 2016 at 2:18 PM, Britt Ballard <span dir=3D"ltr">&lt;<a href=3D"mailto:b=
ritt@thoughtbot.com" target=3D"_blank">britt@thoughtbot.com</a>&gt;</span> =
wrote:<br><blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;bord=
er-left:1px #ccc solid;padding-left:1ex"><div dir=3D"ltr">That you Cecy!<di=
v><br></div><div>Hey Kelly,</div><div><br></div><div>I apologize, I dropped=
the ball on this. Let me know if you need any additional information from =
us and I&#39;ll take care of it.</div><div><br></div><div>Thank you for you=
r interest in helping us out!</div><div><br></div><div>Cheers,</div><div>Br=
itt</div></div><div class=3D"gmail_extra"><div><div class=3D"h5"><br><div c=
lass=3D"gmail_quote">On Tue, Jun 21, 2016 at 2:17 PM, Cecy Correa <span dir=
=3D"ltr">&lt;<a href=3D"mailto:cecycorrea@gmail.com" target=3D"_blank">cecy=
correa@gmail.com</a>&gt;</span> wrote:<br><blockquote class=3D"gmail_quote"=
style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-left:1ex"><d=
iv dir=3D"ltr">Kelly,<div><br></div><div>Very sorry for the delay in this.<=
/div><div><br></div><div>If Dev Bootcamp is still interested in helping out=
with Austin on Rails, we&#39;re looking for a space to host our July meeti=
ng, as Capital Factory is unavailable that day.</div><div><br></div><div>Th=
e day would be July 26, and the time is 6:30pm - 9:00pm.=C2=A0</div><div><b=
r></div><div>Turnout is typically ~50 people. All we need is wifi and a pro=
jector / screen where to hook up presenter laptops.</div><div><br></div><di=
v>Let me know if you think Dev Bootcamp could host us. :)</div><div><br></d=
iv><div>Best,</div></div><div class=3D"gmail_extra"><br clear=3D"all"><div>=
<div data-smartmail=3D"gmail_signature"><div dir=3D"ltr"><b>@cecycorrea</b>=
</div></div></div><div><div>
<br><div class=3D"gmail_quote">On Wed, May 25, 2016 at 4:44 PM, Cecy Correa=
<span dir=3D"ltr">&lt;<a href=3D"mailto:cecycorrea@gmail.com" target=3D"_b=
lank">cecycorrea@gmail.com</a>&gt;</span> wrote:<br><blockquote class=3D"gm=
ail_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-le=
ft:1ex"><div dir=3D"ltr">Hi Kelly!<div><br></div><div>That is amazing! We a=
re actually looking for a space for July!</div><div><br></div><div>I am cc&=
#39;ing Britt here who is organizing the July meetup for Austin on Rails.</=
div><div><br></div><div>Britt =E2=80=94 Kelly works at Dev Bootcamp, and th=
ey are interested in sponsoring July and providing space.</div><div><br></d=
iv><div>Best,</div></div><div class=3D"gmail_extra"><br clear=3D"all"><div>=
<div><div dir=3D"ltr"><b>@cecycorrea</b></div></div></div><div><div>
<br><div class=3D"gmail_quote">On Wed, May 25, 2016 at 2:28 PM, Kelly Erick=
son <span dir=3D"ltr">&lt;<a href=3D"mailto:kelly.erickson@devbootcamp.com"=
target=3D"_blank">kelly.erickson@devbootcamp.com</a>&gt;</span> wrote:<br>=
<blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left:1p=
x #ccc solid;padding-left:1ex">Hi Cecy,<br>
<br>
Hope your week is going well! What&#39;s the need for July? Also, we&#39;re=
open to hosting Austin on Rails in our space.<br>
<br>
Let&#39;s put something on the calendar!!!<br>
<br>
Thanks,<br>
<br>
Kelly<br>
<span><font color=3D"#888888"><br>
Kelly Erickson<br>
C. <a href=3D"tel:%28401%29%20369-0887" value=3D"+14013690887" target=3D"_b=
lank">(401) 369-0887</a><br>
Sent from my iPhone<br>
<br>
</font></span></blockquote></div><br></div></div></div>
</blockquote></div><br></div></div></div>
</blockquote></div><br><br clear=3D"all"><div><br></div></div></div><span c=
lass=3D"HOEnZb"><font color=3D"#888888">-- <br><div data-smartmail=3D"gmail=
_signature"><div dir=3D"ltr">Britt Ballard / thoughtbot Austin<div><a href=
=3D"tel:979.575.5007" value=3D"+19795755007" target=3D"_blank">979.575.5007=
</a><br></div></div></div>
</font></span></div>
</blockquote></div><br><br clear=3D"all"><div><br></div>-- <br><div class=
=3D"gmail_signature" data-smartmail=3D"gmail_signature"><div dir=3D"ltr"><d=
iv><div dir=3D"ltr"><div dir=3D"ltr"><div style=3D"color:rgb(136,136,136);f=
ont-size:12.8px"><font color=3D"#666666">Kelly Erickson</font></div><div st=
yle=3D"color:rgb(136,136,136);font-size:12.8px"><b><font color=3D"#666666">=
Community Marketing Manager | Austin</font></b></div><div style=3D"color:rg=
b(136,136,136);font-size:12.8px"><b><font color=3D"#666666"><br></font></b>=
</div><div style=3D"color:rgb(136,136,136)"><div><font color=3D"#666666" si=
ze=3D"2">@devbootcamp</font></div><div><a href=3D"http://devbootcamp.com/" =
style=3D"color:rgb(17,85,204)" target=3D"_blank"><font size=3D"2" color=3D"=
#666666">devbootcamp.com</font></a></div><div><font size=3D"2" color=3D"#66=
6666">Sign up for our=C2=A0<a href=3D"http://eepurl.com/AgphT" style=3D"col=
or:rgb(17,85,204)" target=3D"_blank">newsletter</a></font></div></div></div=
></div></div></div></div>
</div>

--94eb2c07d5ac7a13230535d31ac5--
