Delivered-To: cecycorrea@gmail.com
Received: by 10.176.5.194 with SMTP id e60csp3777758uae;
Fri, 20 May 2016 06:17:52 -0700 (PDT)
X-Received: by 10.157.61.161 with SMTP id l30mr2052782otc.183.1463750271989;
Fri, 20 May 2016 06:17:51 -0700 (PDT)
Return-Path: <reginald.davis88@gmail.com>
Received: from mail-oi0-x22f.google.com (mail-oi0-x22f.google.com. [2607:f8b0:4003:c06::22f])
by mx.google.com with ESMTPS id t7si9966527oev.51.2016.05.20.06.17.51
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Fri, 20 May 2016 06:17:51 -0700 (PDT)
Received-SPF: pass (google.com: domain of reginald.davis88@gmail.com designates 2607:f8b0:4003:c06::22f as permitted sender) client-ip=2607:f8b0:4003:c06::22f;
Authentication-Results: mx.google.com;
dkim=pass header.i=@gmail.com;
spf=pass (google.com: domain of reginald.davis88@gmail.com designates 2607:f8b0:4003:c06::22f as permitted sender) smtp.mailfrom=reginald.davis88@gmail.com;
dmarc=pass (p=NONE dis=NONE) header.from=gmail.com
Received: by mail-oi0-x22f.google.com with SMTP id x201so177459762oif.3
for <cecycorrea@gmail.com>; Fri, 20 May 2016 06:17:51 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=gmail.com; s=20120113;
h=mime-version:date:message-id:subject:from:to;
bh=tKoJvx8emUR7M4R/uGqdm8HmXyVhLjSNqCTStdTNS0A=;
b=UpGcRhxJhBSSsubwlDFqXEJQLtyNfNcAKcuFyzkyEXJQiwIa5B09K2UMJgPASp3N5J
uHyXyhmRmyRL9q6+nu0m28sxBuQ+Gh2I7p35z3rBbMYKEIrI1JuvB3F/0aHghhIZDEVM
kzp2jh52TLiKT73ORhJ44HxbvI2kJOc3qUjYqMQjq5pNLImkG8tPrLz/vrfc+4XCApVY
9wMUddXD0sOp8oTgsO3y0LDVVzLYTNzXuIw3WU8IiZNNzvHggJREUg2a5fhwUVcqoOTo
iJUztIzJ6YapK8KH6aP6owklkge1p7AH23sIxtEKqb3yOtWHNcNsrXVWf2pO9vVaiyp/
Nvcg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:date:message-id:subject:from:to;
bh=tKoJvx8emUR7M4R/uGqdm8HmXyVhLjSNqCTStdTNS0A=;
b=GDYu7DnEvtIw3KuGetayo4n+Ek9BxcU5N/YEO5ayP4HXSl9/GNYwVOne9vq1Wgp5HL
vu1mJaLuI5u3Gx1OxtssyxlK/ep9WsOrrIDWx4pJZIWUQ8fSmCZJW8G06J+4DhI75rDs
311KWpeTeCNwC3YMjRxWh5IKJW5/CBLAI+mhxJE1SxgkkU/l4RCl1gK44N/BEC68Mk9a
9H5NYMWCvbzb1ujb9CAMdzIj9eIfBmjeyFj9c9EKVdGRFuVcLhkqM4mUsXo1jElFMN4d
LyeBQUvxRchHzReuL8f1C3qYu/zrp2hn+wdNyZjZcG3xj0Y2pxFUcwd76m7bWVovysTx
xvhg==
X-Gm-Message-State: AOPr4FUpzIvDhX8ZrzIByEciJx9evm5CAPjHeKrUghtMTZk3wb7yqSQTSeqwk49KCE5sYMN3STChNzo1rkX2Cg==
MIME-Version: 1.0
X-Received: by 10.202.108.144 with SMTP id h138mr2017196oic.2.1463750271567;
Fri, 20 May 2016 06:17:51 -0700 (PDT)
Received: by 10.202.73.141 with HTTP; Fri, 20 May 2016 06:17:51 -0700 (PDT)
Date: Fri, 20 May 2016 08:17:51 -0500
Message-ID: <CA+LAQu57ZZ8pAOnA+RPZ6j_TAtTKE_DeVUgXupak9Cw2gj=-hQ@mail.gmail.com>
Subject: Reggie from RailsConf
From: Reginald Davis <reginald.davis88@gmail.com>
To: cecycorrea@gmail.com
Content-Type: multipart/alternative; boundary=001a1142e940fa1a28053345ea75

--001a1142e940fa1a28053345ea75
Content-Type: text/plain; charset=UTF-8

Cecy,

I hope you've been having a good week!  I just wanted to let you know that
I think your talk on API's was great and I enjoyed your insight on the
challenges of being a new dev you spoke about when I met you in the exhibit
hall.

Plus, I wanted to tell you that I like you website, especially the tools
section.  You have some pretty good stuff on there and I wanted to
compliment you on that section specifically because I think it's a great
resource for new devs!

If you're at OSCON I hope you learn a lot, if not, I hope you have a great
weekend regardless.  And if you ever need anything, have any questions, or
just want to nerd out over some code don't hesitate to shoot me an e-mail!

Thanks,

Reggie
GitHub: Madblkman
Twitter: @Madblkman

--001a1142e940fa1a28053345ea75
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Cecy,=C2=A0<div><br></div><div>I hope you&#39;ve been havi=
ng a good week!=C2=A0 I just wanted to let you know that I think your talk =
on API&#39;s was great and I enjoyed your insight on the challenges of bein=
g a new dev you spoke about when I met you in the exhibit hall.</div><div><=
br></div><div>Plus, I wanted to tell you that I like you website, especiall=
y the tools section.=C2=A0 You have some pretty good stuff on there and I w=
anted to compliment you on that section specifically because I think it&#39=
;s a great resource for new devs!</div><div><br></div><div>If you&#39;re at=
OSCON I hope you learn a lot, if not, I hope you have a great weekend rega=
rdless.=C2=A0 And if you ever need anything, have any questions, or just wa=
nt to nerd out over some code don&#39;t hesitate to shoot me an e-mail!</di=
v><div><br></div><div>Thanks,=C2=A0</div><div><br></div><div>Reggie</div><d=
iv>GitHub: Madblkman</div><div>Twitter: @Madblkman</div></div>

--001a1142e940fa1a28053345ea75--
