Delivered-To: cecycorrea@gmail.com
Received: by 10.182.97.36 with SMTP id dx4csp54614obb;
Thu, 14 Jul 2016 07:03:55 -0700 (PDT)
X-Received: by 10.202.8.210 with SMTP id 201mr5077737oii.107.1468505035593;
Thu, 14 Jul 2016 07:03:55 -0700 (PDT)
Return-Path: <dan@driverdan.com>
Received: from mail-oi0-x229.google.com (mail-oi0-x229.google.com. [2607:f8b0:4003:c06::229])
by mx.google.com with ESMTPS id l15si2957904otl.103.2016.07.14.07.03.55
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Thu, 14 Jul 2016 07:03:55 -0700 (PDT)
Received-SPF: pass (google.com: domain of dan@driverdan.com designates 2607:f8b0:4003:c06::229 as permitted sender) client-ip=2607:f8b0:4003:c06::229;
Authentication-Results: mx.google.com;
dkim=pass header.i=@driverdan.com;
spf=pass (google.com: domain of dan@driverdan.com designates 2607:f8b0:4003:c06::229 as permitted sender) smtp.mailfrom=dan@driverdan.com
Received: by mail-oi0-x229.google.com with SMTP id w18so117590944oiw.3
for <cecycorrea@gmail.com>; Thu, 14 Jul 2016 07:03:55 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=driverdan.com; s=google;
h=mime-version:from:date:message-id:subject:to;
bh=62p/dV7Ewp7MVAgBu8IkOpUdITMtRbdhU2UHn+PlZy8=;
b=MMfGDxce4zPX3vC9tUyvF1thEmvt7prFrmqQNHMTP6JV66mQnkJVxYNKZutXyoO9xE
E3xupE1GmTa/U0/3AqPSA7wWV9MrcSLyTo+Oh+HTLGI9v5KDF9r5Ilhgmxb6pRbRKJYL
ewdxGZXRe/A9a2/dMdU3lXk2zZx3ogWNjpDn0=
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
bh=62p/dV7Ewp7MVAgBu8IkOpUdITMtRbdhU2UHn+PlZy8=;
b=iWiqGcUoD5RWAzQUMqFw054fGw0wuukl5JKOR0q45dVYTUY12egawxWImmBXgAgctY
p6dyB6Pdl3x720o8r+YLlyi/aGTTLgyxv8H3DzAMcQsCd6HHHGqWY52RkLfjjKrYGscR
0sG0J9PzBgNC0S6UeRzro7i6vRiwSteT0WpzrZIwPj5umdacnuOrbZmQHY7QwmfDyxn9
cmr3c6CBQliaf2Wia/zmtrrxCkUFLOu1MAUIe54UTbmEUYn4zQHR1589gP28ueLTOmlh
kHf4LMO2kMiI4ARaNsjO/vUAbamf6MMl/7Z7zO78gDnwvJ8g7pMK2FNehtONve8gVihr
wYCA==
X-Gm-Message-State: ALyK8tIkrITcB7xthy0Z+ucvINU93bN9nH5JWSNDXv1JB+FKd9f1gBcxkVdCrssG6B3nPh9ycmcaYQvShY7/eQ==
X-Received: by 10.202.88.68 with SMTP id m65mr5254399oib.79.1468505034947;
Thu, 14 Jul 2016 07:03:54 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.157.21.112 with HTTP; Thu, 14 Jul 2016 07:03:54 -0700 (PDT)
X-Originating-IP: [67.79.8.126]
From: Dan DeFelippi <dan@driverdan.com>
Date: Thu, 14 Jul 2016 09:03:54 -0500
Message-ID: <CA+vo8J6FGG158ze36jsNWNMH+ssyfUf3d9bpxzwNEYRF3O9oaw@mail.gmail.com>
Subject: Potential speaker for future Refresh
To: Cecy Correa <cecycorrea@gmail.com>, Scott Hudson <scott.w.hudson@gmail.com>
Content-Type: multipart/alternative; boundary=001a113d5d32f59f37053798f86c

--001a113d5d32f59f37053798f86c
Content-Type: text/plain; charset=UTF-8

Hi Cecy,

Scott Hudson <http://scottwhudson.com/> expressed interest in giving a talk
at a future Refresh if you need speakers. As his former coworker and boss I
can vouch for his ability to talk in front of groups. I'm sure he has some
interesting things he could speak about.

--
Dan DeFelippi
+1.585.466.4747
http://driverdan.com
Follow me on Twitter at @ExpertDan <http://twitter.com/ExpertDan>

--001a113d5d32f59f37053798f86c
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hi Cecy,<div><br></div><div><a href=3D"http://scottwhudson=
.com/">Scott Hudson</a> expressed interest in giving a talk at a future Ref=
resh if you need speakers. As his former coworker and boss I can vouch for =
his ability to talk in front of groups. I&#39;m sure he has some interestin=
g things he could speak about.</div><div><br clear=3D"all"><div><div class=
=3D"gmail_signature" data-smartmail=3D"gmail_signature"><div>--</div><span =
style=3D"font-size:x-small">Dan DeFelippi<br>+1.585.466.4747<br></span><a h=
ref=3D"http://driverdan.com/" target=3D"_blank"><span style=3D"font-size:x-=
small">http://driverdan.com</span></a><span style=3D"font-size:x-small"><br=
>Follow me on Twitter at=C2=A0</span><a href=3D"http://twitter.com/ExpertDa=
n" target=3D"_blank"><span style=3D"font-size:x-small">@ExpertDan</span></a=
><br></div></div>
</div></div>

--001a113d5d32f59f37053798f86c--
