Delivered-To: cecycorrea@gmail.com
Received: by 10.176.5.194 with SMTP id e60csp1747439uae;
Mon, 16 May 2016 15:44:02 -0700 (PDT)
X-Received: by 10.202.78.210 with SMTP id c201mr18853231oib.87.1463438642382;
Mon, 16 May 2016 15:44:02 -0700 (PDT)
Return-Path: <katetrumpower@capitalfactory.com>
Received: from mail-oi0-x232.google.com (mail-oi0-x232.google.com. [2607:f8b0:4003:c06::232])
by mx.google.com with ESMTPS id 74si12280261otu.168.2016.05.16.15.44.02
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Mon, 16 May 2016 15:44:02 -0700 (PDT)
Received-SPF: neutral (google.com: 2607:f8b0:4003:c06::232 is neither permitted nor denied by best guess record for domain of katetrumpower@capitalfactory.com) client-ip=2607:f8b0:4003:c06::232;
Authentication-Results: mx.google.com;
dkim=pass header.i=@capitalfactory-com.20150623.gappssmtp.com;
spf=neutral (google.com: 2607:f8b0:4003:c06::232 is neither permitted nor denied by best guess record for domain of katetrumpower@capitalfactory.com) smtp.mailfrom=katetrumpower@capitalfactory.com
Received: by mail-oi0-x232.google.com with SMTP id x19so288266734oix.2
for <cecycorrea@gmail.com>; Mon, 16 May 2016 15:44:02 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=capitalfactory-com.20150623.gappssmtp.com; s=20150623;
h=mime-version:in-reply-to:references:from:date:message-id:subject:to;
bh=v6yDY3h7Qr8QobXShP1ouStZMSopB1vgTTR1JgiCmiI=;
b=Sc2BcDf3lRbv4qOT56+82TS02nuGtol01pM0vMFVX3mzCoJAJLKrohnPmWkQqp2QBw
Lrrm2qADjqftpWyAS5sa6KOL4Ue10NYE2XjOi1DOrXihaS5OM/73ExmtcR3qwirtssgv
9dwI6wvLqfP7jF8iMR15nQI3jlLVa9dvhWJVIoGvcpKE+/vYIuCYl1/SEbdSxpHbTDpw
LnicbPQme5NZMpbThw/Ki4mGlshefgm1xNP28pNmnaM37xdkYjzuDtmtiCxBSoddnyjy
il6mziPwzDNmEo5W8SwtDPpqn3xszFQeYiZ4KwegGXE0wsQprkl4dFjrLO/Zgvb9ZUTO
RvCA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:in-reply-to:references:from:date
:message-id:subject:to;
bh=v6yDY3h7Qr8QobXShP1ouStZMSopB1vgTTR1JgiCmiI=;
b=mLV6Y07sHLjcfrZWOu8vNWCdBOrrG4nK1PaBlpTvXiG0NZBInXKXEzERewVjaPo/q3
DYRBZS4tC2vlDNi/9A6goUXXb53Hmo6qfIu4JL+zfceCusg0drYQ7K5n+ZXtYtMrwIcX
Lb7QCiEeIVdip9YJNo648elynmo7a7Uf3SPwBDIh817jTbNz7lXARCiMjnn+Guh370EP
RvYDZZgYWTPNw49Eek81rIjy/lGnekygC3WflvnrTOgEFOqbBFDnjLLV2/sa/pZvXPi5
iuWjOkr+eqUj6qOqLCY1zNJhQUbjzxGxnqalz3cfo+UO+uFTd+mAxGv1kreVZSb2pzza
si3A==
X-Gm-Message-State: AOPr4FVDs1DJ9vHCUEfDF5ENvnInPrJQjfUYJwM4LYIKLeD8TESdnRe/9VgK0baQCmo0RlU2wmilK8jmHI3JZw==
X-Received: by 10.157.15.185 with SMTP id d54mr19625327otd.15.1463438642025;
Mon, 16 May 2016 15:44:02 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.202.245.151 with HTTP; Mon, 16 May 2016 15:43:32 -0700 (PDT)
In-Reply-To: <CAL4Zj++F2At-nky_rw6Noi8w5r=1QZjLmX5UneHLexLbhdkQ=A@mail.gmail.com>
References: <CANKKpHZPiXgoqajQMzvozD0V-wiJU9F6eF5P2dbvXLgq_SZ4GA@mail.gmail.com>
<CAOTHSAgeNtnMevEUh11XwKjP0A74rPHa1OF-hY0+0KOTgN1KyA@mail.gmail.com>
<CANKKpHYNrmehutoQEL8iSXc7K5g9Si23Yyba45fkgVJNCRLgVA@mail.gmail.com>
<CANKKpHaDP5XEzvH56s+XuHd74BdO2kdS_tuZKksn5Z7wqaRdqQ@mail.gmail.com>
<CAOTHSAjemvkZGmJdsR7Bqe6F2Rz9Pmic+-Dh56B8RQdEBdwJSg@mail.gmail.com> <CAL4Zj++F2At-nky_rw6Noi8w5r=1QZjLmX5UneHLexLbhdkQ=A@mail.gmail.com>
From: Kate Trumpower <katetrumpower@capitalfactory.com>
Date: Mon, 16 May 2016 17:43:32 -0500
Message-ID: <CANKKpHZCJER0AxUqDeXXsqvjLF6VssnWt4sy1yvEVFR9A=1WbA@mail.gmail.com>
Subject: Re: Austin On Rails | July 26th
To: Cecy Correa <cecycorrea@gmail.com>
Content-Type: multipart/alternative; boundary=001a113cdaac68acc50532fd5cbb

--001a113cdaac68acc50532fd5cbb
Content-Type: text/plain; charset=UTF-8

Hi Cecy,

I totally understand, and I'm sorry it didn't work out this time around. I
will take you off for July but keep you on for the other months.

Thanks!

*Kate Trumpower*
Events & Marketing Coordinator | Capital Factory
701 Brazos Street, Suite 1600 Austin, TX 78701
w: capitalfactory.com | p: 512-842-7159
<http://www.facebook.com/capitalfactory>
<http://twitter.com/CFStartupEvents>
<http://www.linkedin.com/in/katetrumpower>


NewCoATX 2016 is on July 27th! Deadline to sign up
<http://atx.newco.co/apply/> as a HostCo is May 18th. What's NewCo?
<https://www.youtube.com/watch?v=u97871TeV-o>
Interested in learning about sponsorship? Email
Partnerships@capitalfactory.com

On Mon, May 16, 2016 at 5:21 PM, Cecy Correa <cecycorrea@gmail.com> wrote:

> Thanks for the head's up Damon, moving to you bcc.
>
> Kate, we would prefer not to move dates, as the community expects Austin
> on Rails to be on the 4th Tuesday of the month, and it is hard to move
> dates without conflicting with another meetup. We will find another place
> for July, but please do keep us on the same date for other months when
> possible.
>
> Thanks so much,
>
> *@cecycorrea*
>
> On Mon, May 16, 2016 at 5:15 PM, Damon Clinkscales <scales@pobox.com>
> wrote:
>
>> Kate,
>>
>> I only heard that they do not want to switch dates.
>>
>> I am CC-ing Cecy who may have more details about what AoR will do.
>>
>> Best,
>> /damon
>>
>> On Mon, May 16, 2016 at 4:42 PM, Kate Trumpower <
>> katetrumpower@capitalfactory.com> wrote:
>>
>>> Hi Damon,
>>>
>>> I hope this message reaches you well. I'm writing to follow up on this
>>> thread. Have you heard back from the council about switching dates?
>>>
>>> Thanks!
>>>
>>> *Kate Trumpower*
>>> Events & Marketing Coordinator | Capital Factory
>>> 701 Brazos Street, Suite 1600 Austin, TX 78701
>>> w: capitalfactory.com | p: 512-842-7159
>>> <http://www.facebook.com/capitalfactory>
>>> <http://twitter.com/CFStartupEvents>
>>> <http://www.linkedin.com/in/katetrumpower>
>>>
>>>
>>> NewCoATX 2016 is on July 27th! Deadline to sign up
>>> <http://atx.newco.co/apply/> as a HostCo is May 18th. What's NewCo?
>>> <https://www.youtube.com/watch?v=u97871TeV-o>
>>> Interested in learning about sponsorship? Email
>>> Partnerships@capitalfactory.com
>>>
>>> On Tue, Apr 19, 2016 at 10:30 AM, Kate Trumpower <
>>> katetrumpower@capitalfactory.com> wrote:
>>>
>>>> Sounds great. Thank you, Damon!
>>>>
>>>> *Kate Trumpower*
>>>> Events & Marketing Coordinator | Capital Factory
>>>> 701 Brazos Street, Suite 1600 Austin, TX 78701
>>>> w: capitalfactory.com | p: 512-842-7159
>>>> <http://www.facebook.com/capitalfactory>
>>>> <http://twitter.com/CFStartupEvents>
>>>> <http://www.linkedin.com/in/katetrumpower>
>>>>
>>>>
>>>> NewCoATX 2016 is on July 27th! Deadline to sign up
>>>> <http://atx.newco.co/apply/> as a HostCo is May 18th. What's NewCo?
>>>> <https://www.youtube.com/watch?v=u97871TeV-o>
>>>> Interested in learning about sponsorship? email
>>>> Partnerships@capitalfactory.com
>>>>
>>>> On Tue, Apr 19, 2016 at 10:27 AM, Damon Clinkscales <scales@pobox.com>
>>>> wrote:
>>>>
>>>>> i will forward to the aor council and have someone follow up with you
>>>>>
>>>>> thanks,
>>>>> /damon
>>>>>
>>>>> On Tue, Apr 19, 2016 at 10:22 AM, Kate Trumpower <
>>>>> katetrumpower@capitalfactory.com> wrote:
>>>>>
>>>>>> Hi Damon,
>>>>>>
>>>>>> Thanks again for coming in this afternoon to answer questions about
>>>>>> the Austin Startup Scene! I really appreciate it.
>>>>>>
>>>>>> I'm writing to let you know that we are hosting NewCo on July 26th
>>>>>> and will need to move your meetup. Below are other available dates in July.
>>>>>>
>>>>>> July 14th
>>>>>> July 18th
>>>>>> July 20th
>>>>>>
>>>>>> Please let me know if any of those dates work for you. Also, if you'd
>>>>>> like to get involved with NewCo you can apply to be a HostCo here
>>>>>> <http://atx.newco.co/apply/>.
>>>>>>
>>>>>> Thanks!
>>>>>>
>>>>>> *Kate Trumpower*
>>>>>> Events & Marketing Coordinator | Capital Factory
>>>>>> 701 Brazos Street, Suite 1600 Austin, TX 78701
>>>>>> w: capitalfactory.com | p: 512-842-7159
>>>>>> <http://www.facebook.com/capitalfactory>
>>>>>> <http://twitter.com/CFStartupEvents>
>>>>>> <http://www.linkedin.com/in/katetrumpower>
>>>>>>
>>>>>>
>>>>>> NewCoATX 2016 is on July 27th! Deadline to sign up
>>>>>> <http://atx.newco.co/apply/> as a HostCo is May 18th. What's NewCo?
>>>>>> <https://www.youtube.com/watch?v=u97871TeV-o>
>>>>>> Interested in learning about sponsorship? email
>>>>>> Partnerships@capitalfactory.com
>>>>>>
>>>>>
>>>>>
>>>>>
>>>>> --
>>>>> http://twitter.com/damon
>>>>> http://blog.damonc.com
>>>>>
>>>>
>>>>
>>>
>>
>>
>> --
>> http://twitter.com/damon
>> http://blog.damonc.com
>>
>
>

--001a113cdaac68acc50532fd5cbb
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hi Cecy,<div><br></div><div>I totally understand, and I&#3=
9;m sorry it didn&#39;t work out this time around. I will take you off for =
July but keep you on for the other months.=C2=A0</div><div><br></div><div>T=
hanks!</div></div><div class=3D"gmail_extra"><br clear=3D"all"><div><div cl=
ass=3D"gmail_signature"><div dir=3D"ltr"><div><div dir=3D"ltr"><div><div di=
r=3D"ltr"><div><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=
=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr=
"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div =
dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><font size=
=3D"2"><b>Kate Trumpower</b></font><div><font color=3D"#990000" size=3D"2">=
Events &amp; Marketing Coordinator |=C2=A0Capital Factory</font></div><div =
style=3D"font-size:12.8px"><font color=3D"#666666">701 Brazos Street, Suite=
1600 Austin, TX 78701</font></div><div style=3D"font-size:12.8px"><font co=
lor=3D"#990000" style=3D"font-size:12.8px;background-color:rgb(254,254,254)=
">w:</font><span style=3D"font-size:12.8px">=C2=A0</span><font color=3D"#66=
6666" style=3D"font-size:12.8px;background-color:rgb(254,254,254)"><a href=
=3D"http://capitalfactory.com" target=3D"_blank">capitalfactory.com</a></fo=
nt><span style=3D"font-size:12.8px">=C2=A0</span><span style=3D"font-size:1=
2.8px">|</span><span style=3D"font-size:12.8px">=C2=A0</span><font color=3D=
"#990000" style=3D"font-size:12.8px;background-color:rgb(254,254,254)">p:</=
font><span style=3D"font-size:12.8px">=C2=A0</span><font color=3D"#666666" =
style=3D"font-size:12.8px;background-color:rgb(254,254,254)">512-842-7159</=
font></div><div style=3D"font-size:12.8px"><a href=3D"http://www.facebook.c=
om/capitalfactory" style=3D"font-family:Arial;font-size:14px;outline:none;b=
ackground-color:rgb(254,254,254)" target=3D"_blank"><img width=3D"16" src=
=3D"https://s3.amazonaws.com/images.wisestamp.com/icons_32/facebook.png" st=
yle=3D"border:0px;border-radius:0px;width:16px"></a><span style=3D"color:rg=
b(100,100,100);font-family:Arial;font-size:14px;background-color:rgb(254,25=
4,254)">=C2=A0</span><a href=3D"http://twitter.com/CFStartupEvents" style=
=3D"font-family:Arial;font-size:14px;outline:none;background-color:rgb(254,=
254,254)" target=3D"_blank"><img width=3D"16" src=3D"https://s3.amazonaws.c=
om/images.wisestamp.com/icons_32/twitter.png" style=3D"border:0px;border-ra=
dius:0px;width:16px"></a>=C2=A0<a href=3D"http://www.linkedin.com/in/katetr=
umpower" target=3D"_blank"><img width=3D"16" src=3D"https://s3.amazonaws.co=
m/images.wisestamp.com/icons_32/linkedin.png" style=3D"border-radius:0px;bo=
rder:0px;width:16px"></a></div><div style=3D"font-size:12.8px"><br></div><d=
iv style=3D"font-size:12.8px"><span style=3D"font-size:12.8px"><br>NewCoATX=
2016 is on=C2=A0<span><span>July 27th</span></span>!=C2=A0<font color=3D"#=
ff0000">Deadline to</font>=C2=A0<a href=3D"http://atx.newco.co/apply/" styl=
e=3D"color:rgb(17,85,204)" target=3D"_blank">sign up</a>=C2=A0<font color=
=3D"#ff0000">as a HostCo is=C2=A0<span><span>May 18th</span></span>.</font>=
</span><span style=3D"font-size:12.8px">=C2=A0</span><a href=3D"https://www=
.youtube.com/watch?v=3Du97871TeV-o" style=3D"color:rgb(17,85,204);font-size=
:12.8px" target=3D"_blank">What&#39;s NewCo?</a><div style=3D"font-size:12.=
8px">Interested in learning about sponsorship? Email=C2=A0<a href=3D"mailto=
:Partnerships@capitalfactory.com" style=3D"color:rgb(17,85,204)" target=3D"=
_blank">Partnerships@capitalfactory.com</a></div></div></div></div></div></=
div></div></div></div></div></div></div></div></div></div></div></div></div=
></div></div></div></div></div></div></div></div>
<br><div class=3D"gmail_quote">On Mon, May 16, 2016 at 5:21 PM, Cecy Correa=
<span dir=3D"ltr">&lt;<a href=3D"mailto:cecycorrea@gmail.com" target=3D"_b=
lank">cecycorrea@gmail.com</a>&gt;</span> wrote:<br><blockquote class=3D"gm=
ail_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-le=
ft:1ex"><div dir=3D"ltr">Thanks for the head&#39;s up Damon, moving to you =
bcc.<div><br></div><div>Kate, we would prefer not to move dates, as the com=
munity expects Austin on Rails to be on the 4th Tuesday of the month, and i=
t is hard to move dates without conflicting with another meetup. We will fi=
nd another place for July, but please do keep us on the same date for other=
months when possible.</div><div><br></div><div>Thanks so much,</div></div>=
<div class=3D"gmail_extra"><br clear=3D"all"><div><div><div dir=3D"ltr"><b>=
@cecycorrea</b></div></div></div><div><div class=3D"h5">
<br><div class=3D"gmail_quote">On Mon, May 16, 2016 at 5:15 PM, Damon Clink=
scales <span dir=3D"ltr">&lt;<a href=3D"mailto:scales@pobox.com" target=3D"=
_blank">scales@pobox.com</a>&gt;</span> wrote:<br><blockquote class=3D"gmai=
l_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-left=
:1ex"><div dir=3D"ltr">Kate,<div><br></div><div>I only heard that they do n=
ot want to switch dates.</div><div><br></div><div>I am CC-ing Cecy who may =
have more details about what AoR will do.</div><div><br></div><div>Best,</d=
iv><div>/damon</div></div><div class=3D"gmail_extra"><br><div class=3D"gmai=
l_quote">On Mon, May 16, 2016 at 4:42 PM, Kate Trumpower <span dir=3D"ltr">=
&lt;<a href=3D"mailto:katetrumpower@capitalfactory.com" target=3D"_blank">k=
atetrumpower@capitalfactory.com</a>&gt;</span> wrote:<br><blockquote class=
=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padd=
ing-left:1ex"><div dir=3D"ltr">Hi Damon,<div><br></div><div>I hope this mes=
sage reaches you well. I&#39;m writing to follow up=C2=A0on this thread. Ha=
ve you heard back from the council about switching dates?</div><div><br></d=
iv><div>Thanks!</div></div><div class=3D"gmail_extra"><br clear=3D"all"><di=
v><div><div dir=3D"ltr"><div><div dir=3D"ltr"><div><div dir=3D"ltr"><div><d=
iv dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=
=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr=
"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div =
dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><span><font size=3D"2"><b>Kat=
e Trumpower</b></font><div><font color=3D"#990000" size=3D"2">Events &amp; =
Marketing Coordinator |=C2=A0Capital Factory</font></div><div style=3D"font=
-size:12.8px"><font color=3D"#666666">701 Brazos Street, Suite 1600 Austin,=
TX 78701</font></div><div style=3D"font-size:12.8px"><font color=3D"#99000=
0" style=3D"font-size:12.8px;background-color:rgb(254,254,254)">w:</font><s=
pan style=3D"font-size:12.8px">=C2=A0</span><font color=3D"#666666" style=
=3D"font-size:12.8px;background-color:rgb(254,254,254)"><a href=3D"http://c=
apitalfactory.com" target=3D"_blank">capitalfactory.com</a></font><span sty=
le=3D"font-size:12.8px">=C2=A0</span><span style=3D"font-size:12.8px">|</sp=
an><span style=3D"font-size:12.8px">=C2=A0</span><font color=3D"#990000" st=
yle=3D"font-size:12.8px;background-color:rgb(254,254,254)">p:</font><span s=
tyle=3D"font-size:12.8px">=C2=A0</span><font color=3D"#666666" style=3D"fon=
t-size:12.8px;background-color:rgb(254,254,254)"><a href=3D"tel:512-842-715=
9" value=3D"+15128427159" target=3D"_blank">512-842-7159</a></font></div><d=
iv style=3D"font-size:12.8px"><a href=3D"http://www.facebook.com/capitalfac=
tory" style=3D"font-family:Arial;font-size:14px;outline:none;background-col=
or:rgb(254,254,254)" target=3D"_blank"><img width=3D"16" style=3D"border:0p=
x;border-radius:0px;width:16px"></a><span style=3D"color:rgb(100,100,100);f=
ont-family:Arial;font-size:14px;background-color:rgb(254,254,254)">=C2=A0</=
span><a href=3D"http://twitter.com/CFStartupEvents" style=3D"font-family:Ar=
ial;font-size:14px;outline:none;background-color:rgb(254,254,254)" target=
=3D"_blank"><img width=3D"16" style=3D"border:0px;border-radius:0px;width:1=
6px"></a>=C2=A0<a href=3D"http://www.linkedin.com/in/katetrumpower" target=
=3D"_blank"><img width=3D"16" style=3D"border-radius:0px;border:0px;width:1=
6px"></a></div><div style=3D"font-size:12.8px"><br></div></span><div style=
=3D"font-size:12.8px"><span><span style=3D"font-size:12.8px"><br>NewCoATX 2=
016 is on=C2=A0<span><span>July 27th</span></span>!=C2=A0<font color=3D"#ff=
0000">Deadline to</font>=C2=A0<a href=3D"http://atx.newco.co/apply/" style=
=3D"color:rgb(17,85,204)" target=3D"_blank">sign up</a>=C2=A0<font color=3D=
"#ff0000">as a HostCo is=C2=A0<span><span>May 18th</span></span>.</font></s=
pan><span style=3D"font-size:12.8px">=C2=A0</span><a href=3D"https://www.yo=
utube.com/watch?v=3Du97871TeV-o" style=3D"color:rgb(17,85,204);font-size:12=
.8px" target=3D"_blank">What&#39;s NewCo?</a></span><div style=3D"font-size=
:12.8px">Interested in learning about sponsorship? Email=C2=A0<a href=3D"ma=
ilto:Partnerships@capitalfactory.com" style=3D"color:rgb(17,85,204)" target=
=3D"_blank">Partnerships@capitalfactory.com</a></div></div></div></div></di=
v></div></div></div></div></div></div></div></div></div></div></div></div><=
/div></div></div></div></div></div></div></div></div><div><div>
<br><div class=3D"gmail_quote">On Tue, Apr 19, 2016 at 10:30 AM, Kate Trump=
ower <span dir=3D"ltr">&lt;<a href=3D"mailto:katetrumpower@capitalfactory.c=
om" target=3D"_blank">katetrumpower@capitalfactory.com</a>&gt;</span> wrote=
:<br><blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-le=
ft:1px #ccc solid;padding-left:1ex"><div dir=3D"ltr">Sounds great. Thank yo=
u, Damon!</div><div class=3D"gmail_extra"><span><br clear=3D"all"><div><div=
><div dir=3D"ltr"><div><div dir=3D"ltr"><div><div dir=3D"ltr"><div dir=3D"l=
tr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><di=
v dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=
=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr=
"><div dir=3D"ltr"><font size=3D"2"><b>Kate Trumpower</b></font><div><font =
color=3D"#990000" size=3D"2">Events &amp; Marketing Coordinator |=C2=A0Capi=
tal Factory</font></div><div style=3D"font-size:12.8px"><font color=3D"#666=
666">701 Brazos Street, Suite 1600 Austin, TX 78701</font></div><div style=
=3D"font-size:12.8px"><font color=3D"#990000" style=3D"font-size:12.8px;bac=
kground-color:rgb(254,254,254)">w:</font><span style=3D"font-size:12.8px">=
=C2=A0</span><font color=3D"#666666" style=3D"font-size:12.8px;background-c=
olor:rgb(254,254,254)"><a href=3D"http://capitalfactory.com" target=3D"_bla=
nk">capitalfactory.com</a></font><span style=3D"font-size:12.8px">=C2=A0</s=
pan><span style=3D"font-size:12.8px">|</span><span style=3D"font-size:12.8p=
x">=C2=A0</span><font color=3D"#990000" style=3D"font-size:12.8px;backgroun=
d-color:rgb(254,254,254)">p:</font><span style=3D"font-size:12.8px">=C2=A0<=
/span><font color=3D"#666666" style=3D"font-size:12.8px;background-color:rg=
b(254,254,254)"><a href=3D"tel:512-842-7159" value=3D"+15128427159" target=
=3D"_blank">512-842-7159</a></font></div><div style=3D"font-size:12.8px"><a=
href=3D"http://www.facebook.com/capitalfactory" style=3D"font-family:Arial=
;font-size:14px;outline:none;background-color:rgb(254,254,254)" target=3D"_=
blank"><img width=3D"16" style=3D"border:0px;border-radius:0px;width:16px">=
</a><span style=3D"color:rgb(100,100,100);font-family:Arial;font-size:14px;=
background-color:rgb(254,254,254)">=C2=A0</span><a href=3D"http://twitter.c=
om/CFStartupEvents" style=3D"font-family:Arial;font-size:14px;outline:none;=
background-color:rgb(254,254,254)" target=3D"_blank"><img width=3D"16" styl=
e=3D"border:0px;border-radius:0px;width:16px"></a>=C2=A0<a href=3D"http://w=
ww.linkedin.com/in/katetrumpower" target=3D"_blank"><img width=3D"16" style=
=3D"border-radius:0px;border:0px;width:16px"></a></div><div style=3D"font-s=
ize:12.8px"><br></div><div style=3D"font-size:12.8px"><span style=3D"font-s=
ize:12.8px"><br>NewCoATX 2016 is on=C2=A0<span><span>July 27th</span></span=
>!=C2=A0<font color=3D"#ff0000">Deadline to</font>=C2=A0<a href=3D"http://a=
tx.newco.co/apply/" style=3D"color:rgb(17,85,204)" target=3D"_blank">sign u=
p</a>=C2=A0<font color=3D"#ff0000">as a HostCo is=C2=A0<span><span>May 18th=
</span></span>.</font></span><span style=3D"font-size:12.8px">=C2=A0</span>=
<a href=3D"https://www.youtube.com/watch?v=3Du97871TeV-o" style=3D"color:rg=
b(17,85,204);font-size:12.8px" target=3D"_blank">What&#39;s NewCo?</a><div =
style=3D"font-size:12.8px">Interested in learning about sponsorship? email=
=C2=A0<a href=3D"mailto:Partnerships@capitalfactory.com" style=3D"color:rgb=
(17,85,204)" target=3D"_blank">Partnerships@capitalfactory.com</a></div></d=
iv></div></div></div></div></div></div></div></div></div></div></div></div>=
</div></div></div></div></div></div></div></div></div></div>
<br></span><div><div><div class=3D"gmail_quote">On Tue, Apr 19, 2016 at 10:=
27 AM, Damon Clinkscales <span dir=3D"ltr">&lt;<a href=3D"mailto:scales@pob=
ox.com" target=3D"_blank">scales@pobox.com</a>&gt;</span> wrote:<br><blockq=
uote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc =
solid;padding-left:1ex"><div dir=3D"ltr">i will forward to the aor council =
and have someone follow up with you<div><br></div><div>thanks,</div><div>/d=
amon</div></div><div class=3D"gmail_extra"><div><div><br><div class=3D"gmai=
l_quote">On Tue, Apr 19, 2016 at 10:22 AM, Kate Trumpower <span dir=3D"ltr"=
>&lt;<a href=3D"mailto:katetrumpower@capitalfactory.com" target=3D"_blank">=
katetrumpower@capitalfactory.com</a>&gt;</span> wrote:<br><blockquote class=
=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padd=
ing-left:1ex"><div dir=3D"ltr">Hi Damon,<div><br></div><div>Thanks again fo=
r coming in this afternoon to answer questions about the Austin Startup Sce=
ne! I really appreciate it.</div><div><br></div><div>I&#39;m writing to let=
you know that we are hosting NewCo on July 26th and will need to move your=
meetup. Below are other available dates in July.</div><div><br></div><div>=
July 14th</div><div>July 18th</div><div>July 20th</div><div><br></div><div>=
Please let me know if any of those dates work for you. Also, if you&#39;d l=
ike to get involved with NewCo you can <a href=3D"http://atx.newco.co/apply=
/" target=3D"_blank">apply to be a HostCo here</a>.</div><div><br></div><di=
v>Thanks!</div><div><br clear=3D"all"><div><div><div dir=3D"ltr"><div><div =
dir=3D"ltr"><div><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div di=
r=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"lt=
r"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div=
dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><font size=
=3D"2"><b>Kate Trumpower</b></font><div><font color=3D"#990000" size=3D"2">=
Events &amp; Marketing Coordinator |=C2=A0Capital Factory</font></div><div =
style=3D"font-size:12.8px"><font color=3D"#666666">701 Brazos Street, Suite=
1600 Austin, TX 78701</font></div><div style=3D"font-size:12.8px"><font co=
lor=3D"#990000" style=3D"font-size:12.8px;background-color:rgb(254,254,254)=
">w:</font><span style=3D"font-size:12.8px">=C2=A0</span><font color=3D"#66=
6666" style=3D"font-size:12.8px;background-color:rgb(254,254,254)"><a href=
=3D"http://capitalfactory.com" target=3D"_blank">capitalfactory.com</a></fo=
nt><span style=3D"font-size:12.8px">=C2=A0</span><span style=3D"font-size:1=
2.8px">|</span><span style=3D"font-size:12.8px">=C2=A0</span><font color=3D=
"#990000" style=3D"font-size:12.8px;background-color:rgb(254,254,254)">p:</=
font><span style=3D"font-size:12.8px">=C2=A0</span><font color=3D"#666666" =
style=3D"font-size:12.8px;background-color:rgb(254,254,254)"><a href=3D"tel=
:512-842-7159" value=3D"+15128427159" target=3D"_blank">512-842-7159</a></f=
ont></div><div style=3D"font-size:12.8px"><a href=3D"http://www.facebook.co=
m/capitalfactory" style=3D"font-family:Arial;font-size:14px;outline:none;ba=
ckground-color:rgb(254,254,254)" target=3D"_blank"><img width=3D"16" style=
=3D"border:0px;border-radius:0px;width:16px"></a><span style=3D"color:rgb(1=
00,100,100);font-family:Arial;font-size:14px;background-color:rgb(254,254,2=
54)">=C2=A0</span><a href=3D"http://twitter.com/CFStartupEvents" style=3D"f=
ont-family:Arial;font-size:14px;outline:none;background-color:rgb(254,254,2=
54)" target=3D"_blank"><img width=3D"16" style=3D"border:0px;border-radius:=
0px;width:16px"></a>=C2=A0<a href=3D"http://www.linkedin.com/in/katetrumpow=
er" target=3D"_blank"><img width=3D"16" style=3D"border-radius:0px;border:0=
px;width:16px"></a></div><div style=3D"font-size:12.8px"><br></div><div sty=
le=3D"font-size:12.8px"><span style=3D"font-size:12.8px"><br>NewCoATX 2016 =
is on=C2=A0<span><span>July 27th</span></span>!=C2=A0<font color=3D"#ff0000=
">Deadline to</font>=C2=A0<a href=3D"http://atx.newco.co/apply/" style=3D"c=
olor:rgb(17,85,204)" target=3D"_blank">sign up</a>=C2=A0<font color=3D"#ff0=
000">as a HostCo is=C2=A0<span><span>May 18th</span></span>.</font></span><=
span style=3D"font-size:12.8px">=C2=A0</span><a href=3D"https://www.youtube=
.com/watch?v=3Du97871TeV-o" style=3D"color:rgb(17,85,204);font-size:12.8px"=
target=3D"_blank">What&#39;s NewCo?</a><div style=3D"font-size:12.8px">Int=
erested in learning about sponsorship? email=C2=A0<a href=3D"mailto:Partner=
ships@capitalfactory.com" style=3D"color:rgb(17,85,204)" target=3D"_blank">=
Partnerships@capitalfactory.com</a></div></div></div></div></div></div></di=
v></div></div></div></div></div></div></div></div></div></div></div></div><=
/div></div></div></div></div>
</div></div>
</blockquote></div><br><br clear=3D"all"><span><font color=3D"#888888"><div=
><br></div></font></span></div></div><span><font color=3D"#888888"><span><f=
ont color=3D"#888888">-- <br><div><a href=3D"http://twitter.com/damon" targ=
et=3D"_blank">http://twitter.com/damon</a><br><a href=3D"http://blog.damonc=
.com" target=3D"_blank">http://blog.damonc.com</a></div>
</font></span></font></span></div><span><font color=3D"#888888">
</font></span></blockquote></div><span><font color=3D"#888888"><br></font><=
/span></div></div></div><span><font color=3D"#888888">
</font></span></blockquote></div><span><font color=3D"#888888"><br></font><=
/span></div></div></div><span><font color=3D"#888888">
</font></span></blockquote></div><span><font color=3D"#888888"><br><br clea=
r=3D"all"><div><br></div>-- <br><div><a href=3D"http://twitter.com/damon" t=
arget=3D"_blank">http://twitter.com/damon</a><br><a href=3D"http://blog.dam=
onc.com" target=3D"_blank">http://blog.damonc.com</a></div>
</font></span></div>
</blockquote></div><br></div></div></div>
</blockquote></div><br></div>

--001a113cdaac68acc50532fd5cbb--
