Delivered-To: cecycorrea@gmail.com
Received: by 10.182.22.138 with SMTP id d10csp76800obf;
Wed, 20 Jul 2016 16:18:32 -0700 (PDT)
X-Received: by 10.31.65.85 with SMTP id o82mr24441839vka.12.1469056712246;
Wed, 20 Jul 2016 16:18:32 -0700 (PDT)
Return-Path: <casey@ricochetconsulting.com>
Received: from mail-vk0-x232.google.com (mail-vk0-x232.google.com. [2607:f8b0:400c:c05::232])
by mx.google.com with ESMTPS id 8si832357uar.128.2016.07.20.16.18.32
for <Cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Wed, 20 Jul 2016 16:18:32 -0700 (PDT)
Received-SPF: pass (google.com: domain of casey@ricochetconsulting.com designates 2607:f8b0:400c:c05::232 as permitted sender) client-ip=2607:f8b0:400c:c05::232;
Authentication-Results: mx.google.com;
dkim=pass header.i=@ricochetconsulting-com.20150623.gappssmtp.com;
spf=pass (google.com: domain of casey@ricochetconsulting.com designates 2607:f8b0:400c:c05::232 as permitted sender) smtp.mailfrom=casey@ricochetconsulting.com
Received: by mail-vk0-x232.google.com with SMTP id x130so82749967vkc.0
for <Cecycorrea@gmail.com>; Wed, 20 Jul 2016 16:18:32 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=ricochetconsulting-com.20150623.gappssmtp.com; s=20150623;
h=mime-version:sender:from:date:message-id:subject:to;
bh=+1PlvoK587UzyuTalT7nbvHMbXVfTAMFMvWkg7gjjdI=;
b=jbTWaLqvh0CUK6lU1/gxtR+fZNE3YTDDuTrDozP9yx56D5KqevSx4+3kD5GU6SiO7a
pIES5lPQyBxRmWidpWGOZak36keziETvY4eh4Gw36qpGkVWL2f5qMAKKdSkPR4DMC9Q4
GZW+EHw9t2FbuMBuqXYxXmfAKngHKPbNg3fDGfIrJlfUudtU7hrQY9fV17RVF8dDtV/F
WwkRa0vjV3i6Xwo4k+9qALVSmA7yeL9aQult5nkN6OFbg/CXwbDeB7stkN+FY4XpjRVE
1tuC/Si7I/7wfxkUJl0mfSlNr+aEdjQc2as514PVq+c3LKz+foub6C1LemQSKez5lSjo
1NlQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:sender:from:date:message-id:subject
:to;
bh=+1PlvoK587UzyuTalT7nbvHMbXVfTAMFMvWkg7gjjdI=;
b=BQfX39PP9wIThQt7F1mj+Z+9V5jMOSyE42P5NJtiA+RlLzKeUrBSQV+jagqnxZfUsH
lflNn4xYh6Ngj1hBlKOiXsYf//hxQRfOiXjK2wk98tY7z3/n61CqnDhRSW2gQYIfOV7n
YVfeZ+EBOMt0G56uWnnwmGnVb6tS2/qx/BRxX8Uq7C5wxfCbSx7p56ldF0TBWj67Z4kf
aI7HopAXCJ00ShMWSNd7k2vwtbzKaNrW0HLbxlT60zu4q4ORzWUoQA+qBIxH/POijrXY
UaQN3sLYHKjsOiHwejtuHWP55L8WEgOT4aITUFkV47vaOkGMMOYGUGlLqAgPv5jBtQGY
BOOA==
X-Gm-Message-State: ALyK8tLRLcNR9mQl+Q/vXGWjqRz+jYIymyVV8F4ySHuDP5fzlRHgwgRyNueR2dkxtZ8cUryNIDOlz1PFmTE/3w==
X-Received: by 10.31.69.8 with SMTP id s8mr25676289vka.76.1469056711773; Wed,
20 Jul 2016 16:18:31 -0700 (PDT)
MIME-Version: 1.0
Sender: casey@ricochetconsulting.com
Received: by 10.176.5.193 with HTTP; Wed, 20 Jul 2016 16:18:31 -0700 (PDT)
From: Casey Cobb <casey@projectricochet.com>
Date: Wed, 20 Jul 2016 16:18:31 -0700
X-Google-Sender-Auth: NXzo4v7qdMrnduGBXqkxFVP5044
Message-ID: <CACUVTeA7O2jTqs+Z==hoAD3Ju0Hg=jtGrezLVL9suW9VLRV8Yw@mail.gmail.com>
Subject: Accidental Evil
To: Cecy Correa <Cecycorrea@gmail.com>
Content-Type: multipart/alternative; boundary=001a114daf8a75dbfd0538196b5b

--001a114daf8a75dbfd0538196b5b
Content-Type: text/plain; charset=UTF-8

Hi Cecy,

Great chatting today!

Here's that blog post about Accidental Evil I mentioned:
http://www.medium.com/@caseycobb/when-accidental-evil-makes-your-job-miserable-2bfd19ff7410

Also, you should probably have a listen to the feedback podcasts here:
https://www.manager-tools.com/manager-tools-basics. Pretty powerful model!
They are Elia and Casey approved!

Lastly, here's that brewery I mentioned: http://www.aleindustries.com. When
you're in the Bay Area next, snag one of our beers! :)

Best,
Casey

--
*Casey Cobb*
Partner / Developer
Project Ricochet
www.projectricochet.com

Mobile: 925.270.4935
Skype: caseycobb

--001a114daf8a75dbfd0538196b5b
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hi Cecy,=C2=A0<div><br></div><div>Great chatting today!</d=
iv><div><br></div><div>Here&#39;s that blog post about Accidental Evil I me=
ntioned: <a href=3D"http://www.medium.com/@caseycobb/when-accidental-evil-m=
akes-your-job-miserable-2bfd19ff7410">http://www.medium.com/@caseycobb/when=
-accidental-evil-makes-your-job-miserable-2bfd19ff7410</a></div><div><br></=
div><div>Also, you should probably have a listen to the feedback podcasts h=
ere:=C2=A0<a href=3D"https://www.manager-tools.com/manager-tools-basics">ht=
tps://www.manager-tools.com/manager-tools-basics</a>. Pretty powerful model=
! They are Elia and Casey approved!</div><div><br></div><div>Lastly, here&#=
39;s that brewery I mentioned:=C2=A0<a href=3D"http://www.aleindustries.com=
">http://www.aleindustries.com</a>. When you&#39;re in the Bay Area next, s=
nag one of our beers! :)</div><div><br></div><div>Best,</div><div>Casey</di=
v><div><div><div class=3D"gmail_signature" data-smartmail=3D"gmail_signatur=
e"><div dir=3D"ltr"><div><div dir=3D"ltr"><div><div dir=3D"ltr"><div><div d=
ir=3D"ltr"><div><div><div><br></div><div dir=3D"ltr">

<span style=3D"color:rgb(102,102,102)">--<br><span style=3D"color:rgb(68,68=
,68)"><b>Casey Cobb</b></span><br>Partner / Developer<br>

Project Ricochet<br><a href=3D"http://www.projectricochet.com" target=3D"_b=
lank">www.projectricochet.com</a><br>

<br>

Mobile: <a href=3D"tel:925.270.4935" value=3D"+19252704935" target=3D"_blan=
k">925.270.4935</a><br></span></div><div><span style=3D"color:rgb(102,102,1=
02)">Skype: caseycobb</span></div></div></div></div></div></div></div></div=
></div></div></div></div>
</div></div>

--001a114daf8a75dbfd0538196b5b--
