Delivered-To: cecycorrea@gmail.com
Received: by 10.103.130.70 with SMTP id e67csp486825vsd;
Fri, 1 Jul 2016 22:40:43 -0700 (PDT)
X-Received: by 10.28.134.199 with SMTP id i190mr1573335wmd.26.1467438043694;
Fri, 01 Jul 2016 22:40:43 -0700 (PDT)
Return-Path: <damonc@gmail.com>
Received: from mail-wm0-x22a.google.com (mail-wm0-x22a.google.com. [2a00:1450:400c:c09::22a])
by mx.google.com with ESMTPS id n1si2159281wmn.46.2016.07.01.22.40.43
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Fri, 01 Jul 2016 22:40:43 -0700 (PDT)
Received-SPF: pass (google.com: domain of damonc@gmail.com designates 2a00:1450:400c:c09::22a as permitted sender) client-ip=2a00:1450:400c:c09::22a;
Authentication-Results: mx.google.com;
dkim=pass header.i=@gmail.com;
spf=pass (google.com: domain of damonc@gmail.com designates 2a00:1450:400c:c09::22a as permitted sender) smtp.mailfrom=damonc@gmail.com;
dmarc=pass (p=NONE dis=NONE) header.from=gmail.com
Received: by mail-wm0-x22a.google.com with SMTP id a66so39072818wme.0
for <cecycorrea@gmail.com>; Fri, 01 Jul 2016 22:40:43 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=gmail.com; s=20120113;
h=from:content-transfer-encoding:mime-version:subject:message-id:date
:to;
bh=pwcBCt1cNCWdo6o86F9+VFkYyhScIghnPLiPHhkx1Y0=;
b=zNsn4wy66PF2U0TpvmfZeduGB29nyUDL5XFF3HhvT07gyLwnE09gA177Cii686L2ge
kJEOMZmoA3AnXEcZbQ20QV6XDSuPMfmkuxRYKv15HQIugVy8nXsGaSB0cIw3o4ZzuHCM
ypC5k20oeTTOlsx5fnduhZr6YP7lDUVtGhL1mGAUQN6BGHwOXSYPZmaTENmrFDAYMp2z
3IDjoDLkoPEQd8nU43Uq/cXreZXM5hYvDmZog7HwcDL0VroNaW3G+SqhXl1qbwmW5GR4
kY1tKlmNQjeluHK3OSVjycZk+otsg37NvnKEAJ1h7abxefGszOOWZYqmIS3MGFHibMvX
v8Wg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:from:content-transfer-encoding:mime-version
:subject:message-id:date:to;
bh=pwcBCt1cNCWdo6o86F9+VFkYyhScIghnPLiPHhkx1Y0=;
b=lB0BIcg+xqblcZ0KnMHfi3PEAcIKRfRTmcKjPCGlIrB5JRtAnRdLeZVO8d+FcOlWdS
HvEzxCkdyNkPUpXih3Nclc4xokVO1l0M/Gx8xTNhP62RwZcupmGc+kJFKKNQnj1avB0l
Ie8IUHSMKz7uq9P+6OtusdCegJfSA9FYthD9SsSkTaTLZV6Y7sLgosNbu4hK/MZ8YKoM
6MGuVqYwm/6R6+UVnbzjfpS+MpSsQtqeRmPnPohprreR0fqndOHiI4nVIdUy97bxL9dm
KtaYscuDbs8d4KFW4u9I8bEN8Yc9NiMmPAXe0mU3jcDiM1j9c9nil0h7fWGBC5DFFgZR
qw5w==
X-Gm-Message-State: ALyK8tJKFRTftNSMZYvtVFNH/zLngT4Zcv8IaRA0u9tqSNWtl3yFx2hgNsI4r58zEKa8qw==
X-Received: by 10.194.8.38 with SMTP id o6mr1427763wja.13.1467438043044;
Fri, 01 Jul 2016 22:40:43 -0700 (PDT)
Return-Path: <damonc@gmail.com>
Received: from [10.5.2.116] ([46.218.112.141])
by smtp.gmail.com with ESMTPSA id cx8sm1429841wjb.37.2016.07.01.22.40.39
for <cecycorrea@gmail.com>
(version=TLS1 cipher=ECDHE-RSA-AES128-SHA bits=128/128);
Fri, 01 Jul 2016 22:40:39 -0700 (PDT)
From: Damon Clinkscales <damonc@gmail.com>
Content-Type: text/plain;
charset=us-ascii
Content-Transfer-Encoding: 7bit
Mime-Version: 1.0 (1.0)
Subject: Invites
Message-Id: <B166E786-07F7-4B5B-8783-BA3793E5624E@gmail.com>
Date: Sat, 2 Jul 2016 07:40:37 +0200
To: Cecy Correa <cecycorrea@gmail.com>
X-Mailer: iPhone Mail (13F69)

Cecy,

Hello!

Could you please invite these two guys to AoR slack?

Thanks,
/damon

phillipemersonjones@gmail.com
joemarion.io@gmail.com
