Delivered-To: cecycorrea@gmail.com
Received: by 10.176.5.194 with SMTP id e60csp883693uae;
Thu, 12 May 2016 08:16:26 -0700 (PDT)
X-Received: by 10.194.42.69 with SMTP id m5mr10586569wjl.89.1463066186506;
Thu, 12 May 2016 08:16:26 -0700 (PDT)
Return-Path: <laura.e.hersh@gmail.com>
Received: from mail-wm0-x22d.google.com (mail-wm0-x22d.google.com. [2a00:1450:400c:c09::22d])
by mx.google.com with ESMTPS id gs6si16258598wjc.83.2016.05.12.08.16.26
for <CECYCORREA@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Thu, 12 May 2016 08:16:26 -0700 (PDT)
Received-SPF: pass (google.com: domain of laura.e.hersh@gmail.com designates 2a00:1450:400c:c09::22d as permitted sender) client-ip=2a00:1450:400c:c09::22d;
Authentication-Results: mx.google.com;
dkim=pass header.i=@gmail.com;
spf=pass (google.com: domain of laura.e.hersh@gmail.com designates 2a00:1450:400c:c09::22d as permitted sender) smtp.mailfrom=laura.e.hersh@gmail.com;
dmarc=pass (p=NONE dis=NONE) header.from=gmail.com
Received: by mail-wm0-x22d.google.com with SMTP id n129so260120283wmn.1
for <CECYCORREA@GMAIL.COM>; Thu, 12 May 2016 08:16:26 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=gmail.com; s=20120113;
h=mime-version:date:message-id:subject:from:to;
bh=tsOVaiE3NE8wBAwAFo7QC3nnfSSxC2ewt0zKsZQK+Ys=;
b=ku7t3zSTyLfjBjIw5AQh7UqUDNZMMdW0zh6f+JZTfEIpIVuFUisepsqR5gWOUBaFVg
Rv/1Kd0uxLkIudWf2PCqbMfmaJPaAfV2C7xk26aFYCjADhNt3wfQ/9AD9VJGccmS3/Qz
ZLVyco/1VHOjUpx1F/UDJHosteh923dWCN1zzePDwxAWxnuxMBV21fk59iEBHSuIOQV9
Oslig1uyB49nZ9YjAoWBlnXREm/T6STSyUXomJg1AFSYuHsS+6Q/4gHhBNuTSmNrVUKi
MgfC7Z4XJLGU8/LxPGZOe51mNt2GubTd34MUu2Vk0x04Zg8p+Bn7Op385nH6iXvTk/nf
ZWCQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:date:message-id:subject:from:to;
bh=tsOVaiE3NE8wBAwAFo7QC3nnfSSxC2ewt0zKsZQK+Ys=;
b=d5gzTaUIk5fUvjf54I3Ll9za1qraCNn5xFaH2ZKvfWPMIdPPSzIzML9L+7aM3t0Qqw
RRdCrTRQzM4jTgKor6LSvvyEcfL6qU8LSELHm32qFgecIta1c8VdvvtLUUwBhjPLHyLG
vdMRxt7wK4ZrtSwEo3HdxJQP0lOTvQJMfx5jKNCAPsUn1Ubz9eNw2KdFfGg1cTvpniDX
WqxIaHuPkbBqb9iGVbHWreGI7tkCti8SEVtUfum4qLwURm4xrqqragjnX7hE0TrJlH8i
zxawHVRh/CcSx9yWfgseYv/VjT4EaTW/rqcPvWrsz+Dby9LE7GZErU9Qp3pXiJrx8keM
gGlA==
X-Gm-Message-State: AOPr4FU+dK3+e0VqPr/bX5LoPWLNm2vF/G1KG6tDYxecDjzTy8V/gOWCfkKPwgDGP4GVxlG5xJ4pdmIhwI2cIw==
MIME-Version: 1.0
X-Received: by 10.194.92.237 with SMTP id cp13mr10518801wjb.168.1463066186114;
Thu, 12 May 2016 08:16:26 -0700 (PDT)
Received: by 10.194.204.234 with HTTP; Thu, 12 May 2016 08:16:26 -0700 (PDT)
Date: Thu, 12 May 2016 10:16:26 -0500
Message-ID: <CANvv0RmT=8t=wbJs2ZeGhU0EiVFnXL6OMVwjJUKAjhnsW0MFkw@mail.gmail.com>
Subject: GDI Teach Assisting!
From: Laura Hersh <laura.e.hersh@gmail.com>
To: CECYCORREA@GMAIL.COM
Content-Type: multipart/alternative; boundary=047d7beb945a4e6c2f0532a6a4a1

--047d7beb945a4e6c2f0532a6a4a1
Content-Type: text/plain; charset=UTF-8

Hey Cecy!

I don't know if you remember me or not. I was at your Git/Github class
recently and mentioned (at the Sketch class) that I was interested in TAing
for GDI.

Are you still looking for TAs for the upcoming Intro to HTML/CSS class?
Because I would love to help out if so!
http://www.meetup.com/Girl-Develop-It-Austin/events/230878101/

Let me know if you're still looking for TAs for that class or are full!
Thank you so much!



Laura Hersh
*Visual Designer*

W: laurahersh.com
P: 484.553.4445
E: laura.e.hersh@gmail.com

--047d7beb945a4e6c2f0532a6a4a1
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr"><div>Hey Cecy!</div><div><br></div><div>I don&#39;t know i=
f you remember me or not. I was at your Git/Github class recently and menti=
oned (at the Sketch class) that I was interested in TAing for GDI.</div><di=
v><br></div><div>Are you still looking for TAs for the upcoming Intro to HT=
ML/CSS class? Because I would love to help out if so!</div><div><a href=3D"=
http://www.meetup.com/Girl-Develop-It-Austin/events/230878101/">http://www.=
meetup.com/Girl-Develop-It-Austin/events/230878101/</a><br></div><div><br><=
/div><div>Let me know if you&#39;re still looking for TAs for that class or=
are full! Thank you so much!</div><br clear=3D"all"><div><br></div><br><di=
v class=3D"gmail_signature"><div dir=3D"ltr"><div><div dir=3D"ltr"><font si=
ze=3D"2">Laura Hersh</font><div><div><i><font color=3D"#999999">Visual Desi=
gner</font></i></div><div><font color=3D"#999999"><br></font></div><div><fo=
nt color=3D"#999999">W:=C2=A0<a href=3D"http://laurahersh.com" target=3D"_b=
lank">laurahersh.com</a></font></div></div><div><font color=3D"#999999">P: =
484.553.4445</font></div><div><font color=3D"#999999">E: <a href=3D"mailto:=
laura.e.hersh@gmail.com" target=3D"_blank">laura.e.hersh@gmail.com</a></fon=
t></div></div></div></div></div>
</div>

--047d7beb945a4e6c2f0532a6a4a1--
