Delivered-To: cecycorrea@gmail.com
Received: by 10.103.130.70 with SMTP id e67csp1095939vsd;
Wed, 6 Jul 2016 19:50:01 -0700 (PDT)
X-Received: by 10.194.11.5 with SMTP id m5mr23323353wjb.119.1467859800698;
Wed, 06 Jul 2016 19:50:00 -0700 (PDT)
Return-Path: <chondra@sxsw.com>
Received: from mail-wm0-x22c.google.com (mail-wm0-x22c.google.com. [2a00:1450:400c:c09::22c])
by mx.google.com with ESMTPS id p8si3446857wjo.225.2016.07.06.19.50.00
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Wed, 06 Jul 2016 19:50:00 -0700 (PDT)
Received-SPF: pass (google.com: domain of chondra@sxsw.com designates 2a00:1450:400c:c09::22c as permitted sender) client-ip=2a00:1450:400c:c09::22c;
Authentication-Results: mx.google.com;
dkim=pass header.i=@sxsw-com.20150623.gappssmtp.com;
spf=pass (google.com: domain of chondra@sxsw.com designates 2a00:1450:400c:c09::22c as permitted sender) smtp.mailfrom=chondra@sxsw.com
Received: by mail-wm0-x22c.google.com with SMTP id a66so13568814wme.0
for <cecycorrea@gmail.com>; Wed, 06 Jul 2016 19:50:00 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=sxsw-com.20150623.gappssmtp.com; s=20150623;
h=mime-version:in-reply-to:references:from:date:message-id:subject:to;
bh=1ZhSgx1KHqL82e/GycR6+K1AKv5DyOhhlo6vs7NArBQ=;
b=OuQMRcLoxakin2kzgQibo9B/tSMn0W98IMW7DHB5wlQZByBB4bsiM8H5Fta/RtqMv9
lDCABIMlpGqpayeYxLeFmai2tzgfVwIW1ecN7uWqFO3/Cj29O1Gxak+u3Dkh2G2py2wJ
TsvupcoSrt/+1sgAqfuWDPUmM7Hrwd/BwIg4+V2XlrBNGHlWy8PHDG0ReLATKokAc3E+
hnmrMRGT/heq+fsINtRo1iLl/uyTOTO/E37kOC3LN3ia8TV2X4eq5kXy29z/fSOxB6wD
aY7Noi4Xj+amswoxYMgSFabCJ6BuwPs+dUq6iAyZ2ZZd3sVJoVw1BD7h6C+ql/aZ5Z2M
N7lw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:in-reply-to:references:from:date
:message-id:subject:to;
bh=1ZhSgx1KHqL82e/GycR6+K1AKv5DyOhhlo6vs7NArBQ=;
b=KArKT8yKNxVcFq9hXyCctMDARi4Wyc8fQaOkinXvSrXuxwBu37kyVBMFmL0+GedHIB
5ghNu3r9wwVFq7I9D8exRtCPgu+mDAWViOLHniJE5vCm8uz+1ynpNVT4Ep8zzPaO+RC3
uv/YkDxp3LDhUcsfKiRWAUrWvHoVQZ3eddPOrNUSqOw2FoAXeTe4AXuHPPL7MA5Eugf1
lfAA7Jp5g0nE05qfdIW2rl4wGjik0uP3+0IijeqJHVfdKSNfAHvpxVlpdkkKpxBjSbGw
dybpr2q2HmiiA/llwgVNwPMQUyRi5Tm/jMC9QuHFayezw0kz8Bm29gECadUWFsEJtTfW
xKTQ==
X-Gm-Message-State: ALyK8tKlv735y++ovMba6DFnQ7d7KsWh4rfQDHSLm0MG2xvg9VbFci/qwd9VMIrkzVkRbzPUDz4Af9jSaZE4C/DH
X-Received: by 10.194.216.106 with SMTP id op10mr26521100wjc.178.1467859799480;
Wed, 06 Jul 2016 19:49:59 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.28.144.72 with HTTP; Wed, 6 Jul 2016 19:49:19 -0700 (PDT)
In-Reply-To: <CAL4Zj+KX14wsOYt3Op773Ook_YbJanpJ9rhOT2D8DQS2a6NPEQ@mail.gmail.com>
References: <CAJpm1F6=BJQCarLjEKJoA=DK-g8PgLnVhBcAVH2FfZvU9q=3QA@mail.gmail.com>
<CAL4Zj+KX14wsOYt3Op773Ook_YbJanpJ9rhOT2D8DQS2a6NPEQ@mail.gmail.com>
From: Chondra Washington <chondra@sxsw.com>
Date: Wed, 6 Jul 2016 21:49:19 -0500
Message-ID: <CAJpm1F6unYt3Smt5sEROUM4XibQLjon9EiKzZUEQv6rQ=iGvMA@mail.gmail.com>
Subject: Re: SXSW 2016 / Cecy / Thanks for Your Feedback
To: Cecy Correa <cecycorrea@gmail.com>
Content-Type: multipart/alternative; boundary=089e01493d6eeda80d053702bd34

--089e01493d6eeda80d053702bd34
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hi Cecy,

Thanks getting back to me!!
Dang, that is a terrible story to hear. As much as we try to stay on the
same page with the venue staff sometimes there is miscommunication.

Unfortunately, the venue staff was likely told one thing then things
changed and they were not updated. In the end we are all trying to do our
jobs and sometimes it doesn't work as well as we planned.

Thanks for letting us know and if you have any more feedback, questions etc
please feel free to reach out.

Hope to see you in March! :-)



Chondra Washington
SXSW Interactive | Administration
chondra@sxsw.com
O: 512-467-7979



On Tue, Jul 5, 2016 at 4:51 PM, Cecy Correa <cecycorrea@gmail.com> wrote:

> I am so sorry! I mean to reply! I *really* appreciate you following up on
> my comment about the issue I had at the venue with security and staff not
> communicating.
>
> This is what happened:
>
> For the Interactive Conference closing night party, which I have attended
> in the past, I know you are able to get in with just your badge
> (Interactive or Gold)...
>
> When I got to the venue to stand in line (Stubb's), I was turned away and
> was told badges were not allowed, just wristbands. That was news to me
> since it was the *Interactive* closing night party, and I had always been
> able to get in with just my badge (not a wristband). I showed them the ap=
p,
> which said Interactive badges were welcome, and still they did not believ=
e
> me...
>
> I tweeted at MediaTemple, who was putting on the party, and they tweeted
> right back at me saying I could come in with my badge. I showed that to
> security and they still did not believe me...
>
> I talked to SXSW staff that was at the venue and they told me I would be
> allowed in, but the venue security at Stubb's did not even believe the
> people with "SXSW staff" shirts, which was very frustrating.
>
> It seems someone was able to clarify things for the venue security at
> Stubbs, but it took me walking away from the event, and then coming back
> later and essentially begging the security guard to double-check.
>
> Thanks so much again for following up! I honestly really appreciate it.
> Super sorry for the delayed reply!
>
> Best,
>
> *@cecycorrea*
>
> On Mon, May 23, 2016 at 4:27 PM, Chondra Washington <chondra@sxsw.com>
> wrote:
>
>> Dear Cecy,
>>
>> This is Chondra Washington from the South by Southwest (SXSW) Interactiv=
e
>> Festival. HI!!!
>>
>> Thank you for completing the post=C2=AD-event online survey.  Getting fe=
edback
>> from registrants is incredibly valuable to us as we try to continue to
>> improve SXSW. More to the point, attendees see the event from a complete=
ly
>> different perspective than we do as staff. Reading these post=C2=AD-even=
t
>> surveys often helps us learn about good and not=C2=AD-so=C2=AD-good thin=
gs that
>> happened at SXSW that we weren=E2=80=99t completely aware of.
>>
>> I wanted to touch base with you on one of the specific points about the
>> 2016 event that you raised in your feedback.
>>
>> We are so glad to hear you enjoyed the Convergence track, we are working
>> hard to spread the good word regarding Convergence (and it is expanding!=
).
>> It is the best way to get the biggest bang for your buck (in my opinion)=
.
>>
>> You also mentioned communication with venue security could have been
>> better. Can you give me any specific examples of what type of confusion =
you
>> experienced?
>>
>> Feel free to respond with feedback.
>>
>> We hope to see you in Austin again next year for SXSW 2017, which is
>> scheduled March 10-19. Registration for the 2017 event will open on
>> Monday, August 1 =E2=80=94 remember to register early for the best selec=
tion of
>> downtown hotel rooms.
>>
>> Also, if you are interested in speaking at the 2017 event, know that the
>> PanelPicker entry process begins on Tuesday, June 28. See
>> http://sxsw.com/interactive/conference/panelpicker for more info on the
>> PanelPicker process.
>>
>>
>>
>>
>> Chondra Washington
>> SXSW | Interactive Administrative Assistant
>> chondra@sxsw.com
>>
>> Mark your calendars, SXSW 2017 PanelPicker (our session proposal
>> platform) opens June 28.
>>
>
>

--089e01493d6eeda80d053702bd34
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hi Cecy,=C2=A0<div><br></div><div>Thanks getting back to m=
e!!</div><div>Dang, that is a terrible story to hear. As much as we try to =
stay on the same page with the venue staff sometimes there is miscommunicat=
ion.=C2=A0</div><div><br></div><div>Unfortunately, the venue staff was like=
ly told one thing then things changed and they were not updated. In the end=
we are all trying to do our jobs and sometimes it doesn&#39;t work as well=
as we planned.=C2=A0</div><div><br></div><div>Thanks for letting us know a=
nd if you have any more feedback, questions etc please feel free to reach o=
ut.=C2=A0</div><div><br></div><div>Hope to see you in March! :-)</div><div>=
<br></div><div><br></div></div><div class=3D"gmail_extra"><br clear=3D"all"=
><div><div class=3D"gmail_signature" data-smartmail=3D"gmail_signature"><di=
v dir=3D"ltr"><div><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div =
dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"=
ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><d=
iv dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=
=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr=
"><div style=3D"text-align:left"><span style=3D"font-size:12.8px"><font fac=
e=3D"arial black, sans-serif" color=3D"#000000">Chondra Washington</font></=
span></div><div style=3D"text-align:left"><font color=3D"#000000"><span sty=
le=3D"font-family:arial,helvetica,sans-serif;font-size:small">SXSW Interact=
ive | Administration</span></font></div><div style=3D"text-align:left"><fon=
t color=3D"#000000" face=3D"Helvetica"><a href=3D"mailto:chondra@sxsw.com" =
target=3D"_blank">chondra@sxsw.com</a></font></div><div style=3D"text-align=
:left">O: 512-467-7979=C2=A0</div><div style=3D"text-align:left"><br></div>=
<div style=3D"text-align:left"><br></div></div></div></div></div></div></di=
v></div></div></div></div></div></div></div></div></div></div></div></div><=
/div></div></div></div></div></div></div>
<br><div class=3D"gmail_quote">On Tue, Jul 5, 2016 at 4:51 PM, Cecy Correa =
<span dir=3D"ltr">&lt;<a href=3D"mailto:cecycorrea@gmail.com" target=3D"_bl=
ank">cecycorrea@gmail.com</a>&gt;</span> wrote:<br><blockquote class=3D"gma=
il_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-lef=
t:1ex"><div dir=3D"ltr">I am so sorry! I mean to reply! I <b>really</b> app=
reciate you following up on my comment about the issue I had at the venue w=
ith security and staff not communicating.<div><br></div><div>This is what h=
appened:</div><div><br></div><div>For the Interactive Conference closing ni=
ght party, which I have attended in the past, I know you are able to get in=
with just your badge (Interactive or Gold)...=C2=A0</div><div><br></div><d=
iv>When I got to the venue to stand in line (Stubb&#39;s), I was turned awa=
y and was told badges were not allowed, just wristbands. That was news to m=
e since it was the <i>Interactive</i> closing night party, and I had always=
been able to get in with just my badge (not a wristband). I showed them th=
e app, which said Interactive badges were welcome, and still they did not b=
elieve me...=C2=A0</div><div><br></div><div>I tweeted at MediaTemple, who w=
as putting on the party, and they tweeted right back at me saying I could c=
ome in with my badge. I showed that to security and they still did not beli=
eve me...</div><div><br></div><div>I talked to SXSW staff that was at the v=
enue and they told me I would be allowed in, but the venue security at Stub=
b&#39;s did not even believe the people with &quot;SXSW staff&quot; shirts,=
which was very frustrating.</div><div><br></div><div>It seems someone was =
able to clarify things for the venue security at Stubbs, but it took me wal=
king away from the event, and then coming back later and essentially beggin=
g the security guard to double-check.</div><div><br></div><div>Thanks so mu=
ch again for following up! I honestly really appreciate it. Super sorry for=
the delayed reply!</div><div><br></div><div>Best,</div></div><div class=3D=
"gmail_extra"><br clear=3D"all"><div><div data-smartmail=3D"gmail_signature=
"><div dir=3D"ltr"><b>@cecycorrea</b></div></div></div><div><div class=3D"h=
5">
<br><div class=3D"gmail_quote">On Mon, May 23, 2016 at 4:27 PM, Chondra Was=
hington <span dir=3D"ltr">&lt;<a href=3D"mailto:chondra@sxsw.com" target=3D=
"_blank">chondra@sxsw.com</a>&gt;</span> wrote:<br><blockquote class=3D"gma=
il_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-lef=
t:1ex"><div dir=3D"ltr"><div style=3D"font-size:12.8px">Dear Cecy,</div><di=
v style=3D"font-size:12.8px"><br></div><div style=3D"font-size:12.8px">=E2=
=80=A8This is Chondra Washington from the South by Southwest (SXSW) Interac=
tive Festival. HI!!!</div><div style=3D"font-size:12.8px"><br></div><div st=
yle=3D"font-size:12.8px">Thank you for completing the post=C2=AD-event onli=
ne survey.=C2=A0 Getting feedback from registrants is incredibly valuable t=
o us as we try to continue to improve SXSW. More to the point, attendees se=
e the event from a completely different perspective than we do as staff. Re=
ading these post=C2=AD-event surveys often helps us learn about good and no=
t=C2=AD-so=C2=AD-good things that happened at SXSW that we weren=E2=80=99t =
completely aware of.=C2=A0</div><div style=3D"font-size:12.8px"><br></div><=
div style=3D"font-size:12.8px">I wanted to touch base with you on one of th=
e specific points about the 2016 event that you raised in your feedback.=C2=
=A0</div><div style=3D"font-size:12.8px"><br></div><div style=3D"font-size:=
12.8px">We are so glad to hear you enjoyed the Convergence track, we are wo=
rking hard to spread the good word regarding Convergence (and it is expandi=
ng!). It is the best way to get the biggest bang for your buck (in my opini=
on).</div><div style=3D"font-size:12.8px"><br></div><div style=3D"font-size=
:12.8px">You also mentioned communication with venue security could have be=
en better. Can you give me any specific examples of what type of confusion =
you experienced?=C2=A0</div><div style=3D"font-size:12.8px"><br></div><div =
style=3D"font-size:12.8px"><div style=3D"font-size:12.8px"><div style=3D"fo=
nt-size:12.8px"><div style=3D"font-size:12.8px"><span style=3D"font-size:12=
.8px">Feel free to respond with feedback.</span><br></div><div style=3D"fon=
t-size:12.8px"><span style=3D"font-size:12.8px"><br></span></div><div style=
=3D"font-size:12.8px"><span style=3D"font-size:12.8px">We hope to see you i=
n Austin again next year for SXSW 2017, which is schedule</span><span style=
=3D"font-size:12.8px">d March 10-</span><span style=3D"font-size:12.8px">19=
. Registration for the 2017 event will open o</span><span style=3D"font-siz=
e:12.8px">n Monday, August</span><span style=3D"font-size:12.8px">=C2=A0</s=
pan><span style=3D"font-size:12.8px">1 =E2=80=94 remember to register early=
for the best selection of downtown hotel rooms.=C2=A0</span><br></div><div=
style=3D"font-size:12.8px"><br></div><div style=3D"font-size:12.8px">Also,=
if you are interested in speaking at the 2017 event, know that the PanelPi=
cker entry process begins on Tuesday, June=C2=A028. See=C2=A0<a href=3D"htt=
p://sxsw.com/interactive/conference/panelpicker" target=3D"_blank">http://s=
xsw.com/interactive/conference/panelpicker</a>=C2=A0for more info on the Pa=
nelPicker process.</div><div><br></div></div></div></div><div><br></div><di=
v><br></div><div><br></div><div><div><div dir=3D"ltr"><div><div dir=3D"ltr"=
><div><div dir=3D"ltr"><div><div dir=3D"ltr"><div><div dir=3D"ltr"><div><di=
v dir=3D"ltr"><div><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div =
dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"=
ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><d=
iv dir=3D"ltr"><div dir=3D"ltr"><div style=3D"text-align:left"><span style=
=3D"font-size:12.8px"><font face=3D"arial black, sans-serif" color=3D"#0000=
00">Chondra Washington</font></span></div><div style=3D"text-align:left"><f=
ont color=3D"#000000"><span style=3D"font-family:arial,helvetica,sans-serif=
;font-size:small">SXSW | Interactive Administrative=C2=A0</span><span style=
=3D"font-size:12.8px"><font face=3D"arial, helvetica, sans-serif">Assistant=
=C2=A0</font></span></font></div><div style=3D"text-align:left"><font color=
=3D"#000000" face=3D"Helvetica"><a href=3D"mailto:chondra@sxsw.com" target=
=3D"_blank">chondra@sxsw.com</a></font></div><div style=3D"text-align:left"=
><br></div><div style=3D"text-align:left">Mark your calendars, SXSW 2017 Pa=
nelPicker (our session proposal platform) opens June 28.=C2=A0</div></div><=
/div></div></div></div></div></div></div></div></div></div></div></div></di=
v></div></div></div></div></div></div></div></div></div></div></div></div><=
/div></div>
</div>
</blockquote></div><br></div></div></div>
</blockquote></div><br></div>

--089e01493d6eeda80d053702bd34--
