Delivered-To: cecycorrea@gmail.com
Received: by 10.182.97.36 with SMTP id dx4csp623375obb;
Fri, 15 Jul 2016 09:09:52 -0700 (PDT)
X-Received: by 10.129.124.138 with SMTP id x132mr10910902ywc.166.1468598992470;
Fri, 15 Jul 2016 09:09:52 -0700 (PDT)
Return-Path: <scott.w.hudson@gmail.com>
Received: from mail-yw0-x234.google.com (mail-yw0-x234.google.com. [2607:f8b0:4002:c05::234])
by mx.google.com with ESMTPS id y63si893453ywa.480.2016.07.15.09.09.52
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Fri, 15 Jul 2016 09:09:52 -0700 (PDT)
Received-SPF: pass (google.com: domain of scott.w.hudson@gmail.com designates 2607:f8b0:4002:c05::234 as permitted sender) client-ip=2607:f8b0:4002:c05::234;
Authentication-Results: mx.google.com;
dkim=pass header.i=@gmail.com;
spf=pass (google.com: domain of scott.w.hudson@gmail.com designates 2607:f8b0:4002:c05::234 as permitted sender) smtp.mailfrom=scott.w.hudson@gmail.com;
dmarc=pass (p=NONE dis=NONE) header.from=gmail.com
Received: by mail-yw0-x234.google.com with SMTP id i12so101686004ywa.1
for <cecycorrea@gmail.com>; Fri, 15 Jul 2016 09:09:52 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=gmail.com; s=20120113;
h=mime-version:references:in-reply-to:from:date:message-id:subject:to;
bh=/O7mrBCzCs6YJWGT8rYDyABOtS17EAeq+c7zrOS+3/M=;
b=mh7tpqKv7AGfR0Rc9qRP7HJie9j8xIYu9E6p6XmwxAECZKlOH9xKPO8aX0+h988xyq
tnPCeDWlW2ftHJTicnDwQtrmnDmy48FMcRybmfy3tDVoW96PE7aP1HYv6laRpg53KdFY
V9vtoZAWVvlUs+AC3GS1yphXwpIxS9VOKefCkKuUYodeURrVcybeVFmd/3jdLrIscrUs
KFHF77qrtnjuR177Sp/KBiDZck0JQDZqThzf7BPvxS5b9gfFAf25ZL3zTIQdu2Fl4zac
6FyHMO+YuiBWFuP0vuoemLm082/JW2ttBf9f9Myycv0y1uaCh1XALlfmGpxMhZXRgf/W
r4vg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:references:in-reply-to:from:date
:message-id:subject:to;
bh=/O7mrBCzCs6YJWGT8rYDyABOtS17EAeq+c7zrOS+3/M=;
b=Nxq7Q58bEgYb9PgpbLqGW/K7FJvE/hr+ps4AfI0JZNv/VCj3pyGoNg2SYqqQPj1Gr9
eDz26vvEk1uhyCVkiF4Hrvzwm7IBtFxwBY0UJgaczcSLbLz2mJOT0gfIooajorY1hKrD
PbyJMoKEcAbtKoI6S47tpwpbdAhyQ+bIaYU55BH0nVW3Ln8a7nOg0KQj0uk6i56Spyic
zRhPQTd0jf86IUIYOGa2ym7bbsOs5ajYidpfAmN7DlWcSJzTR7vdNqmPKuiBJtFczu7N
eYWTDo7297OtPrSKISNSXBsVFiF8lbGm9EvD99SzHvVUfgEXxbqz+juvUe2L2jS5TdXW
yGbQ==
X-Gm-Message-State: ALyK8tI0Q/bEagKia80nkO+hNlbcDYj58hkcjI/sGv1m0vCtcoH61SRIAPWFfHB7XQeVcnncpp2T3MY8BEtA4w==
X-Received: by 10.37.83.138 with SMTP id h132mr13720842ybb.185.1468598992053;
Fri, 15 Jul 2016 09:09:52 -0700 (PDT)
MIME-Version: 1.0
References: <CA+vo8J6FGG158ze36jsNWNMH+ssyfUf3d9bpxzwNEYRF3O9oaw@mail.gmail.com>
<CAL4Zj++wOO18RMSk3apuhmoNwJP4w2cOFM-zUiocUsrk8-g7ug@mail.gmail.com>
<CAM-iQhL051nQSp7KPLVQWtzmGwO0zqyT5FRqpzp2NKxdAyj0_g@mail.gmail.com> <CAL4Zj+LGdhmYc40LaKJfuXiKEtk+_P7uU-FOH0xAfwgDC5EAsQ@mail.gmail.com>
In-Reply-To: <CAL4Zj+LGdhmYc40LaKJfuXiKEtk+_P7uU-FOH0xAfwgDC5EAsQ@mail.gmail.com>
From: Scott Hudson <scott.w.hudson@gmail.com>
Date: Fri, 15 Jul 2016 16:09:42 +0000
Message-ID: <CAM-iQhJUq2-6QGTRNMuXWb8GNS74-N3a_03=gHa2sph0kMxZQw@mail.gmail.com>
Subject: Re: Potential speaker for future Refresh
To: Cecy Correa <cecycorrea@gmail.com>
Content-Type: multipart/alternative; boundary=001a113e5f9e3d2b9f0537aed900

--001a113e5f9e3d2b9f0537aed900
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

I was thinking about doing a talk on the psychology of motivation for
individuals and teams, mainly because it was some of the most useful
information I got out of college and it really prepared me during my
self-teaching in the programming world.

On Fri, Jul 15, 2016 at 10:54 AM Cecy Correa <cecycorrea@gmail.com> wrote:

> Sounds great!
>
> Can you let me know what you're thinking about speaking on just so I can
> pencil that into our calendar? I need to know a rough idea of the topic s=
o
> I can counter program :)
>
> Best,
>
> *@cecycorrea*
>
> On Thu, Jul 14, 2016 at 6:22 PM, Scott Hudson <scott.w.hudson@gmail.com>
> wrote:
>
>> Hey Cecy, hope all is well in your world!
>>
>> Sure, that works.  I'll go ahead and write the talk over the next few
>> weeks in case something changes.  Thanks!
>>
>> SH
>>
>>
>> On Thu, Jul 14, 2016 at 10:02 AM Cecy Correa <cecycorrea@gmail.com>
>> wrote:
>>
>>> Awesome, thanks Dan! :)
>>>
>>> Scott =E2=80=94 Happy to have you come and speak on a topic of your cho=
ice since
>>> you come so highly recommended. We are *tentatively *booked until
>>> November, would that work for you? Out meetup in November falls on 11/8=
.
>>> Let me know!
>>>
>>> Best,
>>>
>>> *@cecycorrea*
>>>
>>> On Thu, Jul 14, 2016 at 9:03 AM, Dan DeFelippi <dan@driverdan.com>
>>> wrote:
>>>
>>>> Hi Cecy,
>>>>
>>>> Scott Hudson <http://scottwhudson.com/> expressed interest in giving a
>>>> talk at a future Refresh if you need speakers. As his former coworker =
and
>>>> boss I can vouch for his ability to talk in front of groups. I'm sure =
he
>>>> has some interesting things he could speak about.
>>>>
>>>> --
>>>> Dan DeFelippi
>>>> +1.585.466.4747
>>>> http://driverdan.com
>>>> Follow me on Twitter at @ExpertDan <http://twitter.com/ExpertDan>
>>>>
>>>
>>> --
>> Scott Hudson
>> Software Engineer
>> scottwhudson.com
>>
>
> --
Scott Hudson
Software Engineer
scottwhudson.com

--001a113e5f9e3d2b9f0537aed900
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">I was thinking about doing a talk on the psychology of mot=
ivation for individuals and teams, mainly because it was some of the most u=
seful information I got out of college and it really prepared me during my =
self-teaching in the programming world.</div><br><div class=3D"gmail_quote"=
><div dir=3D"ltr">On Fri, Jul 15, 2016 at 10:54 AM Cecy Correa &lt;<a href=
=3D"mailto:cecycorrea@gmail.com">cecycorrea@gmail.com</a>&gt; wrote:<br></d=
iv><blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left=
:1px #ccc solid;padding-left:1ex"><div dir=3D"ltr">Sounds great!<div><br></=
div><div>Can you let me know what you&#39;re thinking about speaking on jus=
t so I can pencil that into our calendar? I need to know a rough idea of th=
e topic so I can counter program :)</div><div><br></div><div>Best,</div></d=
iv><div class=3D"gmail_extra"><br clear=3D"all"><div><div data-smartmail=3D=
"gmail_signature"><div dir=3D"ltr"><b>@cecycorrea</b></div></div></div></di=
v><div class=3D"gmail_extra">
<br><div class=3D"gmail_quote">On Thu, Jul 14, 2016 at 6:22 PM, Scott Hudso=
n <span dir=3D"ltr">&lt;<a href=3D"mailto:scott.w.hudson@gmail.com" target=
=3D"_blank">scott.w.hudson@gmail.com</a>&gt;</span> wrote:<br><blockquote c=
lass=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;=
padding-left:1ex"><div dir=3D"ltr"><div>Hey Cecy, hope all is well in your =
world!</div><div><br></div>Sure, that works.=C2=A0 I&#39;ll go ahead and wr=
ite the talk over the next few weeks in case something changes.=C2=A0 Thank=
s!<div><br></div><div>SH<div><div><br><br><div class=3D"gmail_quote"><div d=
ir=3D"ltr">On Thu, Jul 14, 2016 at 10:02 AM Cecy Correa &lt;<a href=3D"mail=
to:cecycorrea@gmail.com" target=3D"_blank">cecycorrea@gmail.com</a>&gt; wro=
te:<br></div><blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;b=
order-left:1px #ccc solid;padding-left:1ex"><div dir=3D"ltr">Awesome, thank=
s Dan! :)<div><br></div><div>Scott =E2=80=94 Happy to have you come and spe=
ak on a topic of your choice since you come so highly recommended. We are <=
i>tentatively=C2=A0</i>booked until November, would that work for you? Out =
meetup in November falls on 11/8. Let me know!</div><div><br></div><div>Bes=
t,</div></div><div class=3D"gmail_extra"><br clear=3D"all"><div><div data-s=
martmail=3D"gmail_signature"><div dir=3D"ltr"><b>@cecycorrea</b></div></div=
></div></div><div class=3D"gmail_extra">
<br><div class=3D"gmail_quote">On Thu, Jul 14, 2016 at 9:03 AM, Dan DeFelip=
pi <span dir=3D"ltr">&lt;<a href=3D"mailto:dan@driverdan.com" target=3D"_bl=
ank">dan@driverdan.com</a>&gt;</span> wrote:<br><blockquote class=3D"gmail_=
quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-left:1=
ex"><div dir=3D"ltr">Hi Cecy,<div><br></div><div><a href=3D"http://scottwhu=
dson.com/" target=3D"_blank">Scott Hudson</a> expressed interest in giving =
a talk at a future Refresh if you need speakers. As his former coworker and=
boss I can vouch for his ability to talk in front of groups. I&#39;m sure =
he has some interesting things he could speak about.</div><div><br clear=3D=
"all"><div><div data-smartmail=3D"gmail_signature"><div>--</div><span style=
=3D"font-size:x-small">Dan DeFelippi<br><a href=3D"tel:%2B1.585.466.4747" v=
alue=3D"+15854664747" target=3D"_blank">+1.585.466.4747</a><br></span><a hr=
ef=3D"http://driverdan.com/" target=3D"_blank"><span style=3D"font-size:x-s=
mall">http://driverdan.com</span></a><span style=3D"font-size:x-small"><br>=
Follow me on Twitter at=C2=A0</span><a href=3D"http://twitter.com/ExpertDan=
" target=3D"_blank"><span style=3D"font-size:x-small">@ExpertDan</span></a>=
<br></div></div>
</div></div>
</blockquote></div><br></div></blockquote></div></div></div></div></div><sp=
an><font color=3D"#888888"><div dir=3D"ltr">-- <br></div><div data-smartmai=
l=3D"gmail_signature"><div dir=3D"ltr">Scott Hudson<div>Software Engineer<d=
iv><a href=3D"http://scottwhudson.com" target=3D"_blank">scottwhudson.com</=
a></div></div></div></div>
</font></span></blockquote></div><br></div></blockquote></div><div dir=3D"l=
tr">-- <br></div><div data-smartmail=3D"gmail_signature"><div dir=3D"ltr">S=
cott Hudson<div>Software Engineer<div><a href=3D"http://scottwhudson.com">s=
cottwhudson.com</a></div></div></div></div>

--001a113e5f9e3d2b9f0537aed900--
