Delivered-To: cecy@girldevelopit.com
Received: by 10.200.44.83 with SMTP id e19csp718626qta;
Mon, 16 May 2016 08:39:00 -0700 (PDT)
X-Received: by 10.37.10.4 with SMTP id 4mr14770893ybk.160.1463413140386;
Mon, 16 May 2016 08:39:00 -0700 (PDT)
Return-Path: <kendra.helman@galvanize.com>
Received: from mail-qk0-x231.google.com (mail-qk0-x231.google.com. [2607:f8b0:400d:c09::231])
by mx.google.com with ESMTPS id h7si7032490ybc.60.2016.05.16.08.39.00
for <cecy@girldevelopit.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Mon, 16 May 2016 08:39:00 -0700 (PDT)
Received-SPF: pass (google.com: domain of kendra.helman@galvanize.com designates 2607:f8b0:400d:c09::231 as permitted sender) client-ip=2607:f8b0:400d:c09::231;
Authentication-Results: mx.google.com;
dkim=pass header.i=@galvanize-com.20150623.gappssmtp.com;
spf=pass (google.com: domain of kendra.helman@galvanize.com designates 2607:f8b0:400d:c09::231 as permitted sender) smtp.mailfrom=kendra.helman@galvanize.com
Received: by mail-qk0-x231.google.com with SMTP id n62so86774957qkc.2
for <cecy@girldevelopit.com>; Mon, 16 May 2016 08:39:00 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=galvanize-com.20150623.gappssmtp.com; s=20150623;
h=mime-version:in-reply-to:references:from:date:message-id:subject:to
:cc;
bh=EI8OJXmmkr8kujFC+qfd9o6zmMkmL1ETNlfHyIllRa0=;
b=zOQSnzTaB1WnCyNfrcoNY03oflN3Ic1NWQLxCpMkkgiCT+RRDMA4Bi7feiAdk9U0M5
Eb+1T7Fu4mR87joODa265+daBalk+CLB0kbzexCu8MRT+FzYTdcLhJzWI0N/Vv3CUYSM
qdr2Gcvp33nIFmkowfNO+2OvsCRP/MIPkgDv0uOpnZQkzxkXjR54tUcFFk2pxseqHTtf
8cbPZdOsVq7Sre5TGuvMhIu/mH9eGI88g5D5f8iDTcHgoJayotxmBA4u+ExApIcDTDSz
SsmXeEZec4S6KhgxDj5HePy1JDVM47UV4u6OdtVtot3BbiukgU+YroHg3poLdgKYITBq
blvA==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:in-reply-to:references:from:date
:message-id:subject:to:cc;
bh=EI8OJXmmkr8kujFC+qfd9o6zmMkmL1ETNlfHyIllRa0=;
b=G0qjN9zEglGeUk3GCP7bpqDJ5oLCGtAOTFGwFNQ9w2X2LQs45VXoZ/9FrDvo+W1Xhk
BFSZ6PGpcbiOV9QgfwxzC9c3bQalpfychfE+Ec4ie8KGtkL6zzkXxm3KWUjAVTIAI+rT
FSOjMlb0+OFTYUrZjoU5h9JaoQYVgImU8Vgqxrsp90dBWesVj5Hb6oH2Imc9OXsOYm7U
EyUOi1j/nOWYS8Q9WtzBI3duqn3TvtTCA69JB98oCqTbRQz7Xjbq0HqGaxUnoOXud4Lg
bb3p6VjhSVzTldTgsgYQJI+rZZYINKPb6LiPfbj6qJ5WF6sjHKVXzNLJ1VXSdlFJ4512
25Og==
X-Gm-Message-State: AOPr4FWJEKnLpiid+cHidPO6tDOhD0Kd6gsx32ClqoEMF1n2XE2vEUy/FKiJKZERBF4WwByKvIlTBS+5sDoMWIjn
X-Received: by 10.55.74.141 with SMTP id x135mr31877513qka.20.1463413140042;
Mon, 16 May 2016 08:39:00 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.55.140.131 with HTTP; Mon, 16 May 2016 08:38:20 -0700 (PDT)
In-Reply-To: <CACqmxF8iD3+PH=EZZ0yBe2A5N3bt4JsDxre4TxX-cP393begFg@mail.gmail.com>
References: <CACqmxF-2NP+xYisSg1B3g2A7vAgeio+6t3rW0BcB+d=OZhdbfA@mail.gmail.com>
<CAGX=LNQJsJObGnUB+GNHakZL_B5=u1smvk1y-FBahUjY0nH_Ag@mail.gmail.com>
<CAKn_A5sCRfTnSrtP9jkVu3LqXP+SkGt9eRVA67r9kXOsxrr9+Q@mail.gmail.com> <CACqmxF8iD3+PH=EZZ0yBe2A5N3bt4JsDxre4TxX-cP393begFg@mail.gmail.com>
From: Kendra Helman <kendra.helman@galvanize.com>
Date: Mon, 16 May 2016 10:38:20 -0500
Message-ID: <CAGX=LNQPDJW4w2kNhoEwozJgfAmeskOJuiT0nHOi__8P1q+SWA@mail.gmail.com>
Subject: Re: Class Space for Girl Develop It
To: Cecy Correa <cecy@girldevelopit.com>
Cc: Ashley Price <ashley@girldevelopit.com>
Content-Type: multipart/alternative; boundary=001a114a7c6e5f510f0532f76cd9

--001a114a7c6e5f510f0532f76cd9
Content-Type: text/plain; charset=UTF-8

Thank you for the invite! Unfortunately, I won't be able to make it as we
have a few events that evening, as well.


*Kendra Helman*Events Manager
<http://www.galvanize.com/>
Austin | TX
678.595.7489 - Mobile

On Mon, May 16, 2016 at 10:37 AM, Cecy Correa <cecy@girldevelopit.com>
wrote:

> Here is the link with details about our OSCON happy hour, if you want to
> stop by Kendra :)
>
>
> https://www.eventbrite.com/e/austin-women-tech-happy-hour-during-oscon-tickets-25433883430
>
> Best,
>
> ---
> *@cecycorrea*
> *GDI ATX*
>
> On Mon, May 16, 2016 at 10:33 AM, Ashley Price <ashley@girldevelopit.com>
> wrote:
>
>> Hi Kendra,
>> Thank you for all the information.  This would be awesome!  We are
>> currently working with another location for our next class but would be
>> happy to touch base once we get the following one nailed down.  I don't
>> expect us to have that worked out this week as we are pretty busy with our
>> OSCON planning.  Speaking of which, I hope you can join our upcoming happy
>> hour!
>>
>> Best,
>> Ashley
>>
>>
>> On Monday, May 16, 2016, Kendra Helman <kendra.helman@galvanize.com>
>> wrote:
>>
>>> Cecy and Ashley- Your group is absolutely something we can accommodate!
>>> We typically host meetups in our classroom space.  Each classroom can hold
>>> 30 people classroom style and all have a screen and projector.  We also
>>> have campus wide WIFI for guests.
>>> We do have on-site parking but I usually recommend street parking, the
>>> Violet Crown garage, or the City Hall garage as they are a little cheaper
>>> than our parking. I have attached our parking rates, map of our location,
>>> and our event brochure. Please let me know if you have any any questions!
>>>
>>>
>>> *Kendra Helman*Events Manager
>>> <http://www.galvanize.com/>
>>> Austin | TX
>>> 678.595.7489 - Mobile
>>>
>>> On Fri, May 13, 2016 at 12:49 PM, Cecy Correa <cecy@girldevelopit.com>
>>> wrote:
>>>
>>>> Hi Kendra,
>>>>
>>>> Thanks so much for reaching out to Girl Develop It and graciously
>>>> offering us your space for our events / classes.
>>>>
>>>> Our classes are typically small (10 - 20 max). All we need is a
>>>> projector or large screen where we can plug into for slides, and wifi :) Is
>>>> that something you think you can accommodate?
>>>>
>>>> Not sure what the parking situation is around Galvanize. While free
>>>> parking is not a requirement for us, we certainly would like to know what
>>>> options are available for students to park.
>>>>
>>>> I am cc'ing my co-chapter leader Ashley, who also organizes classes.
>>>>
>>>> Let us know! I'd love to see some pictures, if you have any.
>>>>
>>>> Best,
>>>>
>>>> ---
>>>> *@cecycorrea*
>>>> *GDI ATX*
>>>>
>>>
>>>
>

--001a114a7c6e5f510f0532f76cd9
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Thank you for the invite! Unfortunately, I won&#39;t be ab=
le to make it as we have a few events that evening, as well.</div><div clas=
s=3D"gmail_extra"><br clear=3D"all"><div><div class=3D"gmail_signature"><di=
v dir=3D"ltr"><table width=3D"350" border=3D"0" cellpadding=3D"0" cellspaci=
ng=3D"0" style=3D"color:rgb(136,136,136);font-size:12.8px;font-family:Times=
"><tbody><tr><td width=3D"309" valign=3D"top" style=3D"padding:0px"><span s=
tyle=3D"margin-top:0px;margin-bottom:0px;font-family:&#39;Helvetica Neue&#3=
9;,Helvetica,Arial,sans-serif"><font color=3D"#6e6e6e"><span style=3D"font-=
size:14.6667px"><b>Kendra Helman<br></b></span></font>Events Manager<br><fo=
nt color=3D"#acaeb1"><span style=3D"font-size:9pt"><a href=3D"http://www.ga=
lvanize.com/" style=3D"color:rgb(17,85,204)" target=3D"_blank"><img src=3D"=
https://docs.google.com/uc?export=3Ddownload&amp;id=3D0B-CoKWg2NV9aZFJkMXFZ=
NVpMN2s&amp;revid=3D0B-CoKWg2NV9aL05jajdnOUFua3dIYkllQzNxNE9ocGduL3pvPQ" wi=
dth=3D"96" height=3D"36"></a></span></font><br></span></td></tr><tr><td val=
ign=3D"top" style=3D"padding:0px"><span style=3D"color:rgb(156,158,161);fon=
t-family:&#39;Helvetica Neue&#39;,Helvetica,Arial,sans-serif;font-size:9pt"=
>Austin | TX<br></span><span style=3D"color:rgb(156,158,161);font-family:&#=
39;Helvetica Neue&#39;,Helvetica,Arial,sans-serif;font-size:12px">678.595.7=
489=C2=A0-=C2=A0</span><span style=3D"color:rgb(125,126,129);font-family:&#=
39;Helvetica Neue&#39;,Helvetica,Arial,sans-serif;font-size:12px">Mobile</s=
pan></td></tr></tbody></table></div></div></div>
<br><div class=3D"gmail_quote">On Mon, May 16, 2016 at 10:37 AM, Cecy Corre=
a <span dir=3D"ltr">&lt;<a href=3D"mailto:cecy@girldevelopit.com" target=3D=
"_blank">cecy@girldevelopit.com</a>&gt;</span> wrote:<br><blockquote class=
=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padd=
ing-left:1ex"><div dir=3D"ltr">Here is the link with details about our OSCO=
N happy hour, if you want to stop by Kendra :)=C2=A0<div><br></div><div><a =
href=3D"https://www.eventbrite.com/e/austin-women-tech-happy-hour-during-os=
con-tickets-25433883430" target=3D"_blank">https://www.eventbrite.com/e/aus=
tin-women-tech-happy-hour-during-oscon-tickets-25433883430</a><br></div><di=
v><br></div><div>Best,</div></div><div class=3D"gmail_extra"><br clear=3D"a=
ll"><div><div><div dir=3D"ltr"><font color=3D"#999999">---</font><div><font=
color=3D"#999999"><i>@cecycorrea</i></font></div><div><font color=3D"#9999=
99"><i>GDI ATX</i></font></div></div></div></div>
<br><div class=3D"gmail_quote"><span class=3D"">On Mon, May 16, 2016 at 10:=
33 AM, Ashley Price <span dir=3D"ltr">&lt;<a href=3D"mailto:ashley@girldeve=
lopit.com" target=3D"_blank">ashley@girldevelopit.com</a>&gt;</span> wrote:=
<br></span><div><div class=3D"h5"><blockquote class=3D"gmail_quote" style=
=3D"margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-left:1ex">Hi Kendr=
a,<div>Thank you for all the information.=C2=A0 This would be awesome!=C2=
=A0 We are currently working with another location for our next class but w=
ould be happy to touch base once we get the following one nailed down.=C2=
=A0 I don&#39;t expect us to have that worked out this week as we are prett=
y busy with our OSCON planning.=C2=A0 Speaking of which, I hope you can joi=
n our upcoming=C2=A0happy hour!=C2=A0</div><div><br></div><div>Best,</div><=
div>Ashley<div><div><br><br>On Monday, May 16, 2016, Kendra Helman &lt;<a h=
ref=3D"mailto:kendra.helman@galvanize.com" target=3D"_blank">kendra.helman@=
galvanize.com</a>&gt; wrote:<br><blockquote class=3D"gmail_quote" style=3D"=
margin:0 0 0 .8ex;border-left:1px #ccc solid;padding-left:1ex"><div dir=3D"=
ltr">Cecy and Ashley- Your group is absolutely something we can accommodate=
! We typically host meetups in our classroom space.=C2=A0 Each classroom ca=
n hold 30 people classroom style and all have a screen and projector.=C2=A0=
We also have campus wide WIFI for guests.<div>We do have on-site parking b=
ut I usually recommend street parking, the Violet Crown garage, or the City=
Hall garage as they are a little cheaper than our parking. I have attached=
our parking rates, map of our location, and our event brochure. Please let=
me know if you have any any questions!</div></div><div class=3D"gmail_extr=
a"><br clear=3D"all"><div><div><div dir=3D"ltr"><table width=3D"350" border=
=3D"0" cellpadding=3D"0" cellspacing=3D"0" style=3D"color:rgb(136,136,136);=
font-size:12.8px;font-family:Times"><tbody><tr><td width=3D"309" valign=3D"=
top" style=3D"padding:0px"><span style=3D"margin-top:0px;margin-bottom:0px;=
font-family:&#39;Helvetica Neue&#39;,Helvetica,Arial,sans-serif"><font colo=
r=3D"#6e6e6e"><span style=3D"font-size:14.6667px"><b>Kendra Helman<br></b><=
/span></font>Events Manager<br><font color=3D"#acaeb1"><span style=3D"font-=
size:9pt"><a href=3D"http://www.galvanize.com/" style=3D"color:rgb(17,85,20=
4)" target=3D"_blank"><img src=3D"https://docs.google.com/uc?export=3Ddownl=
oad&amp;id=3D0B-CoKWg2NV9aZFJkMXFZNVpMN2s&amp;revid=3D0B-CoKWg2NV9aL05jajdn=
OUFua3dIYkllQzNxNE9ocGduL3pvPQ" width=3D"96" height=3D"36"></a></span></fon=
t><br></span></td></tr><tr><td valign=3D"top" style=3D"padding:0px"><span s=
tyle=3D"color:rgb(156,158,161);font-family:&#39;Helvetica Neue&#39;,Helveti=
ca,Arial,sans-serif;font-size:9pt">Austin | TX<br></span><span style=3D"col=
or:rgb(156,158,161);font-family:&#39;Helvetica Neue&#39;,Helvetica,Arial,sa=
ns-serif;font-size:12px"><a href=3D"tel:678.595.7489" value=3D"+16785957489=
" target=3D"_blank">678.595.7489</a>=C2=A0-=C2=A0</span><span style=3D"colo=
r:rgb(125,126,129);font-family:&#39;Helvetica Neue&#39;,Helvetica,Arial,san=
s-serif;font-size:12px">Mobile</span></td></tr></tbody></table></div></div>=
</div>
<br><div class=3D"gmail_quote">On Fri, May 13, 2016 at 12:49 PM, Cecy Corre=
a <span dir=3D"ltr">&lt;<a>cecy@girldevelopit.com</a>&gt;</span> wrote:<br>=
<blockquote class=3D"gmail_quote" style=3D"margin:0 0 0 .8ex;border-left:1p=
x #ccc solid;padding-left:1ex"><div dir=3D"ltr">Hi Kendra,<div><br></div><d=
iv>Thanks so much for reaching out to Girl Develop It and graciously offeri=
ng us your space for our events / classes.</div><div><br></div><div>Our cla=
sses are typically small (10 - 20 max). All we need is a projector or large=
screen where we can plug into for slides, and wifi :) Is that something yo=
u think you can accommodate?</div><div><br></div><div>Not sure what the par=
king situation is around Galvanize. While free parking is not a requirement=
for us, we certainly would like to know what options are available for stu=
dents to park.</div><div><br></div><div>I am cc&#39;ing my co-chapter leade=
r Ashley, who also organizes classes.</div><div><br></div><div>Let us know!=
I&#39;d love to see some pictures, if you have any.</div><div><br></div><d=
iv>Best,</div><div><br clear=3D"all"><div><div><div dir=3D"ltr"><font color=
=3D"#999999">---</font><div><font color=3D"#999999"><i>@cecycorrea</i></fon=
t></div><div><font color=3D"#999999"><i>GDI ATX</i></font></div></div></div=
></div>
</div></div>
</blockquote></div><br></div>
</blockquote></div></div></div>
</blockquote></div></div></div><br></div>
</blockquote></div><br></div>

--001a114a7c6e5f510f0532f76cd9--
