Delivered-To: cecycorrea@gmail.com
Received: by 10.159.54.171 with SMTP id p40csp1701913uap;
Mon, 6 Jun 2016 17:33:27 -0700 (PDT)
X-Received: by 10.202.95.68 with SMTP id t65mr10671939oib.7.1465259607766;
Mon, 06 Jun 2016 17:33:27 -0700 (PDT)
Return-Path: <stephanie.ultimatestaffing@gmail.com>
Received: from mail-oi0-x244.google.com (mail-oi0-x244.google.com. [2607:f8b0:4003:c06::244])
by mx.google.com with ESMTPS id e78si3861248oib.145.2016.06.06.17.33.27
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Mon, 06 Jun 2016 17:33:27 -0700 (PDT)
Received-SPF: pass (google.com: domain of stephanie.ultimatestaffing@gmail.com designates 2607:f8b0:4003:c06::244 as permitted sender) client-ip=2607:f8b0:4003:c06::244;
Authentication-Results: mx.google.com;
dkim=pass header.i=@gmail.com;
spf=pass (google.com: domain of stephanie.ultimatestaffing@gmail.com designates 2607:f8b0:4003:c06::244 as permitted sender) smtp.mailfrom=stephanie.ultimatestaffing@gmail.com;
dmarc=pass (p=NONE dis=NONE) header.from=gmail.com
Received: by mail-oi0-x244.google.com with SMTP id x204so63990oia.0;
Mon, 06 Jun 2016 17:33:27 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=gmail.com; s=20120113;
h=from:to:references:in-reply-to:subject:date:message-id:mime-version
:thread-index:content-language;
bh=d1q6YKkLMQkKgBNSb9g/laeScgHhZ5OIa1NsagFRBQ4=;
b=TEbGqvIIAweu2WIRNK1yinw/fKzXgI5iyrkRmZJvafQBWvBvNHKkesyfS7LArTn3Ol
3bXvANR4OXMgbVzpuneAbx3TvGzGiMg+PTYyw+mflfge/00HBSQQaj7/aQ4b7aQ5tkzg
YpMgzF04Z2vThj7YehZu5yVWWx1hev9VHXH+dViRtEKGDhVxGZk9EFxFjjgr4EMqC6kc
YJRwpoDKCCTX2uaQ9w9fRB3Zd9sJno3Hpky19EPmMK0A55ulT6ek+M81wufXG6HsYk2N
VZ8xUYwlSzQv45/lLf21Hqu+kwyHYJiDw2iTMAlfy7gBQvykNtK32G8E8lj03DjwnMMw
nMDQ==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:from:to:references:in-reply-to:subject:date
:message-id:mime-version:thread-index:content-language;
bh=d1q6YKkLMQkKgBNSb9g/laeScgHhZ5OIa1NsagFRBQ4=;
b=bY2XKWxO25ATJwcM91qZn7oRrra7jO2reWiQ0kMluwasbwxtwuOL7NJVPn5idRJHbJ
zSMniq+9icyH4M7UxHQtU2wm4rFr2Y7e8qZd1NUahNw2fnI+vrVt8GRlZjczU3Sfuijb
n7JFWxgOENosWxXtXGyJz7O+NL4sVbIt1ATUMoIZkw2/MGdHkV2gM7II8dqfsoO5B+aP
2h6SohE+NdM9lvNHB54tDsYRUn3vWWgxvqLiaCTezspCN2hFVazvSp3vlI9BF2mbPBj/
eigpk/W1rICdkMtQPRGtR/1hjdQYMCDOBoiKk/UaNaQ4KEt5C794wzLp4GarkD3kiT1i
1y0A==
X-Gm-Message-State: ALyK8tLmhBZ8eIer8pKcVpAuN5sKFf43ekBRLcPfsta1AUgf9l4eagFzE7fDyLf+oj5bXQ==
X-Received: by 10.157.61.197 with SMTP id l63mr10915420otc.48.1465259606977;
Mon, 06 Jun 2016 17:33:26 -0700 (PDT)
Return-Path: <stephanie.ultimatestaffing@gmail.com>
Received: from Stephanie ([2602:306:cd9b:6450:55f7:104a:896f:1cd0])
by smtp.gmail.com with ESMTPSA id w16sm11673294oie.18.2016.06.06.17.33.24
(version=TLS1_2 cipher=ECDHE-RSA-AES128-SHA bits=128/128);
Mon, 06 Jun 2016 17:33:26 -0700 (PDT)
From: Stephanie <stephanie.ultimatestaffing@gmail.com>
X-Google-Original-From: "Stephanie" <Stephanie.ultimatestaffing@gmail.com>
To: "Stephanie" <Stephanie.ultimatestaffing@gmail.com>
References: <002d01d1b6b9$5c02fe00$1408fa00$@gmail.com> <009101d1b6bd$734ee700$59ecb500$@gmail.com> <002001d1b6e2$c536c4a0$4fa44de0$@gmail.com> <001401d1c040$dd0a1340$971e39c0$@gmail.com> <000401d1c052$8c8babb0$a5a30310$@gmail.com> <000b01d1c052$d36073e0$7a215ba0$@gmail.com>
In-Reply-To: <000b01d1c052$d36073e0$7a215ba0$@gmail.com>
Subject: Full Stack / UI Developer role with a young, dynamic, cutting edge company in the Austin, TX area!
Date: Mon, 6 Jun 2016 20:28:46 -0400
Message-ID: <001201d1c053$8f399830$adacc890$@gmail.com>
MIME-Version: 1.0
Content-Type: multipart/alternative;
boundary="----=_NextPart_000_0013_01D1C032.0829CCF0"
X-Mailer: Microsoft Outlook 15.0
Thread-Index: AQGEZKSZOn9nlqm4aXvsk7J6X/+2ZQFVJnb/AhrrDAICthX4oAJQk9+EAkJA7oWgIhWhwA==
Content-Language: en-us

This is a multipart message in MIME format.

------=_NextPart_000_0013_01D1C032.0829CCF0
Content-Type: text/plain;
charset="us-ascii"
Content-Transfer-Encoding: 7bit

Good evening,



I am a recruiter and I'm working on an exciting opportunity that I thought
you might be interested in hearing about.  Our client, a well-funded
start-up company that is poised for tremendous growth, is looking for a
creative Full Stack / UI Developer to join their team.  This is your
opportunity to come in on the ground floor of a dynamic, young company, work
on cutting edge technology and be creative!  The company is offering a very
competitive salary for this role, along with an excellent benefits package.



Our client is seeking a highly-motivated Full Stack / UI Developer who
enjoys working in a fast-paced environment.  You enjoy engaging in
passionate discussions with talented team members who are passionate about
their work.  You have built applications using Java based stacks such as
Spring MVC, and working knowledge of JavaScript, HTML5, Document Object
Model, CSS3 and latest JavaScript standards.  You are experienced in
developing consumer facing web applications using Ajax.  You are passionate
about developing well designed, elegant web and / or mobile apps and you are
genuinely excited about technology, have a strong interest in learning and
playing with the latest technologies.



This is an urgent need for the client and the hiring manager is in the
process of reviewing resumes and scheduling interviews.  If this is
something of interest to you, please send your resume as a Word attachment
and let's schedule a time to discuss this exciting opportunity.  Oh, and
please send along links to your portfolio of sites that you've created. We'd
love to see a sample of your work!



Qualifications

*	Bachelor's degree - preferably in computer science or a similar
degree.

*	5+ year's professional experience in software development using
JavaScript and/or Java.
*	Proficiency in Front-end Coding and Design (JavaScript, CSS, HTML,
HTTP, jQuery, and libraries or frameworks such as Bootstrap, Angular)

*	Experience translating design mockups and prototypes into working
application designs.
*	Have developed or supported an operationally critical web service.
*	Motivated to drive tasks to completion and take ownership of
projects.
*	Experience with Unit Testing with at least one testing framework
like BrowserStack, Angular Test Scripts.
*	Experience with Load Runner or Load Impact would be a plus
*	Knowledge in SQL Server database and stored procedures
*	Experience and understanding of service oriented architectures
(SOA), Object Oriented Design/Development, Continuous Integration is
required
*	Demonstrated passion for user experience design and improving
usability.
*	Experience working in a fast paced agile SDLC environment using
Scrum methodology





Best regards,



Stephanie Budin

Ultimate Staffing, Inc.

Email:   <mailto:Stephanie.ultimatestaffing@gmail.com>
Stephanie.ultimatestaffing@gmail.com

Mobile: (561) 342-1868

<http://www.linkedin.com/in/stephaniebudin>
www.linkedin.com/in/stephaniebudin




------=_NextPart_000_0013_01D1C032.0829CCF0
Content-Type: text/html;
charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" =
xmlns:o=3D"urn:schemas-microsoft-com:office:office" =
xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" =
xmlns=3D"http://www.w3.org/TR/REC-html40"><head><meta =
http-equiv=3DContent-Type content=3D"text/html; =
charset=3Dus-ascii"><meta name=3DGenerator content=3D"Microsoft Word 15 =
(filtered medium)"><style><!--
/* Font Definitions */
@font-face
{font-family:"Cambria Math";
panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
{font-family:Calibri;
panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
{margin:0in;
margin-bottom:.0001pt;
font-size:11.0pt;
font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
{mso-style-priority:99;
color:#0563C1;
text-decoration:underline;}
a:visited, span.MsoHyperlinkFollowed
{mso-style-priority:99;
color:#954F72;
text-decoration:underline;}
span.EmailStyle17
{mso-style-type:personal;
font-family:"Calibri",sans-serif;
color:windowtext;}
span.EmailStyle18
{mso-style-type:personal;
font-family:"Calibri",sans-serif;
color:#1F497D;}
span.EmailStyle19
{mso-style-type:personal;
font-family:"Calibri",sans-serif;
color:#1F497D;}
span.EmailStyle20
{mso-style-type:personal;
font-family:"Calibri",sans-serif;
color:#1F497D;}
span.EmailStyle21
{mso-style-type:personal;
font-family:"Calibri",sans-serif;
color:#1F497D;}
span.EmailStyle22
{mso-style-type:personal;
font-family:"Calibri",sans-serif;
color:#1F497D;}
span.EmailStyle23
{mso-style-type:personal-reply;
font-family:"Calibri",sans-serif;
color:#1F497D;}
.MsoChpDefault
{mso-style-type:export-only;
font-size:10.0pt;}
@page WordSection1
{size:8.5in 11.0in;
margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
{page:WordSection1;}
/* List Definitions */
@list l0
{mso-list-id:409499995;
mso-list-template-ids:-1325738952;}
@list l0:level1
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l0:level2
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l0:level3
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l0:level4
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l0:level5
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l0:level6
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l0:level7
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l0:level8
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l0:level9
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l1
{mso-list-id:726950997;
mso-list-template-ids:-1115884568;}
@list l1:level1
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l1:level2
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l1:level3
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l1:level4
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l1:level5
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l1:level6
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l1:level7
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l1:level8
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l1:level9
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l2
{mso-list-id:1133140480;
mso-list-template-ids:-523309814;}
@list l2:level1
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l2:level2
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l2:level3
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l2:level4
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l2:level5
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l2:level6
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l2:level7
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l2:level8
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l2:level9
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l3
{mso-list-id:1233850290;
mso-list-template-ids:-1046442262;}
@list l3:level1
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l3:level2
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l3:level3
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l3:level4
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l3:level5
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l3:level6
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l3:level7
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l3:level8
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l3:level9
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l4
{mso-list-id:1934241682;
mso-list-template-ids:1851533894;}
@list l4:level1
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l4:level2
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l4:level3
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l4:level4
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l4:level5
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l4:level6
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l4:level7
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l4:level8
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l4:level9
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l5
{mso-list-id:2071734107;
mso-list-template-ids:83129620;}
@list l5:level1
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l5:level2
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l5:level3
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:1.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l5:level4
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l5:level5
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:2.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l5:level6
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l5:level7
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:3.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l5:level8
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.0in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
@list l5:level9
{mso-level-number-format:bullet;
mso-level-text:\F0B7;
mso-level-tab-stop:4.5in;
mso-level-number-position:left;
text-indent:-.25in;
mso-ansi-font-size:10.0pt;
font-family:Symbol;}
ol
{margin-bottom:0in;}
ul
{margin-bottom:0in;}
--></style><!--[if gte mso 9]><xml>
<o:shapedefaults v:ext=3D"edit" spidmax=3D"1026" />
</xml><![endif]--><!--[if gte mso 9]><xml>
<o:shapelayout v:ext=3D"edit">
<o:idmap v:ext=3D"edit" data=3D"1" />
</o:shapelayout></xml><![endif]--></head><body lang=3DEN-US =
link=3D"#0563C1" vlink=3D"#954F72"><div class=3DWordSection1><p =
class=3DMsoNormal><span style=3D'color:#1F4E79'>Good </span><span =
style=3D'color:#1F497D'>evening</span><span =
style=3D'color:#1F4E79'>,<o:p></o:p></span></p><p =
class=3DMsoNormal><span =
style=3D'color:#1F4E79'><o:p>&nbsp;</o:p></span></p><p =
class=3DMsoNormal><span style=3D'color:#1F497D'>I am a recruiter and =
I&#8217;m working on an exciting opportunity that I thought you might be =
interested in hearing about.&nbsp; Our client, a well-funded start-up =
</span><span style=3D'color:#1F4E79'>company</span><span =
style=3D'color:#1F497D'> that is poised for tremendous growth, is =
looking for a </span><span style=3D'color:#1F4E79'>creative Full Stack / =
UI Developer to join their team</span><span =
style=3D'color:#1F497D'>.&nbsp; This is your opportunity to come in on =
the ground floor of a dynamic, young company, work on cutting edge =
technology and be creative!&nbsp; The company is offering a very =
competitive salary for this role, along with an excellent benefits =
package.</span><span style=3D'color:#1F4E79'><o:p></o:p></span></p><p =
class=3DMsoNormal><span =
style=3D'color:#1F4E79'><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'mso-margin-top-alt:5.25pt;margin-right:0in;margin-bottom:5.25pt;=
margin-left:0in;line-height:16.8pt;background:white'><span lang=3DEN =
style=3D'color:#1F497D'>O</span><span lang=3DEN =
style=3D'color:#1F4E79'>ur client is seeking a highly-motivated Full =
Stack / UI Developer who enjoys working in a fast-paced =
environment.&nbsp; You enjoy engaging in passionate discussions with =
talented team members who are passionate about their work.&nbsp; You =
have built applications using Java based stacks such as Spring MVC, and =
working knowledge of JavaScript, HTML5, Document Object Model, CSS3 and =
latest JavaScript standards.&nbsp; You are experienced in developing =
consumer facing web applications using Ajax.&nbsp; You are passionate =
about developing well designed, elegant web and / or mobile apps and you =
are genuinely excited about technology, have a strong interest in =
learning and playing with the latest technologies.&nbsp; =
<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'mso-margin-top-alt:5.25pt;margin-right:0in;margin-bottom:5.25pt;=
margin-left:0in;line-height:16.8pt;background:white'><span lang=3DEN =
style=3D'color:#1F4E79'><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'mso-margin-top-alt:5.25pt;margin-right:0in;margin-bottom:5.25pt;=
margin-left:0in;line-height:16.8pt;background:white'><span lang=3DEN =
style=3D'color:#1F4E79'>This is an urgent need for the client and the =
hiring manager is in the process of reviewing resumes and scheduling =
interviews.&nbsp; If this is something of interest to you, please send =
your resume as a Word attachment and let&#8217;s schedule a time to =
discuss this exciting opportunity.&nbsp; Oh, and please send along links =
to your portfolio of sites that you&#8217;ve created. We&#8217;d love to =
see a sample of your work!<o:p></o:p></span></p><p class=3DMsoNormal =
style=3D'mso-margin-top-alt:5.25pt;margin-right:0in;margin-bottom:5.25pt;=
margin-left:.5in;line-height:16.8pt;background:white'><span lang=3DEN =
style=3D'color:#1F4E79'><o:p>&nbsp;</o:p></span></p><p class=3DMsoNormal =
style=3D'line-height:12.0pt;background:white'><span lang=3DEN =
style=3D'color:#1F4E79'>Qualifications <o:p></o:p></span></p><ul =
style=3D'margin-top:0in' type=3Ddisc><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l2 level1 lfo3;background:white'><span =
lang=3DEN>Bachelor&#8217;s degree &#8211; preferably in computer science =
or a similar degree.<o:p></o:p></span></li></ul><ul =
style=3D'margin-top:0in' type=3Ddisc><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l0 level1 lfo6;background:white'><span lang=3DEN>5+ =
year&#8217;s professional experience in software development using =
JavaScript and/or Java.<o:p></o:p></span></li><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l0 level1 lfo6;background:white'><span =
lang=3DEN>Proficiency in Front-end Coding and Design (JavaScript, CSS, =
HTML, HTTP, jQuery, and libraries or frameworks such as Bootstrap, =
Angular)<o:p></o:p></span></li></ul><ul style=3D'margin-top:0in' =
type=3Ddisc><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l1 level1 lfo9;background:white'><span =
lang=3DEN>Experience translating design mockups and prototypes into =
working application designs.<o:p></o:p></span></li><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l1 level1 lfo9;background:white'><span lang=3DEN>Have =
developed or supported an operationally critical web =
service.<o:p></o:p></span></li><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l1 level1 lfo9;background:white'><span =
lang=3DEN>Motivated to drive tasks to completion and take ownership of =
projects.<o:p></o:p></span></li><li class=3DMsoNormal =
style=3D'color:#1F4E79;mso-margin-top-alt:auto;mso-margin-bottom-alt:auto=
;mso-list:l1 level1 lfo9'>Experience with Unit Testing with at least one =
testing framework like BrowserStack, Angular Test =
Scripts.<o:p></o:p></li><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l1 level1 lfo9;background:white'><span =
lang=3DEN>Experience with Load Runner or Load Impact would be a =
plus<o:p></o:p></span></li><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l1 level1 lfo9;background:white'>Knowledge in SQL =
Server database and stored procedures<span =
lang=3DEN><o:p></o:p></span></li><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l1 level1 lfo9;background:white'>Experience and =
understanding of service oriented architectures (SOA), Object Oriented =
Design/Development, Continuous Integration is required<span =
lang=3DEN><o:p></o:p></span></li><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l1 level1 lfo9;background:white'><span =
lang=3DEN>Demonstrated passion for user experience design and improving =
usability.<o:p></o:p></span></li><li class=3DMsoNormal =
style=3D'color:#1F4E79;margin-top:5.25pt;margin-bottom:5.25pt;line-height=
:16.8pt;mso-list:l1 level1 lfo9;background:white'><span =
lang=3DEN>Experience working in a fast paced agile SDLC environment =
using Scrum methodology<o:p></o:p></span></li></ul><p =
class=3DMsoNormal><b><span =
style=3D'color:#1F4E79'><o:p>&nbsp;</o:p></span></b></p><p =
class=3DMsoNormal><span =
style=3D'color:#1F4E79'><o:p>&nbsp;</o:p></span></p><p =
class=3DMsoNormal><span style=3D'color:#1F4E79'>Best =
regards,<o:p></o:p></span></p><p class=3DMsoNormal><span =
style=3D'color:#1F4E79'><o:p>&nbsp;</o:p></span></p><p =
class=3DMsoNormal><span style=3D'color:#1F4E79'>Stephanie =
Budin<o:p></o:p></span></p><p class=3DMsoNormal><span =
style=3D'color:#1F4E79'>Ultimate Staffing, Inc.<o:p></o:p></span></p><p =
class=3DMsoNormal><span style=3D'color:#1F4E79'>Email:&nbsp; <a =
href=3D"mailto:Stephanie.ultimatestaffing@gmail.com"><span =
style=3D'color:#1F4E79'>Stephanie.ultimatestaffing@gmail.com</span></a><o=
:p></o:p></span></p><p class=3DMsoNormal><span =
style=3D'color:#1F4E79'>Mobile: (561) 342-1868<o:p></o:p></span></p><p =
class=3DMsoNormal><span lang=3DEN style=3D'color:#1F4E79'><a =
href=3D"http://www.linkedin.com/in/stephaniebudin"><span =
style=3D'color:#1F4E79'>www.linkedin.com/in/stephaniebudin</span></a><o:p=
></o:p></span></p><p class=3DMsoNormal><span =
style=3D'color:#1F4E79'><o:p>&nbsp;</o:p></span></p></div></body></html>
------=_NextPart_000_0013_01D1C032.0829CCF0--
