Delivered-To: cecycorrea@gmail.com
Received: by 10.182.217.6 with SMTP id ou6csp564730obc;
Mon, 1 Aug 2016 14:38:26 -0700 (PDT)
X-Received: by 10.176.3.116 with SMTP id 107mr27320679uat.131.1470087505965;
Mon, 01 Aug 2016 14:38:25 -0700 (PDT)
Return-Path: <nicole.hartig@generalassemb.ly>
Received: from mail-ua0-x22e.google.com (mail-ua0-x22e.google.com. [2607:f8b0:400c:c08::22e])
by mx.google.com with ESMTPS id 63si7911012uak.118.2016.08.01.14.38.25
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Mon, 01 Aug 2016 14:38:25 -0700 (PDT)
Received-SPF: pass (google.com: domain of nicole.hartig@generalassemb.ly designates 2607:f8b0:400c:c08::22e as permitted sender) client-ip=2607:f8b0:400c:c08::22e;
Authentication-Results: mx.google.com;
dkim=pass header.i=@generalassemb-ly.20150623.gappssmtp.com;
spf=pass (google.com: domain of nicole.hartig@generalassemb.ly designates 2607:f8b0:400c:c08::22e as permitted sender) smtp.mailfrom=nicole.hartig@generalassemb.ly
Received: by mail-ua0-x22e.google.com with SMTP id k90so115792463uak.0
for <cecycorrea@gmail.com>; Mon, 01 Aug 2016 14:38:25 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=generalassemb-ly.20150623.gappssmtp.com; s=20150623;
h=mime-version:from:date:message-id:subject:to;
bh=Ep+GD4PW0JxfCdnB6zZliqtve1mql8PF8vClNP4HdQM=;
b=MAYUWAxSD4YT9engLsXkAcAMZaccYr1gq5Y57LuOVLihjiABWNZqUWNJsKj4AMISns
z1jbnr8aRuNwHN6Y33topEEL4HhZkQEdQouwDu2yuGR79y4OLWSwc784Ti1nJw+L44d7
fhLF8Gt6AQIDCsZIkOME3Rp5Fx2F2TXKEiotGBLTGWmqikD1Z/HPoZYvTVQTSkLW0p88
4Ijs5rHnIcdLjIWaOQI3PFhYNXZf3Qd4rTQLAzHkUx9CQRkjEtvio8GmmlaDKVWHCibe
8tl5FGwiy9FDPp0r0sKOeeIC8U55MvAQMSmmYOLtcQ6k8ZLLuzCgqB+ngybNhmRVTsbk
I3xg==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
bh=Ep+GD4PW0JxfCdnB6zZliqtve1mql8PF8vClNP4HdQM=;
b=kJ+ZXtqn68upn2egDDyadpaWTva66dV2ftHjYQJrFJ/tyRA1kM2bKzwD5ONId95h35
3II5O9aAiOqvss+qane1/77q0q5G69JI+wNuvRZqbx5y83N/kKnBMRrOJiTMzRBtIOQ5
nPiGOyO4mvj1JqCSWJfgaLHrRvGDst5M4Wu/62BlGDGb4yDCYN6cb51dKLDBlVe2G1gS
SqKIZVdhPqW6N5I+3w0wx/tsmo4aCs6KV3zhzLnuwFHEibGicO7FofJs+wXFR1nsRSNa
yqleK9QopPD8nd/7xk+q3LarhouOpzH57Xt7sJ/C7ShGhe+/Z0aalx5tw/NcQRHzL39N
oLtw==
X-Gm-Message-State: AEkoout82B1oA4KznyA6aW3Mb7AlMtpdBlYr0DwvqU9prSHeMWmyhAOtm1W1ufYOnZAHJbt51zUQI3D06JQqUy9Y
X-Received: by 10.176.2.114 with SMTP id 105mr28267008uas.110.1470087505408;
Mon, 01 Aug 2016 14:38:25 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.103.11.7 with HTTP; Mon, 1 Aug 2016 14:37:44 -0700 (PDT)
From: Nicole Umphress <nicole.hartig@generalassemb.ly>
Date: Mon, 1 Aug 2016 16:37:44 -0500
Message-ID: <CAEwXD4k-3uWsobW+b20_5hLsxaU3FyAbM-7F-tUsThw4hxsebg@mail.gmail.com>
Subject: Community Involvement at General Assembly
To: cecycorrea@gmail.com
Content-Type: multipart/alternative; boundary=001a113e40b88c876f0539096bf6

--001a113e40b88c876f0539096bf6
Content-Type: text/plain; charset=UTF-8

Hi Cecy,

Our sixth web development class is in week 10 out of 12 and we are putting
together a panel for them next week (during week 11) called *A Day In The
Life Of*. The panel will have developers rom a product company, an agency
and a startup/freelancer. I'd love have you come in and be the product
company representative. The panel will be on Tuesday, 8/9 from 9-10am.
Would you be interested/available to attend?

Thanks,
Nicole

--
*Nicole Umphress | Outcomes Producer + Career Coach *
General Assembly | Austin
nicoleu@ga.co | (847) 602-4400 <847-602-4400>
ga.co <http://ga.co/austin> | @GA_ATX <https://twitter.com/ga_atx>

Looking for talent? *Get in touch* <https://generalassemb.ly/talent>.

Join us August 5th for a Campus Tour
<https://generalassemb.ly/education/atx-campus-tour/austin/27882>& Happy
Hour <https://generalassemb.ly/education/ga-atx-happy-hour/11/27584>!

--001a113e40b88c876f0539096bf6
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr"><div class=3D"gmail_default" style=3D"font-family:tahoma,s=
ans-serif;font-size:small">Hi Cecy,=C2=A0</div><div class=3D"gmail_default"=
style=3D"font-family:tahoma,sans-serif;font-size:small"><br></div><div cla=
ss=3D"gmail_default" style=3D"font-family:tahoma,sans-serif;font-size:small=
">Our sixth web development class is in week 10 out of 12 and we are puttin=
g together a panel for them next week (during week 11) called=C2=A0<i>A Day=
In The Life Of</i>. The panel will have developers rom a product company, =
an agency and a startup/freelancer. I&#39;d love have you come in and be th=
e product company representative. The panel will be on Tuesday, 8/9 from 9-=
10am. Would you be interested/available to attend?=C2=A0<br clear=3D"all"><=
/div><div class=3D"gmail_default" style=3D"font-family:tahoma,sans-serif;fo=
nt-size:small"><br></div><div class=3D"gmail_default" style=3D"font-family:=
tahoma,sans-serif;font-size:small">Thanks,</div><div class=3D"gmail_default=
" style=3D"font-family:tahoma,sans-serif;font-size:small">Nicole</div><div>=
<br></div>-- <br><div class=3D"gmail_signature"><div dir=3D"ltr"><div><div =
dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"ltr"><div dir=3D"=
ltr"><div style=3D"font-size:13px"><b><font color=3D"#666666" face=3D"arial=
, helvetica, sans-serif">Nicole Umphress | Outcomes Producer + Career Coach=
=C2=A0</font></b></div><div style=3D"font-size:12.8px"><div style=3D"font-s=
ize:13px;word-wrap:break-word"><font color=3D"#666666" face=3D"arial, helve=
tica, sans-serif"><font>General Assembly</font><span style=3D"background-co=
lor:transparent">=C2=A0| Austin</span></font></div><div style=3D"font-size:=
13px;word-wrap:break-word"><font color=3D"#666666" face=3D"arial, helvetica=
, sans-serif"><a href=3D"mailto:nicoleu@ga.co" target=3D"_blank">nicoleu@ga=
.co</a>=C2=A0|=C2=A0<a href=3D"tel:847-602-4400" value=3D"+19546497671" tar=
get=3D"_blank">(847) 602-4400</a></font></div><div style=3D"font-size:13px;=
word-wrap:break-word"><font color=3D"#666666" face=3D"arial, helvetica, san=
s-serif"><a href=3D"http://ga.co/austin" target=3D"_blank">ga.co</a>=C2=A0|=
=C2=A0<a href=3D"https://twitter.com/ga_atx" target=3D"_blank">@GA_ATX</a><=
/font></div><div style=3D"color:rgb(136,136,136);font-size:13px;word-wrap:b=
reak-word"><br></div><div style=3D"word-wrap:break-word"><font face=3D"aria=
l, helvetica, sans-serif"><font color=3D"#000000">Looking for talent?</font=
><font color=3D"#888888">=C2=A0</font><a href=3D"https://generalassemb.ly/t=
alent" target=3D"_blank"><font color=3D"#000000"><b>Get in touch</b></font>=
</a><font color=3D"#888888">.</font></font></div><div style=3D"color:rgb(13=
6,136,136);word-wrap:break-word"><br></div><div style=3D"word-wrap:break-wo=
rd"><font face=3D"arial, helvetica, sans-serif"><font color=3D"#000000">Joi=
n us August 5th for a </font><a href=3D"https://generalassemb.ly/education/=
atx-campus-tour/austin/27882" target=3D"_blank"><font color=3D"#ff0000">Cam=
pus Tour</font> </a><font color=3D"#000000">&amp;=C2=A0</font><a href=3D"ht=
tps://generalassemb.ly/education/ga-atx-happy-hour/11/27584" target=3D"_bla=
nk"><font color=3D"#ff0000">Happy Hour</font></a><font color=3D"#000000">!=
=C2=A0</font></font></div></div></div></div></div></div></div></div></div><=
/div>
</div>

--001a113e40b88c876f0539096bf6--
