Delivered-To: cecycorrea@gmail.com
Received: by 10.159.54.171 with SMTP id p40csp396142uap;
Fri, 10 Jun 2016 11:22:10 -0700 (PDT)
X-Received: by 10.36.123.77 with SMTP id q74mr763547itc.44.1465582930470;
Fri, 10 Jun 2016 11:22:10 -0700 (PDT)
Return-Path: <psmith@aquent.com>
Received: from mail-it0-x22f.google.com (mail-it0-x22f.google.com. [2607:f8b0:4001:c0b::22f])
by mx.google.com with ESMTPS id r42si13303340ioi.179.2016.06.10.11.22.10
for <cecycorrea@gmail.com>
(version=TLS1_2 cipher=ECDHE-RSA-AES128-GCM-SHA256 bits=128/128);
Fri, 10 Jun 2016 11:22:10 -0700 (PDT)
Received-SPF: neutral (google.com: 2607:f8b0:4001:c0b::22f is neither permitted nor denied by best guess record for domain of psmith@aquent.com) client-ip=2607:f8b0:4001:c0b::22f;
Authentication-Results: mx.google.com;
dkim=pass header.i=@aquent.com;
spf=neutral (google.com: 2607:f8b0:4001:c0b::22f is neither permitted nor denied by best guess record for domain of psmith@aquent.com) smtp.mailfrom=psmith@aquent.com;
dmarc=pass (p=NONE dis=NONE) header.from=aquent.com
Received: by mail-it0-x22f.google.com with SMTP id h190so74466ith.1
for <cecycorrea@gmail.com>; Fri, 10 Jun 2016 11:22:10 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=aquent.com; s=google-20160511;
h=mime-version:from:date:message-id:subject:to;
bh=4ZxaugmK0sLR93uHNX3OJCXdbTj563hgDLqeUflfw7Y=;
b=GBRp+ToK9iQ2mm6NIUL8rE8ZKyRj72Ab0FFQ9lZtAzDjpuTxfV/YHT6jacd58KNbQ4
QgHXXGbJahC1cG2oGsUSMGhj3fKvEdUdy2vDW32WKdaMR9lVUbe9VWtV0EO1YCdT8zWh
iJxp+JhSNwzxWZ4sQESxNnJn+5HOSQmIDh2aJvNU4/eE+mY/W6qXGUMWIQg8F88p0Zoh
01fTNHiBoEY5GuxwlvGzBH43uELNj2ondyyJQzJ4A6C7u4OX2FZXeUBBtXtae7onV8Dp
7MKTmMd8aOqPebEmjX9iOJLcXFF8Mp0XV96E9t7IjU3sfOIsmtXn9xWaYojM8WS2chcq
Y0iw==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
d=1e100.net; s=20130820;
h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
bh=4ZxaugmK0sLR93uHNX3OJCXdbTj563hgDLqeUflfw7Y=;
b=TZMEO4Qdg45EyMrSVIOQ1cIgBL8C+umXNasLZJOQEDESR2kmoXDp/2DA+/3GiVrIdE
2JT5HYq0FrtHEfMCu6kUCeFyNLFFakN/lnqMSet5H7cMC6deC9g42UZbPAYS2FQDofGO
K8NNhNxyVZaUBUH36/VbpIml/O9FtswucB9X069oyYCIGNUEhvhIaAvcU64ApCWsCJi1
IBh0RidAy4FFTCT4seAJl28i+GqbPd9kpwZ/7kVr8ukbVcKtE83rVgHVKC3hurEXTZ8I
11MBJuk8RkF7p/WbDI0W2/Y96LGSce/SoPgyjfYwk+5cuPwwOROl/bIzRZ8ZD/opW7X3
LY9w==
X-Gm-Message-State: ALyK8tKMDMmoUuVVjzJ3SCk6JnnDfEH6ImoMKgsAVwMyk8n3lDVFY0HZTfbAKMNOZKbdsrnwdz2J1cr0O7MLPGLK
X-Received: by 10.36.146.194 with SMTP id l185mr795333itd.94.1465582930063;
Fri, 10 Jun 2016 11:22:10 -0700 (PDT)
MIME-Version: 1.0
Received: by 10.79.113.14 with HTTP; Fri, 10 Jun 2016 11:21:50 -0700 (PDT)
From: "Smith, Peggy" <psmith@aquent.com>
Date: Fri, 10 Jun 2016 13:21:50 -0500
Message-ID: <CAJxUwi7LqaKE3SdtKcJGYiWjWPZqXdoNA=5MTrYJgdrDfSxHSQ@mail.gmail.com>
Subject: CMATX Summit - Team Excursions
To: Alicia Saba <alicia.k.saba@gmail.com>, Ashley Hunter <ashley@hmriskgroup.com>,
Cecy Correa <cecycorrea@gmail.com>, Danielle Geraci Thoma <danielle.geraci@gmail.com>,
Yahoo 1 <Dbalkanli@yahoo.com>, Jarrod Joplin <jarrodjoplin@gmail.com>,
Laura Des Enfants <Laura@dandacompany.com>, marque blackman <marque.blackman@gmail.com>,
Quin Adney <quinlan.adney@gmail.com>, Samantha Fagan <suprsam@gmail.com>,
Sarah Gee <geeeenius@gmail.com>, Sarah Dewey <sarah.o.dewey@gmail.com>,
=?UTF-8?Q?Zo=C3=AB_Symon?= <zoesymon@gmail.com>,
Jake Sullivan <jakesulli@gmail.com>, Richelle Ouellette <richelle.ouellette@gmail.com>,
Steve Golab <sgolab@aquent.com>
Content-Type: multipart/alternative; boundary=94eb2c05afd0efdebc0534f09d6e

--94eb2c05afd0efdebc0534f09d6e
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Hi Awesome CMATX Team Excursions,

I need an acronym. Jake?

We have some updates for the team but we want to do them over drinks and
during a fun day. Please join us for an afternoon of fun (bring the family
and friends).

Saturday June 25th
Radio Coffee and Beer
4204 Manchaca Rd.
3pm - ????

There is a nice outdoor area with covered picnic tables. If it gets too hot
we can move inside. Jake and I hope to see you there.

Peggy



*Peggy Smith*

Director of Business Development

VITAMIN T (Division of Aquent)


P: 512-861-2273

E: psmith@vitamintalent.com

A: 823 Congress Ave, Ste 705 Austin, TX 78701


*Visit the Apple App Store and download the Aquent Heads Up App FREE
today! *
*Vitamin T is the only talent agency offering an =E2=80=9Cin-hand=E2=80=9D =
solution to
getting you the people you need=E2=80=94NOW.*




Sent with MailTrack
<https://mailtrack.io/install?source=3Dsignature&lang=3Den&referral=3Dpsmit=
h@aquent.com&idSignature=3D22>

--94eb2c05afd0efdebc0534f09d6e
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

<div dir=3D"ltr">Hi Awesome CMATX Team Excursions,<div><br></div><div>I nee=
d an acronym. Jake?</div><div><br></div><div>We have some updates for the t=
eam but we want to do them over drinks and during a fun day. Please join us=
for an afternoon of fun (bring the family and friends).</div><div><br></di=
v><div>Saturday June 25th</div><div>Radio Coffee and Beer</div><div>4204 Ma=
nchaca Rd.</div><div>3pm - ????</div><div><br></div><div>There is a nice ou=
tdoor area with covered picnic tables. If it gets too hot we can move insid=
e. Jake and I hope to see you there.</div><div><br></div><div>Peggy</div><d=
iv><br></div><div><div><div class=3D"gmail_signature" data-smartmail=3D"gma=
il_signature"><div dir=3D"ltr"><span style=3D"border-collapse:collapse;colo=
r:rgb(80,0,80)"><p style=3D"margin:0px;line-height:14px"><br></p><p style=
=3D"margin:0px;line-height:14px"><br><span style=3D"font-size:10pt;font-fam=
ily:&quot;Arial Black&quot;;color:black"></span></p></span><div><p style=3D=
"font-size:small;font-family:arial;margin:0px"><span style=3D"vertical-alig=
n:baseline"><font color=3D"#000000"><b>Peggy Smith</b></font></span></p><p =
style=3D"font-family:arial;line-height:14px;margin:0px"><span style=3D"bord=
er-collapse:collapse;color:rgb(132,180,55);font-family:&quot;Arial Black&qu=
ot;;font-size:11px;line-height:12px"></span></p><p style=3D"font-family:ari=
al;margin:0px"><font color=3D"#84b437" face=3D"&#39;Arial Black&#39;"><span=
style=3D"border-collapse:collapse"></span></font></p><p style=3D"font-fami=
ly:arial;line-height:14px;margin:0px"><font color=3D"#84b437" face=3D"&#39;=
Arial Black&#39;"><span style=3D"font-size:8pt;line-height:12px">Director o=
f Business Development</span></font></p><p style=3D"font-family:arial;line-=
height:14px;margin:0px"><span style=3D"border-collapse:collapse;color:rgb(1=
32,180,55);font-family:&quot;Arial Black&quot;;font-size:11px;line-height:1=
2px">VITAMIN T (Division of Aquent)</span></p><p style=3D"font-family:arial=
;line-height:26px;margin:0px"><span style=3D"font-size:9pt;line-height:24px=
;font-family:&quot;Arial Black&quot;;color:rgb(106,168,79)"></span></p><p s=
tyle=3D"font-family:arial;line-height:14px;margin:0px"><span style=3D"font-=
size:9pt;line-height:13px;font-family:&quot;Arial Black&quot;;color:rgb(132=
,180,55)"><br></span></p><p style=3D"line-height:14px;margin:0px"><span sty=
le=3D"color:rgb(132,180,55);font-family:&quot;Arial Black&quot;;font-size:1=
1.1111px;line-height:11.9965px">P:</span><font color=3D"#000000" face=3D"ar=
ial, helvetica, sans-serif"><span style=3D"font-size:9pt;line-height:13px">=
=C2=A0</span><span style=3D"font-size:9pt;line-height:13px"><a value=3D"+15=
128612271" style=3D"color:rgb(34,34,34)">512-861-2273</a></span></font></p>=
<p style=3D"line-height:14px;margin:0px"><span style=3D"color:rgb(132,180,5=
5);font-family:&quot;Arial Black&quot;;font-size:11.1111px;line-height:11.9=
965px">E:</span><font color=3D"#000000" face=3D"arial, helvetica, sans-seri=
f"><span style=3D"font-size:9pt;line-height:13px">=C2=A0</span><span style=
=3D"font-size:12.2222px"><a href=3D"mailto:psmith@vitamintalent.com" style=
=3D"color:rgb(17,85,204)" target=3D"_blank">psmith@vitamintalent.com</a></s=
pan></font></p><p style=3D"margin:0px"><span style=3D"color:rgb(132,180,55)=
;font-family:&quot;Arial Black&quot;;font-size:11.1111px;line-height:11.996=
5px">A:</span><font color=3D"#000000" face=3D"arial, helvetica, sans-serif"=
><span style=3D"font-size:9pt">=C2=A0</span><span style=3D"font-size:9pt"><=
font>823 Congress Ave, Ste 705=C2=A0</font></span><span style=3D"font-size:=
9pt"><font>Austin, TX 78701</font></span></font></p><p style=3D"font-family=
:arial;line-height:19px;margin:0px"><br></p><p style=3D"margin:0px"><i styl=
e=3D"line-height:19px"><b>Visit the Apple App Store and download the Aquent=
Heads Up App FREE today!=C2=A0</b></i><br style=3D"line-height:19px"><i st=
yle=3D"line-height:19px">Vitamin T is the only talent agency offering an =
=E2=80=9Cin-hand=E2=80=9D solution to getting you the people you need=E2=80=
=94NOW.</i><br></p></div><div><font><font color=3D"#0000ff" face=3D"Arial">=
<span style=3D"white-space:pre-wrap"><br></span></font></font></div></div><=
/div></div>
<br><br><br><div class=3D""><font color=3D"#999999" class=3D"">Sent with <a=
href=3D"https://mailtrack.io/install?source=3Dsignature&amp;lang=3Den&amp;=
referral=3Dpsmith@aquent.com&amp;idSignature=3D22" class=3D"">MailTrack</a>=
</font></div></div><img width=3D"0" height=3D"0" class=3D"mailtrack-img" sr=
c=3D"https://mailtrack.io/trace/mail/1aceeb7103c342f378dcca0a1c750c7bc0b94f=
17231087.png"></div>

--94eb2c05afd0efdebc0534f09d6e--
